//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

package logger ;import (_f "fmt";_eb "io";_c "os";_e "path/filepath";_fc "runtime";);

// Error logs error message.
func (_cb WriterLogger )Error (format string ,args ...interface{}){if _cb .LogLevel >=LogLevelError {_cce :="\u005b\u0045\u0052\u0052\u004f\u0052\u005d\u0020";_cb .logToWriter (_cb .Output ,_cce ,format ,args ...);};};

// Trace does nothing for dummy logger.
func (DummyLogger )Trace (format string ,args ...interface{}){};

// Trace logs trace message.
func (_dc WriterLogger )Trace (format string ,args ...interface{}){if _dc .LogLevel >=LogLevelTrace {_ad :="\u005b\u0054\u0052\u0041\u0043\u0045\u005d\u0020";_dc .logToWriter (_dc .Output ,_ad ,format ,args ...);};};

// Notice does nothing for dummy logger.
func (DummyLogger )Notice (format string ,args ...interface{}){};

// Debug logs debug message.
func (_fb ConsoleLogger )Debug (format string ,args ...interface{}){if _fb .LogLevel >=LogLevelDebug {_bee :="\u005b\u0044\u0045\u0042\u0055\u0047\u005d\u0020";_fb .output (_c .Stdout ,_bee ,format ,args ...);};};

// Info does nothing for dummy logger.
func (DummyLogger )Info (format string ,args ...interface{}){};

// Info logs info message.
func (_edd ConsoleLogger )Info (format string ,args ...interface{}){if _edd .LogLevel >=LogLevelInfo {_be :="\u005bI\u004e\u0046\u004f\u005d\u0020";_edd .output (_c .Stdout ,_be ,format ,args ...);};};

// IsLogLevel returns true if log level is greater or equal than `level`.
// Can be used to avoid resource intensive calls to loggers.
func (_bg WriterLogger )IsLogLevel (level LogLevel )bool {return _bg .LogLevel >=level };func _abe (_cba _eb .Writer ,_cdc string ,_eeb string ,_aga ...interface{}){_ ,_ccea ,_beb ,_cgf :=_fc .Caller (3);if !_cgf {_ccea ="\u003f\u003f\u003f";_beb =0;}else {_ccea =_e .Base (_ccea );};_af :=_f .Sprintf ("\u0025s\u0020\u0025\u0073\u003a\u0025\u0064 ",_cdc ,_ccea ,_beb )+_eeb +"\u000a";_f .Fprintf (_cba ,_af ,_aga ...);};

// SetLogger sets 'logger' to be used by the unidoc unipdf library.
func SetLogger (logger Logger ){Log =logger };

// Notice logs notice message.
func (_gb ConsoleLogger )Notice (format string ,args ...interface{}){if _gb .LogLevel >=LogLevelNotice {_bbg :="\u005bN\u004f\u0054\u0049\u0043\u0045\u005d ";_gb .output (_c .Stdout ,_bbg ,format ,args ...);};};

// IsLogLevel returns true if log level is greater or equal than `level`.
// Can be used to avoid resource intensive calls to loggers.
func (_gca ConsoleLogger )IsLogLevel (level LogLevel )bool {return _gca .LogLevel >=level };

// DummyLogger does nothing.
type DummyLogger struct{};var Log Logger =DummyLogger {};

// Notice logs notice message.
func (_daf WriterLogger )Notice (format string ,args ...interface{}){if _daf .LogLevel >=LogLevelNotice {_cbg :="\u005bN\u004f\u0054\u0049\u0043\u0045\u005d ";_daf .logToWriter (_daf .Output ,_cbg ,format ,args ...);};};

// WriterLogger is the logger that writes data to the Output writer
type WriterLogger struct{LogLevel LogLevel ;Output _eb .Writer ;};

// Warning does nothing for dummy logger.
func (DummyLogger )Warning (format string ,args ...interface{}){};

// IsLogLevel returns true from dummy logger.
func (DummyLogger )IsLogLevel (level LogLevel )bool {return true };func (_gbf WriterLogger )logToWriter (_cd _eb .Writer ,_ggc string ,_de string ,_dad ...interface{}){_abe (_cd ,_ggc ,_de ,_dad );};

// Warning logs warning message.
func (_acd WriterLogger )Warning (format string ,args ...interface{}){if _acd .LogLevel >=LogLevelWarning {_fe :="\u005b\u0057\u0041\u0052\u004e\u0049\u004e\u0047\u005d\u0020";_acd .logToWriter (_acd .Output ,_fe ,format ,args ...);};};

// Debug logs debug message.
func (_bf WriterLogger )Debug (format string ,args ...interface{}){if _bf .LogLevel >=LogLevelDebug {_bcb :="\u005b\u0044\u0045\u0042\u0055\u0047\u005d\u0020";_bf .logToWriter (_bf .Output ,_bcb ,format ,args ...);};};

// ConsoleLogger is a logger that writes logs to the 'os.Stdout'
type ConsoleLogger struct{LogLevel LogLevel ;};

// Warning logs warning message.
func (_da ConsoleLogger )Warning (format string ,args ...interface{}){if _da .LogLevel >=LogLevelWarning {_bb :="\u005b\u0057\u0041\u0052\u004e\u0049\u004e\u0047\u005d\u0020";_da .output (_c .Stdout ,_bb ,format ,args ...);};};

// Trace logs trace message.
func (_ag ConsoleLogger )Trace (format string ,args ...interface{}){if _ag .LogLevel >=LogLevelTrace {_ee :="\u005b\u0054\u0052\u0041\u0043\u0045\u005d\u0020";_ag .output (_c .Stdout ,_ee ,format ,args ...);};};

// LogLevel is the verbosity level for logging.
type LogLevel int ;const (LogLevelTrace LogLevel =5;LogLevelDebug LogLevel =4;LogLevelInfo LogLevel =3;LogLevelNotice LogLevel =2;LogLevelWarning LogLevel =1;LogLevelError LogLevel =0;);

// Info logs info message.
func (_ae WriterLogger )Info (format string ,args ...interface{}){if _ae .LogLevel >=LogLevelInfo {_ab :="\u005bI\u004e\u0046\u004f\u005d\u0020";_ae .logToWriter (_ae .Output ,_ab ,format ,args ...);};};

// Error logs error message.
func (_ge ConsoleLogger )Error (format string ,args ...interface{}){if _ge .LogLevel >=LogLevelError {_db :="\u005b\u0045\u0052\u0052\u004f\u0052\u005d\u0020";_ge .output (_c .Stdout ,_db ,format ,args ...);};};

// NewWriterLogger creates new 'writer' logger.
func NewWriterLogger (logLevel LogLevel ,writer _eb .Writer )*WriterLogger {logger :=WriterLogger {Output :writer ,LogLevel :logLevel };return &logger ;};func (_ef ConsoleLogger )output (_cg _eb .Writer ,_fbd string ,_ac string ,_dg ...interface{}){_abe (_cg ,_fbd ,_ac ,_dg ...);};

// NewConsoleLogger creates new console logger.
func NewConsoleLogger (logLevel LogLevel )*ConsoleLogger {return &ConsoleLogger {LogLevel :logLevel }};

// Debug does nothing for dummy logger.
func (DummyLogger )Debug (format string ,args ...interface{}){};

// Error does nothing for dummy logger.
func (DummyLogger )Error (format string ,args ...interface{}){};

// Logger is the interface used for logging in the unipdf package.
type Logger interface{Error (_a string ,_b ...interface{});Warning (_g string ,_cc ...interface{});Notice (_bc string ,_ed ...interface{});Info (_ga string ,_ea ...interface{});Debug (_ce string ,_gd ...interface{});Trace (_gg string ,_ebf ...interface{});IsLogLevel (_gc LogLevel )bool ;};