//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

package chart ;import (_e "fmt";_be "github.com/unidoc/unioffice";_bf "github.com/unidoc/unioffice/color";_a "github.com/unidoc/unioffice/drawing";_ea "github.com/unidoc/unioffice/measurement";_bfg "github.com/unidoc/unioffice/schema/soo/dml";_bb "github.com/unidoc/unioffice/schema/soo/dml/chart";
_g "math/rand";);func (_gdg RadarChart )AddAxis (axis Axis ){_bef :=_bb .NewCT_UnsignedInt ();_bef .ValAttr =axis .AxisID ();_gdg ._eace .AxId =append (_gdg ._eace .AxId ,_bef );};

// SetExplosion sets the value that the segements of the pie are 'exploded' by
func (_fab PieChartSeries )SetExplosion (v uint32 ){_fab ._aga .Explosion =_bb .NewCT_UnsignedInt ();_fab ._aga .Explosion .ValAttr =v ;};

// SetText sets the series text.
func (_gbe BubbleChartSeries )SetText (s string ){_gbe ._gca .Tx =_bb .NewCT_SerTx ();_gbe ._gca .Tx .Choice .V =&s ;};var NullAxis Axis =nullAxis (0);

// Properties returns the bar chart series shape properties.
func (_egfe PieChartSeries )Properties ()_a .ShapeProperties {if _egfe ._aga .SpPr ==nil {_egfe ._aga .SpPr =_bfg .NewCT_ShapeProperties ();};return _a .MakeShapeProperties (_egfe ._aga .SpPr );};func (_ega CategoryAxis )SetTickLabelPosition (p _bb .ST_TickLblPos ){if p ==_bb .ST_TickLblPosUnset {_ega ._cf .TickLblPos =nil ;
}else {_ega ._cf .TickLblPos =_bb .NewCT_TickLblPos ();_ega ._cf .TickLblPos .ValAttr =p ;};};func (_egdc chartBase )nextColor (_eac int )_bf .Color {return _aegf [_eac %len (_aegf )]};

// InitializeDefaults the bar chart to its defaults
func (_abg RadarChart )InitializeDefaults (){_abg ._eace .RadarStyle .ValAttr =_bb .ST_RadarStyleMarker };type Line3DChart struct{chartBase ;_gdb *_bb .CT_Line3DChart ;};

// AddSeries adds a default series to a bar chart.
func (_ada BarChart )AddSeries ()BarChartSeries {_gg :=_ada .nextColor (len (_ada ._cc .Ser ));_fbf :=_bb .NewCT_BarSer ();_ada ._cc .Ser =append (_ada ._cc .Ser ,_fbf );_fbf .Idx .ValAttr =uint32 (len (_ada ._cc .Ser )-1);_fbf .Order .ValAttr =uint32 (len (_ada ._cc .Ser )-1);
_gb :=BarChartSeries {_fbf };_gb .InitializeDefaults ();_gb .Properties ().SetSolidFill (_gg );return _gb ;};func (_eae DateAxis )SetMajorTickMark (m _bb .ST_TickMark ){if m ==_bb .ST_TickMarkUnset {_eae ._baa .MajorTickMark =nil ;}else {_eae ._baa .MajorTickMark =_bb .NewCT_TickMark ();
_eae ._baa .MajorTickMark .ValAttr =m ;};};

// Properties returns the bar chart series shape properties.
func (_bce RadarChartSeries )Properties ()_a .ShapeProperties {if _bce ._affb .SpPr ==nil {_bce ._affb .SpPr =_bfg .NewCT_ShapeProperties ();};return _a .MakeShapeProperties (_bce ._affb .SpPr );};func (_fgf ScatterChart )InitializeDefaults (){_fgf ._ege .ScatterStyle .ValAttr =_bb .ST_ScatterStyleMarker ;
};func MakeCategoryAxis (x *_bb .CT_CatAx )CategoryAxis {return CategoryAxis {x }};type Legend struct{_cabfa *_bb .CT_Legend };func (_egfg SeriesAxis )AxisID ()uint32 {return _egfg ._fbfb .AxId .ValAttr };

// BubbleChart is a 2D Bubble chart.
type BubbleChart struct{chartBase ;_ebg *_bb .CT_BubbleChart ;};

// InitializeDefaults the bar chart to its defaults
func (_bdee DoughnutChart )InitializeDefaults (){_bdee ._cec .VaryColors =_bb .NewCT_Boolean ();_bdee ._cec .VaryColors .ValAttr =_be .Bool (true );_bdee ._cec .HoleSize =_bb .NewCT_HoleSize ();_bdee ._cec .HoleSize .ValAttr =&_bb .ST_HoleSize {};_bdee ._cec .HoleSize .ValAttr .ST_HoleSizeUByte =_be .Uint8 (50);
};

// AddSeries adds a default series to a Scatter chart.
func (_deag ScatterChart )AddSeries ()ScatterChartSeries {_feeb :=_deag .nextColor (len (_deag ._ege .Ser ));_ead :=_bb .NewCT_ScatterSer ();_deag ._ege .Ser =append (_deag ._ege .Ser ,_ead );_ead .Idx .ValAttr =uint32 (len (_deag ._ege .Ser )-1);_ead .Order .ValAttr =uint32 (len (_deag ._ege .Ser )-1);
_fceb :=ScatterChartSeries {_ead };_fceb .InitializeDefaults ();_fceb .Marker ().Properties ().LineProperties ().SetSolidFill (_feeb );_fceb .Marker ().Properties ().SetSolidFill (_feeb );return _fceb ;};

// X returns the inner wrapped XML type.
func (_efg ScatterChartSeries )X ()*_bb .CT_ScatterSer {return _efg ._becd };func (_ebeg NumberDataSource )SetReference (s string ){_ebeg .ensureChoice ();if _ebeg ._gacc .Choice .NumRef ==nil {_ebeg ._gacc .Choice .NumRef =_bb .NewCT_NumRef ();};_ebeg ._gacc .Choice .NumRef .F =s ;
};

// InitializeDefaults the bar chart to its defaults
func (_dec Pie3DChart )InitializeDefaults (){_dec ._ecae .VaryColors =_bb .NewCT_Boolean ();_dec ._ecae .VaryColors .ValAttr =_be .Bool (true );};

// AddScatterChart adds a scatter (X/Y) chart.
func (_gaf Chart )AddScatterChart ()ScatterChart {_dba :=_bb .NewCT_PlotAreaChoice ();_gaf ._dda .Chart .PlotArea .Choice =append (_gaf ._dda .Chart .PlotArea .Choice ,_dba );_dba .ScatterChart =_bb .NewCT_ScatterChart ();_ebe :=ScatterChart {_ege :_dba .ScatterChart };
_ebe .InitializeDefaults ();return _ebe ;};

// Properties returns the chart's shape properties.
func (_cde Chart )Properties ()_a .ShapeProperties {if _cde ._dda .SpPr ==nil {_cde ._dda .SpPr =_bfg .NewCT_ShapeProperties ();};return _a .MakeShapeProperties (_cde ._dda .SpPr );};

// SetText sets the series text.
func (_bec BarChartSeries )SetText (s string ){_bec ._ab .Tx =_bb .NewCT_SerTx ();_bec ._ab .Tx .Choice .V =&s ;};

// X returns the inner wrapped XML type.
func (_dg BarChartSeries )X ()*_bb .CT_BarSer {return _dg ._ab };

// AddSurface3DChart adds a new 3D surface chart to a chart.
func (_bab Chart )AddSurface3DChart ()Surface3DChart {_aff :=_bb .NewCT_PlotAreaChoice ();_bab ._dda .Chart .PlotArea .Choice =append (_bab ._dda .Chart .PlotArea .Choice ,_aff );_aff .Surface3DChart =_bb .NewCT_Surface3DChart ();_ceaa (_bab ._dda .Chart );
_eag :=Surface3DChart {_ggaf :_aff .Surface3DChart };_eag .InitializeDefaults ();return _eag ;};func (_fag Marker )Properties ()_a .ShapeProperties {if _fag ._ebcb .SpPr ==nil {_fag ._ebcb .SpPr =_bfg .NewCT_ShapeProperties ();};return _a .MakeShapeProperties (_fag ._ebcb .SpPr );
};

// AddValueAxis adds a value axis to the chart.
func (_ebcd Chart )AddValueAxis ()ValueAxis {_bfb :=_bb .NewCT_ValAx ();if _ebcd ._dda .Chart .PlotArea .CChoice ==nil {_ebcd ._dda .Chart .PlotArea .CChoice =_bb .NewCT_PlotAreaChoice1 ();};_bfb .AxId =_bb .NewCT_UnsignedInt ();_bfb .AxId .ValAttr =0x7FFFFFFF&_g .Uint32 ();
_ebcd ._dda .Chart .PlotArea .CChoice .ValAx =append (_ebcd ._dda .Chart .PlotArea .CChoice .ValAx ,_bfb );_bfb .Delete =_bb .NewCT_Boolean ();_bfb .Delete .ValAttr =_be .Bool (false );_bfb .Scaling =_bb .NewCT_Scaling ();_bfb .Scaling .Orientation =_bb .NewCT_Orientation ();
_bfb .Scaling .Orientation .ValAttr =_bb .ST_OrientationMinMax ;_bfb .Choice =&_bb .EG_AxSharedChoice {};_bfb .Choice .Crosses =_bb .NewCT_Crosses ();_bfb .Choice .Crosses .ValAttr =_bb .ST_CrossesAutoZero ;_bfb .CrossBetween =_bb .NewCT_CrossBetween ();
_bfb .CrossBetween .ValAttr =_bb .ST_CrossBetweenBetween ;_bde :=MakeValueAxis (_bfb );_bde .MajorGridLines ().Properties ().LineProperties ().SetSolidFill (_bf .LightGray );_bde .SetMajorTickMark (_bb .ST_TickMarkOut );_bde .SetMinorTickMark (_bb .ST_TickMarkIn );
_bde .SetTickLabelPosition (_bb .ST_TickLblPosNextTo );_bde .Properties ().LineProperties ().SetSolidFill (_bf .Black );_bde .SetPosition (_bb .ST_AxPosL );return _bde ;};func (_dbef Title )ParagraphProperties ()_a .ParagraphProperties {if _dbef ._aadb .Tx ==nil {_dbef .SetText ("");
};if _dbef ._aadb .Tx .Choice .Rich .P [0].PPr ==nil {_dbef ._aadb .Tx .Choice .Rich .P [0].PPr =_bfg .NewCT_TextParagraphProperties ();};return _a .MakeParagraphProperties (_dbef ._aadb .Tx .Choice .Rich .P [0].PPr );};func (_ggad LineChartSeries )SetSmooth (b bool ){_ggad ._dfg .Smooth =_bb .NewCT_Boolean ();
_ggad ._dfg .Smooth .ValAttr =&b ;};

// X returns the inner wrapped XML type.
func (_egg AreaChartSeries )X ()*_bb .CT_AreaSer {return _egg ._fb };

// InitializeDefaults the bar chart to its defaults
func (_cgd PieChart )InitializeDefaults (){_cgd ._cgf .VaryColors =_bb .NewCT_Boolean ();_cgd ._cgf .VaryColors .ValAttr =_be .Bool (true );};

// InitializeDefaults the Bubble chart to its defaults
func (_ef BubbleChart )InitializeDefaults (){};

// SetIndex sets the index of the series
func (_bed LineChartSeries )SetIndex (idx uint32 ){_bed ._dfg .Idx .ValAttr =idx };

// X returns the inner wrapped XML type.
func (_gaad RadarChartSeries )X ()*_bb .CT_RadarSer {return _gaad ._affb };func (_fcdd BubbleChart )AddAxis (axis Axis ){_gfc :=_bb .NewCT_UnsignedInt ();_gfc .ValAttr =axis .AxisID ();_fcdd ._ebg .AxId =append (_fcdd ._ebg .AxId ,_gfc );};func (_bcd DataLabels )SetShowCategoryName (b bool ){_bcd .ensureChoice ();
_bcd ._ede .Choice .ShowCatName =_bb .NewCT_Boolean ();_bcd ._ede .Choice .ShowCatName .ValAttr =_be .Bool (b );};

// X returns the inner wrapped XML type.
func (_dcd GridLines )X ()*_bb .CT_ChartLines {return _dcd ._dff };

// X returns the inner wrapped XML type.
func (_bdc RadarChart )X ()*_bb .CT_RadarChart {return _bdc ._eace };

// InitializeDefaults initializes an Radar series to the default values.
func (_fcg RadarChartSeries )InitializeDefaults (){};

// AddLineChart adds a new line chart to a chart.
func (_ac Chart )AddLineChart ()LineChart {_beg :=_bb .NewCT_PlotAreaChoice ();_ac ._dda .Chart .PlotArea .Choice =append (_ac ._dda .Chart .PlotArea .Choice ,_beg );_beg .LineChart =_bb .NewCT_LineChart ();_beg .LineChart .Grouping =_bb .NewCT_Grouping ();
_beg .LineChart .Grouping .ValAttr =_bb .ST_GroupingStandard ;return LineChart {_fbb :_beg .LineChart };};

// Index returns the index of the series
func (_fcf SurfaceChartSeries )Index ()uint32 {return _fcf ._gcgf .Idx .ValAttr };

// AddAxis adds an axis to a Scatter chart.
func (_acd ScatterChart )AddAxis (axis Axis ){_eacg :=_bb .NewCT_UnsignedInt ();_eacg .ValAttr =axis .AxisID ();_acd ._ege .AxId =append (_acd ._ege .AxId ,_eacg );};

// AddSeries adds a default series to an Doughnut chart.
func (_gbd DoughnutChart )AddSeries ()PieChartSeries {_gda :=_bb .NewCT_PieSer ();_gbd ._cec .Ser =append (_gbd ._cec .Ser ,_gda );_gda .Idx .ValAttr =uint32 (len (_gbd ._cec .Ser )-1);_gda .Order .ValAttr =uint32 (len (_gbd ._cec .Ser )-1);_gbc :=PieChartSeries {_gda };
_gbc .InitializeDefaults ();return _gbc ;};

// SetValues is used to set the source data to a set of values.
func (_eeb CategoryAxisDataSource )SetValues (v []string ){_eeb ._ed .Choice =_bb .NewCT_AxDataSourceChoice ();_eeb ._ed .Choice .StrLit =_bb .NewCT_StrData ();_eeb ._ed .Choice .StrLit .PtCount =_bb .NewCT_UnsignedInt ();_eeb ._ed .Choice .StrLit .PtCount .ValAttr =uint32 (len (v ));
for _ga ,_cab :=range v {_eeb ._ed .Choice .StrLit .Pt =append (_eeb ._ed .Choice .StrLit .Pt ,&_bb .CT_StrVal {IdxAttr :uint32 (_ga ),V :_cab });};};

// InitializeDefaults the bar chart to its defaults
func (_efa PieOfPieChart )InitializeDefaults (){_efa ._fbc .VaryColors =_bb .NewCT_Boolean ();_efa ._fbc .VaryColors .ValAttr =_be .Bool (true );_efa .SetType (_bb .ST_OfPieTypePie );_efa ._fbc .SecondPieSize =_bb .NewCT_SecondPieSize ();_efa ._fbc .SecondPieSize .ValAttr =&_bb .ST_SecondPieSize {};
_efa ._fbc .SecondPieSize .ValAttr .ST_SecondPieSizeUShort =_be .Uint16 (75);_eaeg :=_bb .NewCT_ChartLines ();_eaeg .SpPr =_bfg .NewCT_ShapeProperties ();_aab :=_a .MakeShapeProperties (_eaeg .SpPr );_aab .LineProperties ().SetSolidFill (_bf .Auto );_efa ._fbc .SerLines =append (_efa ._fbc .SerLines ,_eaeg );
};

// X returns the inner wrapped XML type.
func (_dce BubbleChart )X ()*_bb .CT_BubbleChart {return _dce ._ebg };

// AddSeries adds a default series to a Surface chart.
func (_dcg Surface3DChart )AddSeries ()SurfaceChartSeries {_aaa :=_dcg .nextColor (len (_dcg ._ggaf .Ser ));_aadd :=_bb .NewCT_SurfaceSer ();_dcg ._ggaf .Ser =append (_dcg ._ggaf .Ser ,_aadd );_aadd .Idx .ValAttr =uint32 (len (_dcg ._ggaf .Ser )-1);_aadd .Order .ValAttr =uint32 (len (_dcg ._ggaf .Ser )-1);
_ddbb :=SurfaceChartSeries {_aadd };_ddbb .InitializeDefaults ();_ddbb .Properties ().LineProperties ().SetSolidFill (_aaa );return _ddbb ;};func (_fee Legend )SetOverlay (b bool ){_fee ._cabfa .Overlay =_bb .NewCT_Boolean ();_fee ._cabfa .Overlay .ValAttr =_be .Bool (b );
};func (_bfbe ValueAxis )MajorGridLines ()GridLines {if _bfbe ._adg .MajorGridlines ==nil {_bfbe ._adg .MajorGridlines =_bb .NewCT_ChartLines ();};return GridLines {_bfbe ._adg .MajorGridlines };};

// AddSeries adds a default series to a Bubble chart.
func (_eeg BubbleChart )AddSeries ()BubbleChartSeries {_bbb :=_eeg .nextColor (len (_eeg ._ebg .Ser ));_fcd :=_bb .NewCT_BubbleSer ();_eeg ._ebg .Ser =append (_eeg ._ebg .Ser ,_fcd );_fcd .Idx .ValAttr =uint32 (len (_eeg ._ebg .Ser )-1);_fcd .Order .ValAttr =uint32 (len (_eeg ._ebg .Ser )-1);
_ca :=BubbleChartSeries {_fcd };_ca .InitializeDefaults ();_ca .Properties ().SetSolidFill (_bbb );return _ca ;};

// AddRadarChart adds a new radar chart to a chart.
func (_deac Chart )AddRadarChart ()RadarChart {_bd :=_bb .NewCT_PlotAreaChoice ();_deac ._dda .Chart .PlotArea .Choice =append (_deac ._dda .Chart .PlotArea .Choice ,_bd );_bd .RadarChart =_bb .NewCT_RadarChart ();_dfa :=RadarChart {_eace :_bd .RadarChart };
_dfa .InitializeDefaults ();return _dfa ;};

// Values returns the value data source.
func (_gdda PieChartSeries )Values ()NumberDataSource {if _gdda ._aga .Val ==nil {_gdda ._aga .Val =_bb .NewCT_NumDataSource ();};return MakeNumberDataSource (_gdda ._aga .Val );};

// X returns the inner wrapped XML type.
func (_fcga Surface3DChart )X ()*_bb .CT_Surface3DChart {return _fcga ._ggaf };

// AddAreaChart adds a new area chart to a chart.
func (_aeb Chart )AddAreaChart ()AreaChart {_cag :=_bb .NewCT_PlotAreaChoice ();_aeb ._dda .Chart .PlotArea .Choice =append (_aeb ._dda .Chart .PlotArea .Choice ,_cag );_cag .AreaChart =_bb .NewCT_AreaChart ();_egf :=AreaChart {_df :_cag .AreaChart };_egf .InitializeDefaults ();
return _egf ;};

// Pie3DChart is a Pie3D chart.
type Pie3DChart struct{chartBase ;_ecae *_bb .CT_Pie3DChart ;};

// X returns the inner wrapped XML type.
func (_gbf BubbleChartSeries )X ()*_bb .CT_BubbleSer {return _gbf ._gca };

// AddSurfaceChart adds a new surface chart to a chart.
func (_ddf Chart )AddSurfaceChart ()SurfaceChart {_fdf :=_bb .NewCT_PlotAreaChoice ();_ddf ._dda .Chart .PlotArea .Choice =append (_ddf ._dda .Chart .PlotArea .Choice ,_fdf );_fdf .SurfaceChart =_bb .NewCT_SurfaceChart ();_ceaa (_ddf ._dda .Chart );_ddf ._dda .Chart .View3D .RotX .ValAttr =_be .Int8 (90);
_ddf ._dda .Chart .View3D .RotY .ValAttr =_be .Uint16 (0);_ddf ._dda .Chart .View3D .Perspective =_bb .NewCT_Perspective ();_ddf ._dda .Chart .View3D .Perspective .ValAttr =_be .Uint8 (0);_dcf :=SurfaceChart {_bgbg :_fdf .SurfaceChart };_dcf .InitializeDefaults ();
return _dcf ;};func (_gac DataLabels )SetShowLeaderLines (b bool ){_gac .ensureChoice ();_gac ._ede .Choice .ShowLeaderLines =_bb .NewCT_Boolean ();_gac ._ede .Choice .ShowLeaderLines .ValAttr =_be .Bool (b );};

// RemoveTitle removes any existing title from the chart.
func (_cfa Chart )RemoveTitle (){_cfa ._dda .Chart .Title =nil ;_cfa ._dda .Chart .AutoTitleDeleted =_bb .NewCT_Boolean ();_cfa ._dda .Chart .AutoTitleDeleted .ValAttr =_be .Bool (true );};func MakeChart (x *_bb .ChartSpace )Chart {return Chart {x }};

// PieChartSeries is a series to be used on an Pie chart.
type PieChartSeries struct{_aga *_bb .CT_PieSer };func (_cebc DateAxis )AxisID ()uint32 {return _cebc ._baa .AxId .ValAttr };

// Marker returns the marker properties.
func (_fac LineChartSeries )Marker ()Marker {if _fac ._dfg .Marker ==nil {_fac ._dfg .Marker =_bb .NewCT_Marker ();};return MakeMarker (_fac ._dfg .Marker );};func (_aa DataLabels )SetShowLegendKey (b bool ){_aa .ensureChoice ();_aa ._ede .Choice .ShowLegendKey =_bb .NewCT_Boolean ();
_aa ._ede .Choice .ShowLegendKey .ValAttr =_be .Bool (b );};

// SetHoleSize controls the hole size in the pie chart and is measured in percent.
func (_egb DoughnutChart )SetHoleSize (pct uint8 ){if _egb ._cec .HoleSize ==nil {_egb ._cec .HoleSize =_bb .NewCT_HoleSize ();};if _egb ._cec .HoleSize .ValAttr ==nil {_egb ._cec .HoleSize .ValAttr =&_bb .ST_HoleSize {};};_egb ._cec .HoleSize .ValAttr .ST_HoleSizeUByte =&pct ;
};func (_age Bar3DChart )AddAxis (axis Axis ){_gcf :=_bb .NewCT_UnsignedInt ();_gcf .ValAttr =axis .AxisID ();_age ._eggg .AxId =append (_age ._eggg .AxId ,_gcf );};

// InitializeDefaults the bar chart to its defaults
func (_cb Bar3DChart )InitializeDefaults (){_cb .SetDirection (_bb .ST_BarDirCol )};func (_ceb DataLabels )SetShowValue (b bool ){_ceb .ensureChoice ();_ceb ._ede .Choice .ShowVal =_bb .NewCT_Boolean ();_ceb ._ede .Choice .ShowVal .ValAttr =_be .Bool (b );
};

// InitializeDefaults initializes a Bubble chart series to the default values.
func (_cd BubbleChartSeries )InitializeDefaults (){};

// AddSeries adds a default series to a Stock chart.
func (_cged StockChart )AddSeries ()LineChartSeries {_fcb :=_bb .NewCT_LineSer ();_cged ._ccd .Ser =append (_cged ._ccd .Ser ,_fcb );_fcb .Idx .ValAttr =uint32 (len (_cged ._ccd .Ser )-1);_fcb .Order .ValAttr =uint32 (len (_cged ._ccd .Ser )-1);_bggc :=LineChartSeries {_fcb };
_bggc .Values ().CreateEmptyNumberCache ();_bggc .Properties ().LineProperties ().SetNoFill ();return _bggc ;};

// AddArea3DChart adds a new area chart to a chart.
func (_ggg Chart )AddArea3DChart ()Area3DChart {_ceaa (_ggg ._dda .Chart );_aeg :=_bb .NewCT_PlotAreaChoice ();_ggg ._dda .Chart .PlotArea .Choice =append (_ggg ._dda .Chart .PlotArea .Choice ,_aeg );_aeg .Area3DChart =_bb .NewCT_Area3DChart ();_bc :=Area3DChart {_eg :_aeg .Area3DChart };
_bc .InitializeDefaults ();return _bc ;};

// X returns the inner wrapped XML type.
func (_edcf ValueAxis )X ()*_bb .CT_ValAx {return _edcf ._adg };func (_fae Legend )InitializeDefaults (){_fae .SetPosition (_bb .ST_LegendPosR );_fae .SetOverlay (false );_fae .Properties ().SetNoFill ();_fae .Properties ().LineProperties ().SetNoFill ();
};

// AddAxis adds an axis to a line chart.
func (_fba Line3DChart )AddAxis (axis Axis ){_gga :=_bb .NewCT_UnsignedInt ();_gga .ValAttr =axis .AxisID ();_fba ._gdb .AxId =append (_fba ._gdb .AxId ,_gga );};func (_dfbg ValueAxis )SetPosition (p _bb .ST_AxPos ){_dfbg ._adg .AxPos =_bb .NewCT_AxPos ();
_dfbg ._adg .AxPos .ValAttr =p ;};func (_fdfc DataLabels )SetShowSeriesName (b bool ){_fdfc .ensureChoice ();_fdfc ._ede .Choice .ShowSerName =_bb .NewCT_Boolean ();_fdfc ._ede .Choice .ShowSerName .ValAttr =_be .Bool (b );};

// InitializeDefaults initializes an Pie series to the default values.
func (_gdd PieChartSeries )InitializeDefaults (){};

// SetOrder sets the order of the series
func (_bfed ScatterChartSeries )SetOrder (idx uint32 ){_bfed ._becd .Order .ValAttr =idx };type ScatterChart struct{chartBase ;_ege *_bb .CT_ScatterChart ;};var _aegf =[]_bf .Color {_bf .RGB (0x33,0x66,0xcc),_bf .RGB (0xDC,0x39,0x12),_bf .RGB (0xFF,0x99,0x00),_bf .RGB (0x10,0x96,0x18),_bf .RGB (0x99,0x00,0x99),_bf .RGB (0x3B,0x3E,0xAC),_bf .RGB (0x00,0x99,0xC6),_bf .RGB (0xDD,0x44,0x77),_bf .RGB (0x66,0xAA,0x00),_bf .RGB (0xB8,0x2E,0x2E),_bf .RGB (0x31,0x63,0x95),_bf .RGB (0x99,0x44,0x99),_bf .RGB (0x22,0xAA,0x99),_bf .RGB (0xAA,0xAA,0x11),_bf .RGB (0x66,0x33,0xCC),_bf .RGB (0xE6,0x73,0x00),_bf .RGB (0x8B,0x07,0x07),_bf .RGB (0x32,0x92,0x62),_bf .RGB (0x55,0x74,0xA6),_bf .RGB (0x3B,0x3E,0xAC)};


// BarChart is a 2D bar chart.
type BarChart struct{chartBase ;_cc *_bb .CT_BarChart ;};

// X returns the inner wrapped XML type.
func (_ecd SeriesAxis )X ()*_bb .CT_SerAx {return _ecd ._fbfb };type NumberDataSource struct{_gacc *_bb .CT_NumDataSource };

// X returns the inner wrapped XML type.
func (_def BarChart )X ()*_bb .CT_BarChart {return _def ._cc };func (_gdcb LineChartSeries )InitializeDefaults (){_gdcb .Properties ().LineProperties ().SetWidth (1*_ea .Point );_gdcb .Properties ().LineProperties ().SetSolidFill (_bf .Black );_gdcb .Properties ().LineProperties ().SetJoin (_a .LineJoinRound );
_gdcb .Marker ().SetSymbol (_bb .ST_MarkerStyleNone );_gdcb .Labels ().SetShowLegendKey (false );_gdcb .Labels ().SetShowValue (false );_gdcb .Labels ().SetShowPercent (false );_gdcb .Labels ().SetShowCategoryName (false );_gdcb .Labels ().SetShowSeriesName (false );
_gdcb .Labels ().SetShowLeaderLines (false );};func (_cbg ValueAxis )SetTickLabelPosition (p _bb .ST_TickLblPos ){if p ==_bb .ST_TickLblPosUnset {_cbg ._adg .TickLblPos =nil ;}else {_cbg ._adg .TickLblPos =_bb .NewCT_TickLblPos ();_cbg ._adg .TickLblPos .ValAttr =p ;
};};func (_cbbe DateAxis )Properties ()_a .ShapeProperties {if _cbbe ._baa .SpPr ==nil {_cbbe ._baa .SpPr =_bfg .NewCT_ShapeProperties ();};return _a .MakeShapeProperties (_cbbe ._baa .SpPr );};

// X returns the inner wrapped XML type.
func (_bdea Title )X ()*_bb .CT_Title {return _bdea ._aadb };

// X returns the inner wrapped XML type.
func (_ddde SurfaceChart )X ()*_bb .CT_SurfaceChart {return _ddde ._bgbg };

// AddSeries adds a default series to an Pie chart.
func (_bfd PieChart )AddSeries ()PieChartSeries {_bae :=_bb .NewCT_PieSer ();_bfd ._cgf .Ser =append (_bfd ._cgf .Ser ,_bae );_bae .Idx .ValAttr =uint32 (len (_bfd ._cgf .Ser )-1);_bae .Order .ValAttr =uint32 (len (_bfd ._cgf .Ser )-1);_abfd :=PieChartSeries {_bae };
_abfd .InitializeDefaults ();return _abfd ;};

// CategoryAxis returns the category data source.
func (_cee AreaChartSeries )CategoryAxis ()CategoryAxisDataSource {if _cee ._fb .Cat ==nil {_cee ._fb .Cat =_bb .NewCT_AxDataSource ();};return MakeAxisDataSource (_cee ._fb .Cat );};

// AreaChart is an area chart that has a shaded area underneath a curve.
type AreaChart struct{chartBase ;_df *_bb .CT_AreaChart ;};func (_dfe DataLabels )SetShowPercent (b bool ){_dfe .ensureChoice ();_dfe ._ede .Choice .ShowPercent =_bb .NewCT_Boolean ();_dfe ._ede .Choice .ShowPercent .ValAttr =_be .Bool (b );};

// X returns the inner wrapped XML type.
func (_ccc DoughnutChart )X ()*_bb .CT_DoughnutChart {return _ccc ._cec };

// SetText sets the series text.
func (_ce AreaChartSeries )SetText (s string ){_ce ._fb .Tx =_bb .NewCT_SerTx ();_ce ._fb .Tx .Choice .V =&s ;};func (_edd ScatterChartSeries )SetSmooth (b bool ){_edd ._becd .Smooth =_bb .NewCT_Boolean ();_edd ._becd .Smooth .ValAttr =&b ;};

// AddSeries adds a default series to an area chart.
func (_ec Area3DChart )AddSeries ()AreaChartSeries {_f :=_ec .nextColor (len (_ec ._eg .Ser ));_d :=_bb .NewCT_AreaSer ();_ec ._eg .Ser =append (_ec ._eg .Ser ,_d );_d .Idx .ValAttr =uint32 (len (_ec ._eg .Ser )-1);_d .Order .ValAttr =uint32 (len (_ec ._eg .Ser )-1);
_fg :=AreaChartSeries {_d };_fg .InitializeDefaults ();_fg .Properties ().SetSolidFill (_f );return _fg ;};

// CategoryAxis returns the category data source.
func (_dde PieChartSeries )CategoryAxis ()CategoryAxisDataSource {if _dde ._aga .Cat ==nil {_dde ._aga .Cat =_bb .NewCT_AxDataSource ();};return MakeAxisDataSource (_dde ._aga .Cat );};

// AddSeries adds a default series to a bar chart.
func (_cg Bar3DChart )AddSeries ()BarChartSeries {_ff :=_cg .nextColor (len (_cg ._eggg .Ser ));_fef :=_bb .NewCT_BarSer ();_cg ._eggg .Ser =append (_cg ._eggg .Ser ,_fef );_fef .Idx .ValAttr =uint32 (len (_cg ._eggg .Ser )-1);_fef .Order .ValAttr =uint32 (len (_cg ._eggg .Ser )-1);
_de :=BarChartSeries {_fef };_de .InitializeDefaults ();_de .Properties ().SetSolidFill (_ff );return _de ;};func MakeNumberDataSource (x *_bb .CT_NumDataSource )NumberDataSource {return NumberDataSource {x }};

// Properties returns the bar chart series shape properties.
func (_fga AreaChartSeries )Properties ()_a .ShapeProperties {if _fga ._fb .SpPr ==nil {_fga ._fb .SpPr =_bfg .NewCT_ShapeProperties ();};return _a .MakeShapeProperties (_fga ._fb .SpPr );};

// SetValues sets values directly on a source.
func (_bfc NumberDataSource )SetValues (v []float64 ){_bfc .ensureChoice ();_bfc ._gacc .Choice .NumRef =nil ;_bfc ._gacc .Choice .NumLit =_bb .NewCT_NumData ();_bfc ._gacc .Choice .NumLit .PtCount =_bb .NewCT_UnsignedInt ();_bfc ._gacc .Choice .NumLit .PtCount .ValAttr =uint32 (len (v ));
for _aae ,_bdb :=range v {_bfc ._gacc .Choice .NumLit .Pt =append (_bfc ._gacc .Choice .NumLit .Pt ,&_bb .CT_NumVal {IdxAttr :uint32 (_aae ),V :_e .Sprintf ("\u0025\u0067",_bdb )});};};

// Order returns the order of the series
func (_ecb ScatterChartSeries )Order ()uint32 {return _ecb ._becd .Order .ValAttr };

// BarChartSeries is a series to be used on a bar chart.
type BarChartSeries struct{_ab *_bb .CT_BarSer };func (_fgg DateAxis )MajorGridLines ()GridLines {if _fgg ._baa .MajorGridlines ==nil {_fgg ._baa .MajorGridlines =_bb .NewCT_ChartLines ();};return GridLines {_fgg ._baa .MajorGridlines };};

// SetOrder sets the order of the series
func (_bffa LineChartSeries )SetOrder (idx uint32 ){_bffa ._dfg .Order .ValAttr =idx };func (_gcaa CategoryAxis )InitializeDefaults (){_gcaa .SetPosition (_bb .ST_AxPosB );_gcaa .SetMajorTickMark (_bb .ST_TickMarkOut );_gcaa .SetMinorTickMark (_bb .ST_TickMarkIn );
_gcaa .SetTickLabelPosition (_bb .ST_TickLblPosNextTo );_gcaa .MajorGridLines ().Properties ().LineProperties ().SetSolidFill (_bf .LightGray );_gcaa .Properties ().LineProperties ().SetSolidFill (_bf .Black );};

// Values returns the value data source.
func (_adc BubbleChartSeries )Values ()NumberDataSource {if _adc ._gca .YVal ==nil {_adc ._gca .YVal =_bb .NewCT_NumDataSource ();};return MakeNumberDataSource (_adc ._gca .YVal );};

// AddSeries adds a default series to an Radar chart.
func (_agab RadarChart )AddSeries ()RadarChartSeries {_ddb :=_agab .nextColor (len (_agab ._eace .Ser ));_aaec :=_bb .NewCT_RadarSer ();_agab ._eace .Ser =append (_agab ._eace .Ser ,_aaec );_aaec .Idx .ValAttr =uint32 (len (_agab ._eace .Ser )-1);_aaec .Order .ValAttr =uint32 (len (_agab ._eace .Ser )-1);
_ffe :=RadarChartSeries {_aaec };_ffe .InitializeDefaults ();_ffe .Properties ().SetSolidFill (_ddb );return _ffe ;};

// Values returns the value data source.
func (_cea AreaChartSeries )Values ()NumberDataSource {if _cea ._fb .Val ==nil {_cea ._fb .Val =_bb .NewCT_NumDataSource ();};return MakeNumberDataSource (_cea ._fb .Val );};

// AddBar3DChart adds a new 3D bar chart to a chart.
func (_ba Chart )AddBar3DChart ()Bar3DChart {_ceaa (_ba ._dda .Chart );_cdd :=_bb .NewCT_PlotAreaChoice ();_ba ._dda .Chart .PlotArea .Choice =append (_ba ._dda .Chart .PlotArea .Choice ,_cdd );_cdd .Bar3DChart =_bb .NewCT_Bar3DChart ();_cdd .Bar3DChart .Grouping =_bb .NewCT_BarGrouping ();
_cdd .Bar3DChart .Grouping .ValAttr =_bb .ST_BarGroupingStandard ;_ddab :=Bar3DChart {_eggg :_cdd .Bar3DChart };_ddab .InitializeDefaults ();return _ddab ;};func (_ecaa nullAxis )AxisID ()uint32 {return 0};

// RadarChartSeries is a series to be used on an Radar chart.
type RadarChartSeries struct{_affb *_bb .CT_RadarSer };

// Index returns the index of the series
func (_afgd LineChartSeries )Index ()uint32 {return _afgd ._dfg .Idx .ValAttr };func (_agd Area3DChart )AddAxis (axis Axis ){_gc :=_bb .NewCT_UnsignedInt ();_gc .ValAttr =axis .AxisID ();_agd ._eg .AxId =append (_agd ._eg .AxId ,_gc );};

// X returns the inner wrapped XML type.
func (_bbd Legend )X ()*_bb .CT_Legend {return _bbd ._cabfa };

// SetIndex sets the index of the series
func (_egge SurfaceChartSeries )SetIndex (idx uint32 ){_egge ._gcgf .Idx .ValAttr =idx };

// AddLegend adds a legend to a chart, replacing any existing legend.
func (_efea Chart )AddLegend ()Legend {_efea ._dda .Chart .Legend =_bb .NewCT_Legend ();_acf :=MakeLegend (_efea ._dda .Chart .Legend );_acf .InitializeDefaults ();return _acf ;};func (_adb ValueAxis )AxisID ()uint32 {return _adb ._adg .AxId .ValAttr };


// ScatterChartSeries is the data series for a scatter chart.
type ScatterChartSeries struct{_becd *_bb .CT_ScatterSer };

// Labels returns the data label properties.
func (_efd LineChartSeries )Labels ()DataLabels {if _efd ._dfg .DLbls ==nil {_efd ._dfg .DLbls =_bb .NewCT_DLbls ();};return MakeDataLabels (_efd ._dfg .DLbls );};

// X returns the inner wrapped XML type.
func (_fec PieChart )X ()*_bb .CT_PieChart {return _fec ._cgf };

// X returns the inner wrapped XML type.
func (_cfc LineChartSeries )X ()*_bb .CT_LineSer {return _cfc ._dfg };

// X returns the inner wrapped XML type.
func (_dc Bar3DChart )X ()*_bb .CT_Bar3DChart {return _dc ._eggg };

// X returns the inner wrapped XML type.
func (_beca Chart )X ()*_bb .ChartSpace {return _beca ._dda };

// AddStockChart adds a new stock chart.
func (_bba Chart )AddStockChart ()StockChart {_gcfb :=_bb .NewCT_PlotAreaChoice ();_bba ._dda .Chart .PlotArea .Choice =append (_bba ._dda .Chart .PlotArea .Choice ,_gcfb );_gcfb .StockChart =_bb .NewCT_StockChart ();_edg :=StockChart {_ccd :_gcfb .StockChart };
_edg .InitializeDefaults ();return _edg ;};

// AddSeries adds a default series to an area chart.
func (_fc AreaChart )AddSeries ()AreaChartSeries {_fe :=_fc .nextColor (len (_fc ._df .Ser ));_gd :=_bb .NewCT_AreaSer ();_fc ._df .Ser =append (_fc ._df .Ser ,_gd );_gd .Idx .ValAttr =uint32 (len (_fc ._df .Ser )-1);_gd .Order .ValAttr =uint32 (len (_fc ._df .Ser )-1);
_fd :=AreaChartSeries {_gd };_fd .InitializeDefaults ();_fd .Properties ().SetSolidFill (_fe );return _fd ;};

// SetIndex sets the index of the series
func (_affcf ScatterChartSeries )SetIndex (idx uint32 ){_affcf ._becd .Idx .ValAttr =idx };

// InitializeDefaults the bar chart to its defaults
func (_af BarChart )InitializeDefaults (){_af .SetDirection (_bb .ST_BarDirCol )};

// AddAxis adds an axis to a line chart.
func (_bcg LineChart )AddAxis (axis Axis ){_ceg :=_bb .NewCT_UnsignedInt ();_ceg .ValAttr =axis .AxisID ();_bcg ._fbb .AxId =append (_bcg ._fbb .AxId ,_ceg );};func (_acb DateAxis )SetTickLabelPosition (p _bb .ST_TickLblPos ){if p ==_bb .ST_TickLblPosUnset {_acb ._baa .TickLblPos =nil ;
}else {_acb ._baa .TickLblPos =_bb .NewCT_TickLblPos ();_acb ._baa .TickLblPos .ValAttr =p ;};};

// SetDirection changes the direction of the bar chart (bar or column).
func (_gf Bar3DChart )SetDirection (d _bb .ST_BarDir ){_gf ._eggg .BarDir .ValAttr =d };func (_bgg CategoryAxis )MajorGridLines ()GridLines {if _bgg ._cf .MajorGridlines ==nil {_bgg ._cf .MajorGridlines =_bb .NewCT_ChartLines ();};return GridLines {_bgg ._cf .MajorGridlines };
};

// X returns the inner wrapped XML type.
func (_edf StockChart )X ()*_bb .CT_StockChart {return _edf ._ccd };

// AddSeries adds a default series to a Surface chart.
func (_cbdd SurfaceChart )AddSeries ()SurfaceChartSeries {_agdd :=_cbdd .nextColor (len (_cbdd ._bgbg .Ser ));_egdcc :=_bb .NewCT_SurfaceSer ();_cbdd ._bgbg .Ser =append (_cbdd ._bgbg .Ser ,_egdcc );_egdcc .Idx .ValAttr =uint32 (len (_cbdd ._bgbg .Ser )-1);
_egdcc .Order .ValAttr =uint32 (len (_cbdd ._bgbg .Ser )-1);_egff :=SurfaceChartSeries {_egdcc };_egff .InitializeDefaults ();_egff .Properties ().LineProperties ().SetSolidFill (_agdd );return _egff ;};

// AddSeries adds a default series to a line chart.
func (_agc Line3DChart )AddSeries ()LineChartSeries {_cdc :=_agc .nextColor (len (_agc ._gdb .Ser ));_bfee :=_bb .NewCT_LineSer ();_agc ._gdb .Ser =append (_agc ._gdb .Ser ,_bfee );_bfee .Idx .ValAttr =uint32 (len (_agc ._gdb .Ser )-1);_bfee .Order .ValAttr =uint32 (len (_agc ._gdb .Ser )-1);
_adcc :=LineChartSeries {_bfee };_adcc .InitializeDefaults ();_adcc .Properties ().LineProperties ().SetSolidFill (_cdc );_adcc .Properties ().SetSolidFill (_cdc );return _adcc ;};func (_bcda ValueAxis )SetCrosses (axis Axis ){_bcda ._adg .CrossAx .ValAttr =axis .AxisID ()};
func (_fca DateAxis )SetCrosses (axis Axis ){_fca ._baa .CrossAx .ValAttr =axis .AxisID ()};

// SetLabelReference is used to set the source data to a range of cells
// containing strings.
func (_fge CategoryAxisDataSource )SetLabelReference (s string ){_fge ._ed .Choice =_bb .NewCT_AxDataSourceChoice ();_fge ._ed .Choice .StrRef =_bb .NewCT_StrRef ();_fge ._ed .Choice .StrRef .F =s ;};

// SurfaceChart is a 3D surface chart, viewed from the top-down.
type SurfaceChart struct{chartBase ;_bgbg *_bb .CT_SurfaceChart ;};

// SetText sets the series text
func (_cae SurfaceChartSeries )SetText (s string ){_cae ._gcgf .Tx =_bb .NewCT_SerTx ();_cae ._gcgf .Tx .Choice .V =&s ;};

// AddSeries adds a default series to an Pie chart.
func (_beee PieOfPieChart )AddSeries ()PieChartSeries {_egbg :=_bb .NewCT_PieSer ();_beee ._fbc .Ser =append (_beee ._fbc .Ser ,_egbg );_egbg .Idx .ValAttr =uint32 (len (_beee ._fbc .Ser )-1);_egbg .Order .ValAttr =uint32 (len (_beee ._fbc .Ser )-1);_fgc :=PieChartSeries {_egbg };
_fgc .InitializeDefaults ();return _fgc ;};

// X returns the inner wrapped XML type.
func (_ddc PieChartSeries )X ()*_bb .CT_PieSer {return _ddc ._aga };

// SetText sets the series text.
func (_ecc RadarChartSeries )SetText (s string ){_ecc ._affb .Tx =_bb .NewCT_SerTx ();_ecc ._affb .Tx .Choice .V =&s ;};

// AddLine3DChart adds a new 3D line chart to a chart.
func (_gaa Chart )AddLine3DChart ()Line3DChart {_ceaa (_gaa ._dda .Chart );_dbf :=_bb .NewCT_PlotAreaChoice ();_gaa ._dda .Chart .PlotArea .Choice =append (_gaa ._dda .Chart .PlotArea .Choice ,_dbf );_dbf .Line3DChart =_bb .NewCT_Line3DChart ();_dbf .Line3DChart .Grouping =_bb .NewCT_Grouping ();
_dbf .Line3DChart .Grouping .ValAttr =_bb .ST_GroupingStandard ;return Line3DChart {_gdb :_dbf .Line3DChart };};

// AddSeries adds a default series to an Pie3D chart.
func (_gfb Pie3DChart )AddSeries ()PieChartSeries {_ggc :=_bb .NewCT_PieSer ();_gfb ._ecae .Ser =append (_gfb ._ecae .Ser ,_ggc );_ggc .Idx .ValAttr =uint32 (len (_gfb ._ecae .Ser )-1);_ggc .Order .ValAttr =uint32 (len (_gfb ._ecae .Ser )-1);_dbg :=PieChartSeries {_ggc };
_dbg .InitializeDefaults ();return _dbg ;};func MakeMarker (x *_bb .CT_Marker )Marker {return Marker {x }};type LineChart struct{chartBase ;_fbb *_bb .CT_LineChart ;};type chartBase struct{};type ValueAxis struct{_adg *_bb .CT_ValAx };func (_gbcf SeriesAxis )SetCrosses (axis Axis ){_gbcf ._fbfb .CrossAx .ValAttr =axis .AxisID ()};
func (_bea SurfaceChartSeries )Values ()NumberDataSource {if _bea ._gcgf .Val ==nil {_bea ._gcgf .Val =_bb .NewCT_NumDataSource ();};_dbeb :=MakeNumberDataSource (_bea ._gcgf .Val );_dbeb .CreateEmptyNumberCache ();return _dbeb ;};func (_cac CategoryAxis )SetMinorTickMark (m _bb .ST_TickMark ){if m ==_bb .ST_TickMarkUnset {_cac ._cf .MinorTickMark =nil ;
}else {_cac ._cf .MinorTickMark =_bb .NewCT_TickMark ();_cac ._cf .MinorTickMark .ValAttr =m ;};};

// AreaChartSeries is a series to be used on an area chart.
type AreaChartSeries struct{_fb *_bb .CT_AreaSer };func MakeLegend (l *_bb .CT_Legend )Legend {return Legend {l }};

// CreateEmptyNumberCache creates an empty number cache, which is used sometimes
// to increase file format compatibility.  It should actually contain the
// computed cell data, but just creating an empty one is good enough.
func (_affc NumberDataSource )CreateEmptyNumberCache (){_affc .ensureChoice ();if _affc ._gacc .Choice .NumRef ==nil {_affc ._gacc .Choice .NumRef =_bb .NewCT_NumRef ();};_affc ._gacc .Choice .NumLit =nil ;_affc ._gacc .Choice .NumRef .NumCache =_bb .NewCT_NumData ();
_affc ._gacc .Choice .NumRef .NumCache .PtCount =_bb .NewCT_UnsignedInt ();_affc ._gacc .Choice .NumRef .NumCache .PtCount .ValAttr =0;};

// X returns the inner wrapped XML type.
func (_baaa Pie3DChart )X ()*_bb .CT_Pie3DChart {return _baaa ._ecae };

// AddPieChart adds a new pie chart to a chart.
func (_ebf Chart )AddPieChart ()PieChart {_bfe :=_bb .NewCT_PlotAreaChoice ();_ebf ._dda .Chart .PlotArea .Choice =append (_ebf ._dda .Chart .PlotArea .Choice ,_bfe );_bfe .PieChart =_bb .NewCT_PieChart ();_bag :=PieChart {_cgf :_bfe .PieChart };_bag .InitializeDefaults ();
return _bag ;};

// AddBarChart adds a new bar chart to a chart.
func (_abf Chart )AddBarChart ()BarChart {_dea :=_bb .NewCT_PlotAreaChoice ();_abf ._dda .Chart .PlotArea .Choice =append (_abf ._dda .Chart .PlotArea .Choice ,_dea );_dea .BarChart =_bb .NewCT_BarChart ();_dea .BarChart .Grouping =_bb .NewCT_BarGrouping ();
_dea .BarChart .Grouping .ValAttr =_bb .ST_BarGroupingStandard ;_afg :=BarChart {_cc :_dea .BarChart };_afg .InitializeDefaults ();return _afg ;};func (_dcb Chart )AddSeriesAxis ()SeriesAxis {_cge :=_bb .NewCT_SerAx ();if _dcb ._dda .Chart .PlotArea .CChoice ==nil {_dcb ._dda .Chart .PlotArea .CChoice =_bb .NewCT_PlotAreaChoice1 ();
};_cge .AxId =_bb .NewCT_UnsignedInt ();_cge .AxId .ValAttr =0x7FFFFFFF&_g .Uint32 ();_dcb ._dda .Chart .PlotArea .CChoice .SerAx =append (_dcb ._dda .Chart .PlotArea .CChoice .SerAx ,_cge );_cge .Delete =_bb .NewCT_Boolean ();_cge .Delete .ValAttr =_be .Bool (false );
_eda :=MakeSeriesAxis (_cge );_eda .InitializeDefaults ();return _eda ;};func (_bbe BarChart )AddAxis (axis Axis ){_cgc :=_bb .NewCT_UnsignedInt ();_cgc .ValAttr =axis .AxisID ();_bbe ._cc .AxId =append (_bbe ._cc .AxId ,_cgc );};

// Values returns the value data source.
func (_egd BarChartSeries )Values ()NumberDataSource {if _egd ._ab .Val ==nil {_egd ._ab .Val =_bb .NewCT_NumDataSource ();};return MakeNumberDataSource (_egd ._ab .Val );};

// CategoryAxis returns the category data source.
func (_agf RadarChartSeries )CategoryAxis ()CategoryAxisDataSource {if _agf ._affb .Cat ==nil {_agf ._affb .Cat =_bb .NewCT_AxDataSource ();};return MakeAxisDataSource (_agf ._affb .Cat );};

// SetType sets the type the secone pie to either pie or bar
func (_cabd PieOfPieChart )SetType (t _bb .ST_OfPieType ){_cabd ._fbc .OfPieType .ValAttr =t };func (_ddagb ValueAxis )SetMajorTickMark (m _bb .ST_TickMark ){if m ==_bb .ST_TickMarkUnset {_ddagb ._adg .MajorTickMark =nil ;}else {_ddagb ._adg .MajorTickMark =_bb .NewCT_TickMark ();
_ddagb ._adg .MajorTickMark .ValAttr =m ;};};type SurfaceChartSeries struct{_gcgf *_bb .CT_SurfaceSer };

// AddAxis adds an axis to a Surface chart.
func (_ccdg SurfaceChart )AddAxis (axis Axis ){_fcbd :=_bb .NewCT_UnsignedInt ();_fcbd .ValAttr =axis .AxisID ();_ccdg ._bgbg .AxId =append (_ccdg ._bgbg .AxId ,_fcbd );};type GridLines struct{_dff *_bb .CT_ChartLines };

// CategoryAxisDataSource specifies the data for an axis.  It's commonly used with
// SetReference to set the axis data to a range of cells.
type CategoryAxisDataSource struct{_ed *_bb .CT_AxDataSource };func (_fa CategoryAxis )SetMajorTickMark (m _bb .ST_TickMark ){if m ==_bb .ST_TickMarkUnset {_fa ._cf .MajorTickMark =nil ;}else {_fa ._cf .MajorTickMark =_bb .NewCT_TickMark ();_fa ._cf .MajorTickMark .ValAttr =m ;
};};

// BubbleChartSeries is a series to be used on a Bubble chart.
type BubbleChartSeries struct{_gca *_bb .CT_BubbleSer };

// X returns the inner wrapped XML type.
func (_faa DateAxis )X ()*_bb .CT_DateAx {return _faa ._baa };

// X returns the inner wrapped XML type.
func (_bbbef SurfaceChartSeries )X ()*_bb .CT_SurfaceSer {return _bbbef ._gcgf };

// AddPieOfPieChart adds a new pie chart to a chart.
func (_bff Chart )AddPieOfPieChart ()PieOfPieChart {_ccf :=_bb .NewCT_PlotAreaChoice ();_bff ._dda .Chart .PlotArea .Choice =append (_bff ._dda .Chart .PlotArea .Choice ,_ccf );_ccf .OfPieChart =_bb .NewCT_OfPieChart ();_cbd :=PieOfPieChart {_fbc :_ccf .OfPieChart };
_cbd .InitializeDefaults ();return _cbd ;};func (_eegd DataLabels )SetPosition (p _bb .ST_DLblPos ){_eegd .ensureChoice ();_eegd ._ede .Choice .DLblPos =_bb .NewCT_DLblPos ();_eegd ._ede .Choice .DLblPos .ValAttr =p ;};

// InitializeDefaults the bar chart to its defaults
func (_c AreaChart )InitializeDefaults (){};

// AddTitle sets a new title on the chart.
func (_ggd Chart )AddTitle ()Title {_ggd ._dda .Chart .Title =_bb .NewCT_Title ();_ggd ._dda .Chart .Title .Overlay =_bb .NewCT_Boolean ();_ggd ._dda .Chart .Title .Overlay .ValAttr =_be .Bool (false );_ggd ._dda .Chart .AutoTitleDeleted =_bb .NewCT_Boolean ();
_ggd ._dda .Chart .AutoTitleDeleted .ValAttr =_be .Bool (false );_dcfe :=MakeTitle (_ggd ._dda .Chart .Title );_dcfe .InitializeDefaults ();return _dcfe ;};func (_bee CategoryAxis )AxisID ()uint32 {return _bee ._cf .AxId .ValAttr };func (_dbe SeriesAxis )InitializeDefaults (){};


// X returns the inner wrapped XML type.
func (_eb Area3DChart )X ()*_bb .CT_Area3DChart {return _eb ._eg };type CategoryAxis struct{_cf *_bb .CT_CatAx };

// X returns the inner wrapped XML type.
func (_eca AreaChart )X ()*_bb .CT_AreaChart {return _eca ._df };

// AddSeries adds a default series to a line chart.
func (_cad LineChart )AddSeries ()LineChartSeries {_gge :=_cad .nextColor (len (_cad ._fbb .Ser ));_aebd :=_bb .NewCT_LineSer ();_cad ._fbb .Ser =append (_cad ._fbb .Ser ,_aebd );_aebd .Idx .ValAttr =uint32 (len (_cad ._fbb .Ser )-1);_aebd .Order .ValAttr =uint32 (len (_cad ._fbb .Ser )-1);
_dfb :=LineChartSeries {_aebd };_dfb .InitializeDefaults ();_dfb .Properties ().LineProperties ().SetSolidFill (_gge );return _dfb ;};

// Labels returns the data label properties.
func (_ddag ScatterChartSeries )Labels ()DataLabels {if _ddag ._becd .DLbls ==nil {_ddag ._becd .DLbls =_bb .NewCT_DLbls ();};return MakeDataLabels (_ddag ._becd .DLbls );};

// Chart is a generic chart.
type Chart struct{_dda *_bb .ChartSpace };

// LineChartSeries is the data series for a line chart.
type LineChartSeries struct{_dfg *_bb .CT_LineSer };

// AddDateAxis adds a value axis to the chart.
func (_adcf Chart )AddDateAxis ()DateAxis {_ccg :=_bb .NewCT_DateAx ();if _adcf ._dda .Chart .PlotArea .CChoice ==nil {_adcf ._dda .Chart .PlotArea .CChoice =_bb .NewCT_PlotAreaChoice1 ();};_ccg .AxId =_bb .NewCT_UnsignedInt ();_ccg .AxId .ValAttr =0x7FFFFFFF&_g .Uint32 ();
_adcf ._dda .Chart .PlotArea .CChoice .DateAx =append (_adcf ._dda .Chart .PlotArea .CChoice .DateAx ,_ccg );_ccg .Delete =_bb .NewCT_Boolean ();_ccg .Delete .ValAttr =_be .Bool (false );_ccg .Scaling =_bb .NewCT_Scaling ();_ccg .Scaling .Orientation =_bb .NewCT_Orientation ();
_ccg .Scaling .Orientation .ValAttr =_bb .ST_OrientationMinMax ;_ccg .Choice =&_bb .EG_AxSharedChoice {};_ccg .Choice .Crosses =_bb .NewCT_Crosses ();_ccg .Choice .Crosses .ValAttr =_bb .ST_CrossesAutoZero ;_ffc :=DateAxis {_ccg };_ffc .MajorGridLines ().Properties ().LineProperties ().SetSolidFill (_bf .LightGray );
_ffc .SetMajorTickMark (_bb .ST_TickMarkOut );_ffc .SetMinorTickMark (_bb .ST_TickMarkIn );_ffc .SetTickLabelPosition (_bb .ST_TickLblPosNextTo );_ffc .Properties ().LineProperties ().SetSolidFill (_bf .Black );_ffc .SetPosition (_bb .ST_AxPosL );return _ffc ;
};

// SetDirection changes the direction of the bar chart (bar or column).
func (_ee BarChart )SetDirection (d _bb .ST_BarDir ){_ee ._cc .BarDir .ValAttr =d };

// Order returns the order of the series
func (_gba SurfaceChartSeries )Order ()uint32 {return _gba ._gcgf .Order .ValAttr };

// Bar3DChart is a 3D bar chart.
type Bar3DChart struct{chartBase ;_eggg *_bb .CT_Bar3DChart ;};

// SetDisplayBlanksAs controls how missing values are displayed.
func (_efe Chart )SetDisplayBlanksAs (v _bb .ST_DispBlanksAs ){_efe ._dda .Chart .DispBlanksAs =_bb .NewCT_DispBlanksAs ();_efe ._dda .Chart .DispBlanksAs .ValAttr =v ;};type nullAxis byte ;

// Properties returns the Bubble chart series shape properties.
func (_ae BubbleChartSeries )Properties ()_a .ShapeProperties {if _ae ._gca .SpPr ==nil {_ae ._gca .SpPr =_bfg .NewCT_ShapeProperties ();};return _a .MakeShapeProperties (_ae ._gca .SpPr );};

// InitializeDefaults the bar chart to its defaults
func (_ag Area3DChart )InitializeDefaults (){};func (_fbg ValueAxis )Properties ()_a .ShapeProperties {if _fbg ._adg .SpPr ==nil {_fbg ._adg .SpPr =_bfg .NewCT_ShapeProperties ();};return _a .MakeShapeProperties (_fbg ._adg .SpPr );};func (_egac ScatterChartSeries )CategoryAxis ()CategoryAxisDataSource {if _egac ._becd .XVal ==nil {_egac ._becd .XVal =_bb .NewCT_AxDataSource ();
};return MakeAxisDataSource (_egac ._becd .XVal );};func (_agaa ScatterChartSeries )Values ()NumberDataSource {if _agaa ._becd .YVal ==nil {_agaa ._becd .YVal =_bb .NewCT_NumDataSource ();};return MakeNumberDataSource (_agaa ._becd .YVal );};type DateAxis struct{_baa *_bb .CT_DateAx };
func (_gdab Marker )SetSymbol (s _bb .ST_MarkerStyle ){if s ==_bb .ST_MarkerStyleUnset {_gdab ._ebcb .Symbol =nil ;}else {_gdab ._ebcb .Symbol =_bb .NewCT_MarkerStyle ();_gdab ._ebcb .Symbol .ValAttr =s ;};};func (_bdff ValueAxis )SetMinorTickMark (m _bb .ST_TickMark ){if m ==_bb .ST_TickMarkUnset {_bdff ._adg .MinorTickMark =nil ;
}else {_bdff ._adg .MinorTickMark =_bb .NewCT_TickMark ();_bdff ._adg .MinorTickMark .ValAttr =m ;};};

// CategoryAxis returns the category data source.
func (_da BarChartSeries )CategoryAxis ()CategoryAxisDataSource {if _da ._ab .Cat ==nil {_da ._ab .Cat =_bb .NewCT_AxDataSource ();};return MakeAxisDataSource (_da ._ab .Cat );};func MakeDataLabels (x *_bb .CT_DLbls )DataLabels {return DataLabels {x }};
func (_ebee Title )SetText (s string ){if _ebee ._aadb .Tx ==nil {_ebee ._aadb .Tx =_bb .NewCT_Tx ();};if _ebee ._aadb .Tx .Choice .Rich ==nil {_ebee ._aadb .Tx .Choice .Rich =_bfg .NewCT_TextBody ();};var _fbd *_bfg .CT_TextParagraph ;if len (_ebee ._aadb .Tx .Choice .Rich .P )==0{_fbd =_bfg .NewCT_TextParagraph ();
_ebee ._aadb .Tx .Choice .Rich .P =[]*_bfg .CT_TextParagraph {_fbd };}else {_fbd =_ebee ._aadb .Tx .Choice .Rich .P [0];};var _baf *_bfg .EG_TextRun ;if len (_fbd .EG_TextRun )==0{_baf =_bfg .NewEG_TextRun ();_fbd .EG_TextRun =[]*_bfg .EG_TextRun {_baf };
}else {_baf =_fbd .EG_TextRun [0];};if _baf .R ==nil {_baf .R =_bfg .NewCT_RegularTextRun ();};_baf .R .T =s ;};

// AddDoughnutChart adds a new doughnut (pie with a hole in the center) chart to a chart.
func (_cabf Chart )AddDoughnutChart ()DoughnutChart {_afc :=_bb .NewCT_PlotAreaChoice ();_cabf ._dda .Chart .PlotArea .Choice =append (_cabf ._dda .Chart .PlotArea .Choice ,_afc );_afc .DoughnutChart =_bb .NewCT_DoughnutChart ();_ebc :=DoughnutChart {_cec :_afc .DoughnutChart };
_ebc .InitializeDefaults ();return _ebc ;};

// CategoryAxis returns the category data source.
func (_efb BubbleChartSeries )CategoryAxis ()CategoryAxisDataSource {if _efb ._gca .XVal ==nil {_efb ._gca .XVal =_bb .NewCT_AxDataSource ();};return MakeAxisDataSource (_efb ._gca .XVal );};type SeriesAxis struct{_fbfb *_bb .CT_SerAx };func MakeValueAxis (x *_bb .CT_ValAx )ValueAxis {return ValueAxis {x }};
func (_gcg AreaChart )AddAxis (axis Axis ){_bg :=_bb .NewCT_UnsignedInt ();_bg .ValAttr =axis .AxisID ();_gcg ._df .AxId =append (_gcg ._df .AxId ,_bg );};

// AddPie3DChart adds a new pie chart to a chart.
func (_ge Chart )AddPie3DChart ()Pie3DChart {_ceaa (_ge ._dda .Chart );_gde :=_bb .NewCT_PlotAreaChoice ();_ge ._dda .Chart .PlotArea .Choice =append (_ge ._dda .Chart .PlotArea .Choice ,_gde );_gde .Pie3DChart =_bb .NewCT_Pie3DChart ();_fde :=Pie3DChart {_ecae :_gde .Pie3DChart };
_fde .InitializeDefaults ();return _fde ;};

// RemoveLegend removes the legend if the chart has one.
func (_gdc Chart )RemoveLegend (){_gdc ._dda .Chart .Legend =nil };func _ceaa (_cgca *_bb .CT_Chart ){_cgca .View3D =_bb .NewCT_View3D ();_cgca .View3D .RotX =_bb .NewCT_RotX ();_cgca .View3D .RotX .ValAttr =_be .Int8 (15);_cgca .View3D .RotY =_bb .NewCT_RotY ();
_cgca .View3D .RotY .ValAttr =_be .Uint16 (20);_cgca .View3D .RAngAx =_bb .NewCT_Boolean ();_cgca .View3D .RAngAx .ValAttr =_be .Bool (false );_cgca .Floor =_bb .NewCT_Surface ();_cgca .Floor .Thickness =_bb .NewCT_Thickness ();_cgca .Floor .Thickness .ValAttr .Uint32 =_be .Uint32 (0);
_cgca .SideWall =_bb .NewCT_Surface ();_cgca .SideWall .Thickness =_bb .NewCT_Thickness ();_cgca .SideWall .Thickness .ValAttr .Uint32 =_be .Uint32 (0);_cgca .BackWall =_bb .NewCT_Surface ();_cgca .BackWall .Thickness =_bb .NewCT_Thickness ();_cgca .BackWall .Thickness .ValAttr .Uint32 =_be .Uint32 (0);
};type Marker struct{_ebcb *_bb .CT_Marker };func (_ded CategoryAxis )Properties ()_a .ShapeProperties {if _ded ._cf .SpPr ==nil {_ded ._cf .SpPr =_bfg .NewCT_ShapeProperties ();};return _a .MakeShapeProperties (_ded ._cf .SpPr );};func (_dgf StockChart )AddAxis (axis Axis ){_gce :=_bb .NewCT_UnsignedInt ();
_gce .ValAttr =axis .AxisID ();_dgf ._ccd .AxId =append (_dgf ._ccd .AxId ,_gce );};func (_bbg LineChartSeries )Values ()NumberDataSource {if _bbg ._dfg .Val ==nil {_bbg ._dfg .Val =_bb .NewCT_NumDataSource ();};return MakeNumberDataSource (_bbg ._dfg .Val );
};func (_dca Surface3DChart )InitializeDefaults (){_dca ._ggaf .Wireframe =_bb .NewCT_Boolean ();_dca ._ggaf .Wireframe .ValAttr =_be .Bool (false );_dca ._ggaf .BandFmts =_bb .NewCT_BandFmts ();for _dee :=0;_dee < 15;_dee ++{_aegc :=_bb .NewCT_BandFmt ();
_aegc .Idx .ValAttr =uint32 (_dee );_aegc .SpPr =_bfg .NewCT_ShapeProperties ();_ddd :=_a .MakeShapeProperties (_aegc .SpPr );_ddd .SetSolidFill (_dca .nextColor (_dee ));_dca ._ggaf .BandFmts .BandFmt =append (_dca ._ggaf .BandFmts .BandFmt ,_aegc );};
};

// StockChart is a 2D Stock chart.
type StockChart struct{chartBase ;_ccd *_bb .CT_StockChart ;};func (_fbbd ScatterChartSeries )InitializeDefaults (){_fbbd .Properties ().LineProperties ().SetNoFill ();_fbbd .Marker ().SetSymbol (_bb .ST_MarkerStyleAuto );_fbbd .Labels ().SetShowLegendKey (false );
_fbbd .Labels ().SetShowValue (true );_fbbd .Labels ().SetShowPercent (false );_fbbd .Labels ().SetShowCategoryName (false );_fbbd .Labels ().SetShowSeriesName (false );_fbbd .Labels ().SetShowLeaderLines (false );};

// MakeAxisDataSource constructs an AxisDataSource wrapper.
func MakeAxisDataSource (x *_bb .CT_AxDataSource )CategoryAxisDataSource {return CategoryAxisDataSource {x };};

// Properties returns the line chart series shape properties.
func (_aad LineChartSeries )Properties ()_a .ShapeProperties {if _aad ._dfg .SpPr ==nil {_aad ._dfg .SpPr =_bfg .NewCT_ShapeProperties ();};return _a .MakeShapeProperties (_aad ._dfg .SpPr );};func (_fdfg GridLines )Properties ()_a .ShapeProperties {if _fdfg ._dff .SpPr ==nil {_fdfg ._dff .SpPr =_bfg .NewCT_ShapeProperties ();
};return _a .MakeShapeProperties (_fdfg ._dff .SpPr );};type DataLabels struct{_ede *_bb .CT_DLbls };func (_bfdc Title )InitializeDefaults (){_bfdc .SetText ("\u0054\u0069\u0074l\u0065");_bfdc .RunProperties ().SetSize (16*_ea .Point );_bfdc .RunProperties ().SetSolidFill (_bf .Black );
_bfdc .RunProperties ().SetFont ("\u0043\u0061\u006c\u0069\u0062\u0020\u0072\u0069");_bfdc .RunProperties ().SetBold (false );};func (_dd CategoryAxis )SetPosition (p _bb .ST_AxPos ){_dd ._cf .AxPos =_bb .NewCT_AxPos ();_dd ._cf .AxPos .ValAttr =p ;};

// Properties returns the bar chart series shape properties.
func (_fcc BarChartSeries )Properties ()_a .ShapeProperties {if _fcc ._ab .SpPr ==nil {_fcc ._ab .SpPr =_bfg .NewCT_ShapeProperties ();};return _a .MakeShapeProperties (_fcc ._ab .SpPr );};

// PieChart is a Pie chart.
type PieChart struct{chartBase ;_cgf *_bb .CT_PieChart ;};

// SetText sets the series text
func (_cda LineChartSeries )SetText (s string ){_cda ._dfg .Tx =_bb .NewCT_SerTx ();_cda ._dfg .Tx .Choice .V =&s ;};

// AddBubbleChart adds a new bubble chart.
func (_ffd Chart )AddBubbleChart ()BubbleChart {_fdd :=_bb .NewCT_PlotAreaChoice ();_ffd ._dda .Chart .PlotArea .Choice =append (_ffd ._dda .Chart .PlotArea .Choice ,_fdd );_fdd .BubbleChart =_bb .NewCT_BubbleChart ();_abe :=BubbleChart {_ebg :_fdd .BubbleChart };
_abe .InitializeDefaults ();return _abe ;};

// Axis is the interface implemented by different axes when assigning to a
// chart.
type Axis interface{AxisID ()uint32 ;};func MakeTitle (x *_bb .CT_Title )Title {return Title {x }};

// SetText sets the series text.
func (_bdf PieChartSeries )SetText (s string ){_bdf ._aga .Tx =_bb .NewCT_SerTx ();_bdf ._aga .Tx .Choice .V =&s ;};

// AddAxis adds an axis to a Surface chart.
func (_egaa Surface3DChart )AddAxis (axis Axis ){_bgb :=_bb .NewCT_UnsignedInt ();_bgb .ValAttr =axis .AxisID ();_egaa ._ggaf .AxId =append (_egaa ._ggaf .AxId ,_bgb );};func (_gcfbe Legend )Properties ()_a .ShapeProperties {if _gcfbe ._cabfa .SpPr ==nil {_gcfbe ._cabfa .SpPr =_bfg .NewCT_ShapeProperties ();
};return _a .MakeShapeProperties (_gcfbe ._cabfa .SpPr );};func (_gec DateAxis )SetMinorTickMark (m _bb .ST_TickMark ){if m ==_bb .ST_TickMarkUnset {_gec ._baa .MinorTickMark =nil ;}else {_gec ._baa .MinorTickMark =_bb .NewCT_TickMark ();_gec ._baa .MinorTickMark .ValAttr =m ;
};};

// InitializeDefaults the Stock chart to its defaults
func (_dga StockChart )InitializeDefaults (){_dga ._ccd .HiLowLines =_bb .NewCT_ChartLines ();_dga ._ccd .UpDownBars =_bb .NewCT_UpDownBars ();_dga ._ccd .UpDownBars .GapWidth =_bb .NewCT_GapAmount ();_dga ._ccd .UpDownBars .GapWidth .ValAttr =&_bb .ST_GapAmount {};
_dga ._ccd .UpDownBars .GapWidth .ValAttr .ST_GapAmountUShort =_be .Uint16 (150);_dga ._ccd .UpDownBars .UpBars =_bb .NewCT_UpDownBar ();_dga ._ccd .UpDownBars .DownBars =_bb .NewCT_UpDownBar ();};func (_bbbe DataLabels )ensureChoice (){if _bbbe ._ede .Choice ==nil {_bbbe ._ede .Choice =_bb .NewCT_DLblsChoice ();
};};func (_bfbc Marker )SetSize (sz uint8 ){_bfbc ._ebcb .Size =_bb .NewCT_MarkerSize ();_bfbc ._ebcb .Size .ValAttr =&sz ;};func (_gcd SurfaceChartSeries )InitializeDefaults (){_gcd .Properties ().LineProperties ().SetWidth (1*_ea .Point );_gcd .Properties ().LineProperties ().SetSolidFill (_bf .Black );
_gcd .Properties ().LineProperties ().SetJoin (_a .LineJoinRound );};func (_gdcd SurfaceChart )InitializeDefaults (){_gdcd ._bgbg .Wireframe =_bb .NewCT_Boolean ();_gdcd ._bgbg .Wireframe .ValAttr =_be .Bool (false );_gdcd ._bgbg .BandFmts =_bb .NewCT_BandFmts ();
for _gafe :=0;_gafe < 15;_gafe ++{_fdg :=_bb .NewCT_BandFmt ();_fdg .Idx .ValAttr =uint32 (_gafe );_fdg .SpPr =_bfg .NewCT_ShapeProperties ();_aaef :=_a .MakeShapeProperties (_fdg .SpPr );_aaef .SetSolidFill (_gdcd .nextColor (_gafe ));_gdcd ._bgbg .BandFmts .BandFmt =append (_gdcd ._bgbg .BandFmts .BandFmt ,_fdg );
};};

// Index returns the index of the series
func (_egef ScatterChartSeries )Index ()uint32 {return _egef ._becd .Idx .ValAttr };

// InitializeDefaults initializes an area series to the default values.
func (_ad AreaChartSeries )InitializeDefaults (){};

// Values returns the value data source.
func (_egde RadarChartSeries )Values ()NumberDataSource {if _egde ._affb .Val ==nil {_egde ._affb .Val =_bb .NewCT_NumDataSource ();};return MakeNumberDataSource (_egde ._affb .Val );};

// Properties returns the line chart series shape properties.
func (_gcb ScatterChartSeries )Properties ()_a .ShapeProperties {if _gcb ._becd .SpPr ==nil {_gcb ._becd .SpPr =_bfg .NewCT_ShapeProperties ();};return _a .MakeShapeProperties (_gcb ._becd .SpPr );};type Title struct{_aadb *_bb .CT_Title };

// X returns the inner wrapped XML type.
func (_fcec PieOfPieChart )X ()*_bb .CT_OfPieChart {return _fcec ._fbc };

// X returns the inner wrapped XML type.
func (_cebcf ScatterChart )X ()*_bb .CT_ScatterChart {return _cebcf ._ege };

// Area3DChart is an area chart that has a shaded area underneath a curve.
type Area3DChart struct{chartBase ;_eg *_bb .CT_Area3DChart ;};

// X returns the inner wrapped XML type.
func (_gcaae Marker )X ()*_bb .CT_Marker {return _gcaae ._ebcb };

// Order returns the order of the series
func (_dad LineChartSeries )Order ()uint32 {return _dad ._dfg .Order .ValAttr };func (_faeg NumberDataSource )ensureChoice (){if _faeg ._gacc .Choice ==nil {_faeg ._gacc .Choice =_bb .NewCT_NumDataSourceChoice ();};};

// AddCategoryAxis adds a category axis.
func (_cgg Chart )AddCategoryAxis ()CategoryAxis {_cbb :=_bb .NewCT_CatAx ();if _cgg ._dda .Chart .PlotArea .CChoice ==nil {_cgg ._dda .Chart .PlotArea .CChoice =_bb .NewCT_PlotAreaChoice1 ();};_cbb .AxId =_bb .NewCT_UnsignedInt ();_cbb .AxId .ValAttr =0x7FFFFFFF&_g .Uint32 ();
_cgg ._dda .Chart .PlotArea .CChoice .CatAx =append (_cgg ._dda .Chart .PlotArea .CChoice .CatAx ,_cbb );_cbb .Auto =_bb .NewCT_Boolean ();_cbb .Auto .ValAttr =_be .Bool (true );_cbb .Delete =_bb .NewCT_Boolean ();_cbb .Delete .ValAttr =_be .Bool (false );
_gab :=MakeCategoryAxis (_cbb );_gab .InitializeDefaults ();return _gab ;};

// SetNumberReference is used to set the source data to a range of cells containing
// numbers.
func (_dbc CategoryAxisDataSource )SetNumberReference (s string ){_dbc ._ed .Choice =_bb .NewCT_AxDataSourceChoice ();_dbc ._ed .Choice .NumRef =_bb .NewCT_NumRef ();_dbc ._ed .Choice .NumRef .F =s ;};func (_afa DateAxis )SetPosition (p _bb .ST_AxPos ){_afa ._baa .AxPos =_bb .NewCT_AxPos ();
_afa ._baa .AxPos .ValAttr =p ;};

// SetOrder sets the order of the series
func (_edc SurfaceChartSeries )SetOrder (idx uint32 ){_edc ._gcgf .Order .ValAttr =idx };func (_gdbd Title )RunProperties ()_a .RunProperties {if _gdbd ._aadb .Tx ==nil {_gdbd .SetText ("");};if _gdbd ._aadb .Tx .Choice .Rich .P [0].EG_TextRun [0].R .RPr ==nil {_gdbd ._aadb .Tx .Choice .Rich .P [0].EG_TextRun [0].R .RPr =_bfg .NewCT_TextCharacterProperties ();
};return _a .MakeRunProperties (_gdbd ._aadb .Tx .Choice .Rich .P [0].EG_TextRun [0].R .RPr );};

// Surface3DChart is a 3D view of a surface chart.
type Surface3DChart struct{chartBase ;_ggaf *_bb .CT_Surface3DChart ;};

// Values returns the bubble size data source.
func (_bge BubbleChartSeries )BubbleSizes ()NumberDataSource {if _bge ._gca .BubbleSize ==nil {_bge ._gca .BubbleSize =_bb .NewCT_NumDataSource ();};return MakeNumberDataSource (_bge ._gca .BubbleSize );};func (_gdcf LineChartSeries )CategoryAxis ()CategoryAxisDataSource {if _gdcf ._dfg .Cat ==nil {_gdcf ._dfg .Cat =_bb .NewCT_AxDataSource ();
};return MakeAxisDataSource (_gdcf ._dfg .Cat );};func (_bged CategoryAxis )SetCrosses (axis Axis ){_bged ._cf .Choice =_bb .NewEG_AxSharedChoice ();_bged ._cf .Choice .Crosses =_bb .NewCT_Crosses ();_bged ._cf .Choice .Crosses .ValAttr =_bb .ST_CrossesAutoZero ;
_bged ._cf .CrossAx .ValAttr =axis .AxisID ();};

// InitializeDefaults initializes a bar chart series to the default values.
func (_db BarChartSeries )InitializeDefaults (){};

// DoughnutChart is a Doughnut chart.
type DoughnutChart struct{chartBase ;_cec *_bb .CT_DoughnutChart ;};func (_agec Legend )SetPosition (p _bb .ST_LegendPos ){if p ==_bb .ST_LegendPosUnset {_agec ._cabfa .LegendPos =nil ;}else {_agec ._cabfa .LegendPos =_bb .NewCT_LegendPos ();_agec ._cabfa .LegendPos .ValAttr =p ;
};};func (_aaaa SurfaceChartSeries )CategoryAxis ()CategoryAxisDataSource {if _aaaa ._gcgf .Cat ==nil {_aaaa ._gcgf .Cat =_bb .NewCT_AxDataSource ();};return MakeAxisDataSource (_aaaa ._gcgf .Cat );};

// RadarChart is an Radar chart that has a shaded Radar underneath a curve.
type RadarChart struct{chartBase ;_eace *_bb .CT_RadarChart ;};

// Marker returns the marker properties.
func (_gbed ScatterChartSeries )Marker ()Marker {if _gbed ._becd .Marker ==nil {_gbed ._becd .Marker =_bb .NewCT_Marker ();};return MakeMarker (_gbed ._becd .Marker );};

// SetText sets the series text
func (_egggd ScatterChartSeries )SetText (s string ){_egggd ._becd .Tx =_bb .NewCT_SerTx ();_egggd ._becd .Tx .Choice .V =&s ;};

// Properties returns the line chart series shape properties.
func (_cdg SurfaceChartSeries )Properties ()_a .ShapeProperties {if _cdg ._gcgf .SpPr ==nil {_cdg ._gcgf .SpPr =_bfg .NewCT_ShapeProperties ();};return _a .MakeShapeProperties (_cdg ._gcgf .SpPr );};

// X returns the inner wrapped XML type.
func (_fce Line3DChart )X ()*_bb .CT_Line3DChart {return _fce ._gdb };

// X returns the inner wrapped XML type.
func (_gdcg LineChart )X ()*_bb .CT_LineChart {return _gdcg ._fbb };

// PieOfPieChart is a Pie chart with an extra Pie chart.
type PieOfPieChart struct{chartBase ;_fbc *_bb .CT_OfPieChart ;};func MakeSeriesAxis (x *_bb .CT_SerAx )SeriesAxis {return SeriesAxis {x }};