//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

package chart ;import (_gg "fmt";_c "github.com/unidoc/unioffice";_e "github.com/unidoc/unioffice/color";_d "github.com/unidoc/unioffice/drawing";_b "github.com/unidoc/unioffice/measurement";_cb "github.com/unidoc/unioffice/schema/soo/dml";_gb "github.com/unidoc/unioffice/schema/soo/dml/chart";_ce "math/rand";);

// X returns the inner wrapped XML type.
func (_gdf SeriesAxis )X ()*_gb .CT_SerAx {return _gdf ._cfgb };func (_ffb DataLabels )SetShowSeriesName (b bool ){_ffb .ensureChoice ();_ffb ._bfd .Choice .ShowSerName =_gb .NewCT_Boolean ();_ffb ._bfd .Choice .ShowSerName .ValAttr =_c .Bool (b );};

// AddSeries adds a default series to an Doughnut chart.
func (_ddg DoughnutChart )AddSeries ()PieChartSeries {_befe :=_gb .NewCT_PieSer ();_ddg ._dec .Ser =append (_ddg ._dec .Ser ,_befe );_befe .Idx .ValAttr =uint32 (len (_ddg ._dec .Ser )-1);_befe .Order .ValAttr =uint32 (len (_ddg ._dec .Ser )-1);_gag :=PieChartSeries {_befe };_gag .InitializeDefaults ();return _gag ;};

// SetHoleSize controls the hole size in the pie chart and is measured in percent.
func (_fbbg DoughnutChart )SetHoleSize (pct uint8 ){if _fbbg ._dec .HoleSize ==nil {_fbbg ._dec .HoleSize =_gb .NewCT_HoleSize ();};if _fbbg ._dec .HoleSize .ValAttr ==nil {_fbbg ._dec .HoleSize .ValAttr =&_gb .ST_HoleSize {};};_fbbg ._dec .HoleSize .ValAttr .ST_HoleSizeUByte =&pct ;};func (_bcga chartBase )nextColor (_ecfg int )_e .Color {return _bgaa [_ecfg %len (_bgaa )]};func (_bgaaf Legend )Properties ()_d .ShapeProperties {if _bgaaf ._bgae .SpPr ==nil {_bgaaf ._bgae .SpPr =_cb .NewCT_ShapeProperties ();};return _d .MakeShapeProperties (_bgaaf ._bgae .SpPr );};

// InitializeDefaults the bar chart to its defaults
func (_fgd DoughnutChart )InitializeDefaults (){_fgd ._dec .VaryColors =_gb .NewCT_Boolean ();_fgd ._dec .VaryColors .ValAttr =_c .Bool (true );_fgd ._dec .HoleSize =_gb .NewCT_HoleSize ();_fgd ._dec .HoleSize .ValAttr =&_gb .ST_HoleSize {};_fgd ._dec .HoleSize .ValAttr .ST_HoleSizeUByte =_c .Uint8 (50);};

// StockChart is a 2D Stock chart.
type StockChart struct{chartBase ;_edf *_gb .CT_StockChart ;};

// SetNumberReference is used to set the source data to a range of cells containing
// numbers.
func (_cee CategoryAxisDataSource )SetNumberReference (s string ){_cee ._ebd .Choice =_gb .NewCT_AxDataSourceChoice ();_cee ._ebd .Choice .NumRef =_gb .NewCT_NumRef ();_cee ._ebd .Choice .NumRef .F =s ;};

// Properties returns the line chart series shape properties.
func (_edae ScatterChartSeries )Properties ()_d .ShapeProperties {if _edae ._abg .SpPr ==nil {_edae ._abg .SpPr =_cb .NewCT_ShapeProperties ();};return _d .MakeShapeProperties (_edae ._abg .SpPr );};

// X returns the inner wrapped XML type.
func (_bdab PieChartSeries )X ()*_gb .CT_PieSer {return _bdab ._gbg };

// X returns the inner wrapped XML type.
func (_dfb ScatterChart )X ()*_gb .CT_ScatterChart {return _dfb ._aea };

// AddSeries adds a default series to an area chart.
func (_ee AreaChart )AddSeries ()AreaChartSeries {_cda :=_ee .nextColor (len (_ee ._eb .Ser ));_fd :=_gb .NewCT_AreaSer ();_ee ._eb .Ser =append (_ee ._eb .Ser ,_fd );_fd .Idx .ValAttr =uint32 (len (_ee ._eb .Ser )-1);_fd .Order .ValAttr =uint32 (len (_ee ._eb .Ser )-1);_fdf :=AreaChartSeries {_fd };_fdf .InitializeDefaults ();_fdf .Properties ().SetSolidFill (_cda );return _fdf ;};func (_bdc DataLabels )ensureChoice (){if _bdc ._bfd .Choice ==nil {_bdc ._bfd .Choice =_gb .NewCT_DLblsChoice ();};};

// SetDirection changes the direction of the bar chart (bar or column).
func (_af BarChart )SetDirection (d _gb .ST_BarDir ){_af ._ggc .BarDir .ValAttr =d };func (_aae ScatterChart )InitializeDefaults (){_aae ._aea .ScatterStyle .ValAttr =_gb .ST_ScatterStyleMarker ;};

// AddSeries adds a default series to an area chart.
func (_bd Area3DChart )AddSeries ()AreaChartSeries {_bb :=_bd .nextColor (len (_bd ._gba .Ser ));_bbd :=_gb .NewCT_AreaSer ();_bd ._gba .Ser =append (_bd ._gba .Ser ,_bbd );_bbd .Idx .ValAttr =uint32 (len (_bd ._gba .Ser )-1);_bbd .Order .ValAttr =uint32 (len (_bd ._gba .Ser )-1);_dd :=AreaChartSeries {_bbd };_dd .InitializeDefaults ();_dd .Properties ().SetSolidFill (_bb );return _dd ;};func (_cfab DataLabels )SetShowLegendKey (b bool ){_cfab .ensureChoice ();_cfab ._bfd .Choice .ShowLegendKey =_gb .NewCT_Boolean ();_cfab ._bfd .Choice .ShowLegendKey .ValAttr =_c .Bool (b );};func (_cgg Title )RunProperties ()_d .RunProperties {if _cgg ._gded .Tx ==nil {_cgg .SetText ("");};if _cgg ._gded .Tx .Choice .Rich .P [0].EG_TextRun [0].R .RPr ==nil {_cgg ._gded .Tx .Choice .Rich .P [0].EG_TextRun [0].R .RPr =_cb .NewCT_TextCharacterProperties ();};return _d .MakeRunProperties (_cgg ._gded .Tx .Choice .Rich .P [0].EG_TextRun [0].R .RPr );};

// InitializeDefaults the bar chart to its defaults
func (_ed Bar3DChart )InitializeDefaults (){_ed .SetDirection (_gb .ST_BarDirCol )};func (_dgc ValueAxis )SetMinorTickMark (m _gb .ST_TickMark ){if m ==_gb .ST_TickMarkUnset {_dgc ._dffd .MinorTickMark =nil ;}else {_dgc ._dffd .MinorTickMark =_gb .NewCT_TickMark ();_dgc ._dffd .MinorTickMark .ValAttr =m ;};};func (_eda Marker )Properties ()_d .ShapeProperties {if _eda ._dff .SpPr ==nil {_eda ._dff .SpPr =_cb .NewCT_ShapeProperties ();};return _d .MakeShapeProperties (_eda ._dff .SpPr );};

// X returns the inner wrapped XML type.
func (_bbc Surface3DChart )X ()*_gb .CT_Surface3DChart {return _bbc ._dgd };

// SetValues is used to set the source data to a set of values.
func (_ecf CategoryAxisDataSource )SetValues (v []string ){_ecf ._ebd .Choice =_gb .NewCT_AxDataSourceChoice ();_ecf ._ebd .Choice .StrLit =_gb .NewCT_StrData ();_ecf ._ebd .Choice .StrLit .PtCount =_gb .NewCT_UnsignedInt ();_ecf ._ebd .Choice .StrLit .PtCount .ValAttr =uint32 (len (v ));for _fgf ,_eea :=range v {_ecf ._ebd .Choice .StrLit .Pt =append (_ecf ._ebd .Choice .StrLit .Pt ,&_gb .CT_StrVal {IdxAttr :uint32 (_fgf ),V :_eea });};};

// BubbleChart is a 2D Bubble chart.
type BubbleChart struct{chartBase ;_bbg *_gb .CT_BubbleChart ;};

// Properties returns the Bubble chart series shape properties.
func (_gfb BubbleChartSeries )Properties ()_d .ShapeProperties {if _gfb ._afe .SpPr ==nil {_gfb ._afe .SpPr =_cb .NewCT_ShapeProperties ();};return _d .MakeShapeProperties (_gfb ._afe .SpPr );};

// SetExplosion sets the value that the segements of the pie are 'exploded' by
func (_dfe PieChartSeries )SetExplosion (v uint32 ){_dfe ._gbg .Explosion =_gb .NewCT_UnsignedInt ();_dfe ._gbg .Explosion .ValAttr =v ;};

// Labels returns the data label properties.
func (_eac LineChartSeries )Labels ()DataLabels {if _eac ._feaa .DLbls ==nil {_eac ._feaa .DLbls =_gb .NewCT_DLbls ();};return MakeDataLabels (_eac ._feaa .DLbls );};

// SetText sets the series text
func (_decb LineChartSeries )SetText (s string ){_decb ._feaa .Tx =_gb .NewCT_SerTx ();_decb ._feaa .Tx .Choice .V =&s ;};

// BarChart is a 2D bar chart.
type BarChart struct{chartBase ;_ggc *_gb .CT_BarChart ;};

// SetIndex sets the index of the series
func (_gga LineChartSeries )SetIndex (idx uint32 ){_gga ._feaa .Idx .ValAttr =idx };

// InitializeDefaults the bar chart to its defaults
func (_a Area3DChart )InitializeDefaults (){};

// AddSurface3DChart adds a new 3D surface chart to a chart.
func (_cbe Chart )AddSurface3DChart ()Surface3DChart {_bdf :=_gb .NewCT_PlotAreaChoice ();_cbe ._daf .Chart .PlotArea .Choice =append (_cbe ._daf .Chart .PlotArea .Choice ,_bdf );_bdf .Surface3DChart =_gb .NewCT_Surface3DChart ();_ad (_cbe ._daf .Chart );_bee :=Surface3DChart {_dgd :_bdf .Surface3DChart };_bee .InitializeDefaults ();return _bee ;};func (_ea CategoryAxis )SetCrosses (axis Axis ){_ea ._ba .Choice =_gb .NewEG_AxSharedChoice ();_ea ._ba .Choice .Crosses =_gb .NewCT_Crosses ();_ea ._ba .Choice .Crosses .ValAttr =_gb .ST_CrossesAutoZero ;_ea ._ba .CrossAx .ValAttr =axis .AxisID ();};func (_fbf DataLabels )SetShowPercent (b bool ){_fbf .ensureChoice ();_fbf ._bfd .Choice .ShowPercent =_gb .NewCT_Boolean ();_fbf ._bfd .Choice .ShowPercent .ValAttr =_c .Bool (b );};func (_gbd CategoryAxis )InitializeDefaults (){_gbd .SetPosition (_gb .ST_AxPosB );_gbd .SetMajorTickMark (_gb .ST_TickMarkOut );_gbd .SetMinorTickMark (_gb .ST_TickMarkIn );_gbd .SetTickLabelPosition (_gb .ST_TickLblPosNextTo );_gbd .MajorGridLines ().Properties ().LineProperties ().SetSolidFill (_e .LightGray );_gbd .Properties ().LineProperties ().SetSolidFill (_e .Black );};

// CategoryAxis returns the category data source.
func (_cea AreaChartSeries )CategoryAxis ()CategoryAxisDataSource {if _cea ._cf .Cat ==nil {_cea ._cf .Cat =_gb .NewCT_AxDataSource ();};return MakeAxisDataSource (_cea ._cf .Cat );};

// AddSeries adds a default series to a Scatter chart.
func (_fded ScatterChart )AddSeries ()ScatterChartSeries {_acec :=_fded .nextColor (len (_fded ._aea .Ser ));_abe :=_gb .NewCT_ScatterSer ();_fded ._aea .Ser =append (_fded ._aea .Ser ,_abe );_abe .Idx .ValAttr =uint32 (len (_fded ._aea .Ser )-1);_abe .Order .ValAttr =uint32 (len (_fded ._aea .Ser )-1);_eafa :=ScatterChartSeries {_abe };_eafa .InitializeDefaults ();_eafa .Marker ().Properties ().LineProperties ().SetSolidFill (_acec );_eafa .Marker ().Properties ().SetSolidFill (_acec );return _eafa ;};type DataLabels struct{_bfd *_gb .CT_DLbls };

// X returns the inner wrapped XML type.
func (_fddb BubbleChart )X ()*_gb .CT_BubbleChart {return _fddb ._bbg };func (_edd DateAxis )SetPosition (p _gb .ST_AxPos ){_edd ._agd .AxPos =_gb .NewCT_AxPos ();_edd ._agd .AxPos .ValAttr =p ;};

// SetLabelReference is used to set the source data to a range of cells
// containing strings.
func (_gcaf CategoryAxisDataSource )SetLabelReference (s string ){_gcaf ._ebd .Choice =_gb .NewCT_AxDataSourceChoice ();_gcaf ._ebd .Choice .StrRef =_gb .NewCT_StrRef ();_gcaf ._ebd .Choice .StrRef .F =s ;};

// LineChartSeries is the data series for a line chart.
type LineChartSeries struct{_feaa *_gb .CT_LineSer };func (_egc GridLines )Properties ()_d .ShapeProperties {if _egc ._afcd .SpPr ==nil {_egc ._afcd .SpPr =_cb .NewCT_ShapeProperties ();};return _d .MakeShapeProperties (_egc ._afcd .SpPr );};

// SetText sets the series text.
func (_cbg BubbleChartSeries )SetText (s string ){_cbg ._afe .Tx =_gb .NewCT_SerTx ();_cbg ._afe .Tx .Choice .V =&s ;};func (_beg Marker )SetSymbol (s _gb .ST_MarkerStyle ){if s ==_gb .ST_MarkerStyleUnset {_beg ._dff .Symbol =nil ;}else {_beg ._dff .Symbol =_gb .NewCT_MarkerStyle ();_beg ._dff .Symbol .ValAttr =s ;};};func MakeDataLabels (x *_gb .CT_DLbls )DataLabels {return DataLabels {x }};var _bgaa =[]_e .Color {_e .RGB (0x33,0x66,0xcc),_e .RGB (0xDC,0x39,0x12),_e .RGB (0xFF,0x99,0x00),_e .RGB (0x10,0x96,0x18),_e .RGB (0x99,0x00,0x99),_e .RGB (0x3B,0x3E,0xAC),_e .RGB (0x00,0x99,0xC6),_e .RGB (0xDD,0x44,0x77),_e .RGB (0x66,0xAA,0x00),_e .RGB (0xB8,0x2E,0x2E),_e .RGB (0x31,0x63,0x95),_e .RGB (0x99,0x44,0x99),_e .RGB (0x22,0xAA,0x99),_e .RGB (0xAA,0xAA,0x11),_e .RGB (0x66,0x33,0xCC),_e .RGB (0xE6,0x73,0x00),_e .RGB (0x8B,0x07,0x07),_e .RGB (0x32,0x92,0x62),_e .RGB (0x55,0x74,0xA6),_e .RGB (0x3B,0x3E,0xAC)};

// InitializeDefaults initializes a bar chart series to the default values.
func (_gbc BarChartSeries )InitializeDefaults (){};

// SetText sets the series text.
func (_bec AreaChartSeries )SetText (s string ){_bec ._cf .Tx =_gb .NewCT_SerTx ();_bec ._cf .Tx .Choice .V =&s ;};

// AddAreaChart adds a new area chart to a chart.
func (_bfa Chart )AddAreaChart ()AreaChart {_cc :=_gb .NewCT_PlotAreaChoice ();_bfa ._daf .Chart .PlotArea .Choice =append (_bfa ._daf .Chart .PlotArea .Choice ,_cc );_cc .AreaChart =_gb .NewCT_AreaChart ();_baf :=AreaChart {_eb :_cc .AreaChart };_baf .InitializeDefaults ();return _baf ;};

// Index returns the index of the series
func (_agce LineChartSeries )Index ()uint32 {return _agce ._feaa .Idx .ValAttr };type Marker struct{_dff *_gb .CT_Marker };

// X returns the inner wrapped XML type.
func (_ebc AreaChart )X ()*_gb .CT_AreaChart {return _ebc ._eb };

// Values returns the value data source.
func (_bag RadarChartSeries )Values ()NumberDataSource {if _bag ._gaf .Val ==nil {_bag ._gaf .Val =_gb .NewCT_NumDataSource ();};return MakeNumberDataSource (_bag ._gaf .Val );};

// X returns the inner wrapped XML type.
func (_dfd Legend )X ()*_gb .CT_Legend {return _dfd ._bgae };

// X returns the inner wrapped XML type.
func (_gbde StockChart )X ()*_gb .CT_StockChart {return _gbde ._edf };

// CategoryAxisDataSource specifies the data for an axis.  It's commonly used with
// SetReference to set the axis data to a range of cells.
type CategoryAxisDataSource struct{_ebd *_gb .CT_AxDataSource };type LineChart struct{chartBase ;_fea *_gb .CT_LineChart ;};

// AddSeries adds a default series to a line chart.
func (_eec LineChart )AddSeries ()LineChartSeries {_eed :=_eec .nextColor (len (_eec ._fea .Ser ));_bfe :=_gb .NewCT_LineSer ();_eec ._fea .Ser =append (_eec ._fea .Ser ,_bfe );_bfe .Idx .ValAttr =uint32 (len (_eec ._fea .Ser )-1);_bfe .Order .ValAttr =uint32 (len (_eec ._fea .Ser )-1);_dbge :=LineChartSeries {_bfe };_dbge .InitializeDefaults ();_dbge .Properties ().LineProperties ().SetSolidFill (_eed );return _dbge ;};

// SetDirection changes the direction of the bar chart (bar or column).
func (_fg Bar3DChart )SetDirection (d _gb .ST_BarDir ){_fg ._ff .BarDir .ValAttr =d };func (_def DateAxis )SetTickLabelPosition (p _gb .ST_TickLblPos ){if p ==_gb .ST_TickLblPosUnset {_def ._agd .TickLblPos =nil ;}else {_def ._agd .TickLblPos =_gb .NewCT_TickLblPos ();_def ._agd .TickLblPos .ValAttr =p ;};};

// X returns the inner wrapped XML type.
func (_fdb PieChart )X ()*_gb .CT_PieChart {return _fdb ._cbf };

// AddSurfaceChart adds a new surface chart to a chart.
func (_acf Chart )AddSurfaceChart ()SurfaceChart {_fbb :=_gb .NewCT_PlotAreaChoice ();_acf ._daf .Chart .PlotArea .Choice =append (_acf ._daf .Chart .PlotArea .Choice ,_fbb );_fbb .SurfaceChart =_gb .NewCT_SurfaceChart ();_ad (_acf ._daf .Chart );_acf ._daf .Chart .View3D .RotX .ValAttr =_c .Int8 (90);_acf ._daf .Chart .View3D .RotY .ValAttr =_c .Uint16 (0);_acf ._daf .Chart .View3D .Perspective =_gb .NewCT_Perspective ();_acf ._daf .Chart .View3D .Perspective .ValAttr =_c .Uint8 (0);_dag :=SurfaceChart {_afce :_fbb .SurfaceChart };_dag .InitializeDefaults ();return _dag ;};

// AddLine3DChart adds a new 3D line chart to a chart.
func (_eeac Chart )AddLine3DChart ()Line3DChart {_ad (_eeac ._daf .Chart );_gdg :=_gb .NewCT_PlotAreaChoice ();_eeac ._daf .Chart .PlotArea .Choice =append (_eeac ._daf .Chart .PlotArea .Choice ,_gdg );_gdg .Line3DChart =_gb .NewCT_Line3DChart ();_gdg .Line3DChart .Grouping =_gb .NewCT_Grouping ();_gdg .Line3DChart .Grouping .ValAttr =_gb .ST_GroupingStandard ;return Line3DChart {_afa :_gdg .Line3DChart };};

// X returns the inner wrapped XML type.
func (_bfag SurfaceChartSeries )X ()*_gb .CT_SurfaceSer {return _bfag ._ebad };

// AddLegend adds a legend to a chart, replacing any existing legend.
func (_cfa Chart )AddLegend ()Legend {_cfa ._daf .Chart .Legend =_gb .NewCT_Legend ();_ega :=MakeLegend (_cfa ._daf .Chart .Legend );_ega .InitializeDefaults ();return _ega ;};func (_df nullAxis )AxisID ()uint32 {return 0};

// AddStockChart adds a new stock chart.
func (_fge Chart )AddStockChart ()StockChart {_ace :=_gb .NewCT_PlotAreaChoice ();_fge ._daf .Chart .PlotArea .Choice =append (_fge ._daf .Chart .PlotArea .Choice ,_ace );_ace .StockChart =_gb .NewCT_StockChart ();_acc :=StockChart {_edf :_ace .StockChart };_acc .InitializeDefaults ();return _acc ;};func (_cac DataLabels )SetPosition (p _gb .ST_DLblPos ){_cac .ensureChoice ();_cac ._bfd .Choice .DLblPos =_gb .NewCT_DLblPos ();_cac ._bfd .Choice .DLblPos .ValAttr =p ;};func (_fb BubbleChart )AddAxis (axis Axis ){_ggcg :=_gb .NewCT_UnsignedInt ();_ggcg .ValAttr =axis .AxisID ();_fb ._bbg .AxId =append (_fb ._bbg .AxId ,_ggcg );};

// Chart is a generic chart.
type Chart struct{_daf *_gb .ChartSpace };

// Values returns the value data source.
func (_db AreaChartSeries )Values ()NumberDataSource {if _db ._cf .Val ==nil {_db ._cf .Val =_gb .NewCT_NumDataSource ();};return MakeNumberDataSource (_db ._cf .Val );};

// AreaChartSeries is a series to be used on an area chart.
type AreaChartSeries struct{_cf *_gb .CT_AreaSer };

// Bar3DChart is a 3D bar chart.
type Bar3DChart struct{chartBase ;_ff *_gb .CT_Bar3DChart ;};

// Properties returns the bar chart series shape properties.
func (_cg BarChartSeries )Properties ()_d .ShapeProperties {if _cg ._bc .SpPr ==nil {_cg ._bc .SpPr =_cb .NewCT_ShapeProperties ();};return _d .MakeShapeProperties (_cg ._bc .SpPr );};func (_agg ScatterChartSeries )SetSmooth (b bool ){_agg ._abg .Smooth =_gb .NewCT_Boolean ();_agg ._abg .Smooth .ValAttr =&b ;};func (_ec Area3DChart )AddAxis (axis Axis ){_f :=_gb .NewCT_UnsignedInt ();_f .ValAttr =axis .AxisID ();_ec ._gba .AxId =append (_ec ._gba .AxId ,_f );};type Line3DChart struct{chartBase ;_afa *_gb .CT_Line3DChart ;};

// X returns the inner wrapped XML type.
func (_fdcf Title )X ()*_gb .CT_Title {return _fdcf ._gded };

// X returns the inner wrapped XML type.
func (_gc Area3DChart )X ()*_gb .CT_Area3DChart {return _gc ._gba };

// X returns the inner wrapped XML type.
func (_gddf RadarChart )X ()*_gb .CT_RadarChart {return _gddf ._fgc };

// Index returns the index of the series
func (_dfg ScatterChartSeries )Index ()uint32 {return _dfg ._abg .Idx .ValAttr };func (_fa CategoryAxis )SetPosition (p _gb .ST_AxPos ){_fa ._ba .AxPos =_gb .NewCT_AxPos ();_fa ._ba .AxPos .ValAttr =p ;};

// CreateEmptyNumberCache creates an empty number cache, which is used sometimes
// to increase file format compatibility.  It should actually contain the
// computed cell data, but just creating an empty one is good enough.
func (_ebb NumberDataSource )CreateEmptyNumberCache (){_ebb .ensureChoice ();if _ebb ._ffe .Choice .NumRef ==nil {_ebb ._ffe .Choice .NumRef =_gb .NewCT_NumRef ();};_ebb ._ffe .Choice .NumLit =nil ;_ebb ._ffe .Choice .NumRef .NumCache =_gb .NewCT_NumData ();_ebb ._ffe .Choice .NumRef .NumCache .PtCount =_gb .NewCT_UnsignedInt ();_ebb ._ffe .Choice .NumRef .NumCache .PtCount .ValAttr =0;};

// SetDisplayBlanksAs controls how missing values are displayed.
func (_bef Chart )SetDisplayBlanksAs (v _gb .ST_DispBlanksAs ){_bef ._daf .Chart .DispBlanksAs =_gb .NewCT_DispBlanksAs ();_bef ._daf .Chart .DispBlanksAs .ValAttr =v ;};

// AddRadarChart adds a new radar chart to a chart.
func (_cfg Chart )AddRadarChart ()RadarChart {_fga :=_gb .NewCT_PlotAreaChoice ();_cfg ._daf .Chart .PlotArea .Choice =append (_cfg ._daf .Chart .PlotArea .Choice ,_fga );_fga .RadarChart =_gb .NewCT_RadarChart ();_ccf :=RadarChart {_fgc :_fga .RadarChart };_ccf .InitializeDefaults ();return _ccf ;};

// X returns the inner wrapped XML type.
func (_gf BarChartSeries )X ()*_gb .CT_BarSer {return _gf ._bc };

// RemoveLegend removes the legend if the chart has one.
func (_bbda Chart )RemoveLegend (){_bbda ._daf .Chart .Legend =nil };

// CategoryAxis returns the category data source.
func (_bf BarChartSeries )CategoryAxis ()CategoryAxisDataSource {if _bf ._bc .Cat ==nil {_bf ._bc .Cat =_gb .NewCT_AxDataSource ();};return MakeAxisDataSource (_bf ._bc .Cat );};func MakeLegend (l *_gb .CT_Legend )Legend {return Legend {l }};

// InitializeDefaults the Stock chart to its defaults
func (_ebae StockChart )InitializeDefaults (){_ebae ._edf .HiLowLines =_gb .NewCT_ChartLines ();_ebae ._edf .UpDownBars =_gb .NewCT_UpDownBars ();_ebae ._edf .UpDownBars .GapWidth =_gb .NewCT_GapAmount ();_ebae ._edf .UpDownBars .GapWidth .ValAttr =&_gb .ST_GapAmount {};_ebae ._edf .UpDownBars .GapWidth .ValAttr .ST_GapAmountUShort =_c .Uint16 (150);_ebae ._edf .UpDownBars .UpBars =_gb .NewCT_UpDownBar ();_ebae ._edf .UpDownBars .DownBars =_gb .NewCT_UpDownBar ();};func (_de DateAxis )MajorGridLines ()GridLines {if _de ._agd .MajorGridlines ==nil {_de ._agd .MajorGridlines =_gb .NewCT_ChartLines ();};return GridLines {_de ._agd .MajorGridlines };};

// Properties returns the bar chart series shape properties.
func (_afca PieChartSeries )Properties ()_d .ShapeProperties {if _afca ._gbg .SpPr ==nil {_afca ._gbg .SpPr =_cb .NewCT_ShapeProperties ();};return _d .MakeShapeProperties (_afca ._gbg .SpPr );};func (_eegf LineChartSeries )SetSmooth (b bool ){_eegf ._feaa .Smooth =_gb .NewCT_Boolean ();_eegf ._feaa .Smooth .ValAttr =&b ;};

// RemoveTitle removes any existing title from the chart.
func (_afd Chart )RemoveTitle (){_afd ._daf .Chart .Title =nil ;_afd ._daf .Chart .AutoTitleDeleted =_gb .NewCT_Boolean ();_afd ._daf .Chart .AutoTitleDeleted .ValAttr =_c .Bool (true );};func (_eba CategoryAxis )SetTickLabelPosition (p _gb .ST_TickLblPos ){if p ==_gb .ST_TickLblPosUnset {_eba ._ba .TickLblPos =nil ;}else {_eba ._ba .TickLblPos =_gb .NewCT_TickLblPos ();_eba ._ba .TickLblPos .ValAttr =p ;};};

// X returns the inner wrapped XML type.
func (_cdab BubbleChartSeries )X ()*_gb .CT_BubbleSer {return _cdab ._afe };

// SetText sets the series text.
func (_eff RadarChartSeries )SetText (s string ){_eff ._gaf .Tx =_gb .NewCT_SerTx ();_eff ._gaf .Tx .Choice .V =&s ;};func (_gea SeriesAxis )InitializeDefaults (){};func (_gaa DataLabels )SetShowLeaderLines (b bool ){_gaa .ensureChoice ();_gaa ._bfd .Choice .ShowLeaderLines =_gb .NewCT_Boolean ();_gaa ._bfd .Choice .ShowLeaderLines .ValAttr =_c .Bool (b );};type Title struct{_gded *_gb .CT_Title };func _ad (_ede *_gb .CT_Chart ){_ede .View3D =_gb .NewCT_View3D ();_ede .View3D .RotX =_gb .NewCT_RotX ();_ede .View3D .RotX .ValAttr =_c .Int8 (15);_ede .View3D .RotY =_gb .NewCT_RotY ();_ede .View3D .RotY .ValAttr =_c .Uint16 (20);_ede .View3D .RAngAx =_gb .NewCT_Boolean ();_ede .View3D .RAngAx .ValAttr =_c .Bool (false );_ede .Floor =_gb .NewCT_Surface ();_ede .Floor .Thickness =_gb .NewCT_Thickness ();_ede .Floor .Thickness .ValAttr .Uint32 =_c .Uint32 (0);_ede .SideWall =_gb .NewCT_Surface ();_ede .SideWall .Thickness =_gb .NewCT_Thickness ();_ede .SideWall .Thickness .ValAttr .Uint32 =_c .Uint32 (0);_ede .BackWall =_gb .NewCT_Surface ();_ede .BackWall .Thickness =_gb .NewCT_Thickness ();_ede .BackWall .Thickness .ValAttr .Uint32 =_c .Uint32 (0);};func MakeMarker (x *_gb .CT_Marker )Marker {return Marker {x }};

// AddAxis adds an axis to a Surface chart.
func (_gcd SurfaceChart )AddAxis (axis Axis ){_adf :=_gb .NewCT_UnsignedInt ();_adf .ValAttr =axis .AxisID ();_gcd ._afce .AxId =append (_gcd ._afce .AxId ,_adf );};

// Properties returns the line chart series shape properties.
func (_fbbge SurfaceChartSeries )Properties ()_d .ShapeProperties {if _fbbge ._ebad .SpPr ==nil {_fbbge ._ebad .SpPr =_cb .NewCT_ShapeProperties ();};return _d .MakeShapeProperties (_fbbge ._ebad .SpPr );};func MakeNumberDataSource (x *_gb .CT_NumDataSource )NumberDataSource {return NumberDataSource {x }};func (_bgad DateAxis )SetCrosses (axis Axis ){_bgad ._agd .CrossAx .ValAttr =axis .AxisID ()};func (_ggaf LineChartSeries )Values ()NumberDataSource {if _ggaf ._feaa .Val ==nil {_ggaf ._feaa .Val =_gb .NewCT_NumDataSource ();};return MakeNumberDataSource (_ggaf ._feaa .Val );};

// X returns the inner wrapped XML type.
func (_gege GridLines )X ()*_gb .CT_ChartLines {return _gege ._afcd };

// AddDoughnutChart adds a new doughnut (pie with a hole in the center) chart to a chart.
func (_bdb Chart )AddDoughnutChart ()DoughnutChart {_aed :=_gb .NewCT_PlotAreaChoice ();_bdb ._daf .Chart .PlotArea .Choice =append (_bdb ._daf .Chart .PlotArea .Choice ,_aed );_aed .DoughnutChart =_gb .NewCT_DoughnutChart ();_cdf :=DoughnutChart {_dec :_aed .DoughnutChart };_cdf .InitializeDefaults ();return _cdf ;};func (_dce CategoryAxis )Properties ()_d .ShapeProperties {if _dce ._ba .SpPr ==nil {_dce ._ba .SpPr =_cb .NewCT_ShapeProperties ();};return _d .MakeShapeProperties (_dce ._ba .SpPr );};func (_eaf Legend )InitializeDefaults (){_eaf .SetPosition (_gb .ST_LegendPosR );_eaf .SetOverlay (false );_eaf .Properties ().SetNoFill ();_eaf .Properties ().LineProperties ().SetNoFill ();};

// AddAxis adds an axis to a Scatter chart.
func (_bcaa ScatterChart )AddAxis (axis Axis ){_eaa :=_gb .NewCT_UnsignedInt ();_eaa .ValAttr =axis .AxisID ();_bcaa ._aea .AxId =append (_bcaa ._aea .AxId ,_eaa );};

// Axis is the interface implemented by different axes when assigning to a
// chart.
type Axis interface{AxisID ()uint32 ;};

// AreaChart is an area chart that has a shaded area underneath a curve.
type AreaChart struct{chartBase ;_eb *_gb .CT_AreaChart ;};func (_cfbc SeriesAxis )SetCrosses (axis Axis ){_cfbc ._cfgb .CrossAx .ValAttr =axis .AxisID ()};func MakeCategoryAxis (x *_gb .CT_CatAx )CategoryAxis {return CategoryAxis {x }};

// AddBarChart adds a new bar chart to a chart.
func (_efd Chart )AddBarChart ()BarChart {_ae :=_gb .NewCT_PlotAreaChoice ();_efd ._daf .Chart .PlotArea .Choice =append (_efd ._daf .Chart .PlotArea .Choice ,_ae );_ae .BarChart =_gb .NewCT_BarChart ();_ae .BarChart .Grouping =_gb .NewCT_BarGrouping ();_ae .BarChart .Grouping .ValAttr =_gb .ST_BarGroupingStandard ;_bga :=BarChart {_ggc :_ae .BarChart };_bga .InitializeDefaults ();return _bga ;};

// InitializeDefaults the bar chart to its defaults
func (_cd AreaChart )InitializeDefaults (){};

// X returns the inner wrapped XML type.
func (_ffc Bar3DChart )X ()*_gb .CT_Bar3DChart {return _ffc ._ff };func (_aded ValueAxis )SetTickLabelPosition (p _gb .ST_TickLblPos ){if p ==_gb .ST_TickLblPosUnset {_aded ._dffd .TickLblPos =nil ;}else {_aded ._dffd .TickLblPos =_gb .NewCT_TickLblPos ();_aded ._dffd .TickLblPos .ValAttr =p ;};};

// AddSeries adds a default series to a bar chart.
func (_agb BarChart )AddSeries ()BarChartSeries {_gca :=_agb .nextColor (len (_agb ._ggc .Ser ));_fgg :=_gb .NewCT_BarSer ();_agb ._ggc .Ser =append (_agb ._ggc .Ser ,_fgg );_fgg .Idx .ValAttr =uint32 (len (_agb ._ggc .Ser )-1);_fgg .Order .ValAttr =uint32 (len (_agb ._ggc .Ser )-1);_fe :=BarChartSeries {_fgg };_fe .InitializeDefaults ();_fe .Properties ().SetSolidFill (_gca );return _fe ;};

// AddSeries adds a default series to a bar chart.
func (_cba Bar3DChart )AddSeries ()BarChartSeries {_gde :=_cba .nextColor (len (_cba ._ff .Ser ));_ecb :=_gb .NewCT_BarSer ();_cba ._ff .Ser =append (_cba ._ff .Ser ,_ecb );_ecb .Idx .ValAttr =uint32 (len (_cba ._ff .Ser )-1);_ecb .Order .ValAttr =uint32 (len (_cba ._ff .Ser )-1);_cdd :=BarChartSeries {_ecb };_cdd .InitializeDefaults ();_cdd .Properties ().SetSolidFill (_gde );return _cdd ;};

// Index returns the index of the series
func (_gdge SurfaceChartSeries )Index ()uint32 {return _gdge ._ebad .Idx .ValAttr };func (_bcab Legend )SetPosition (p _gb .ST_LegendPos ){if p ==_gb .ST_LegendPosUnset {_bcab ._bgae .LegendPos =nil ;}else {_bcab ._bgae .LegendPos =_gb .NewCT_LegendPos ();_bcab ._bgae .LegendPos .ValAttr =p ;};};

// AddSeries adds a default series to an Pie3D chart.
func (_dffg Pie3DChart )AddSeries ()PieChartSeries {_fdfa :=_gb .NewCT_PieSer ();_dffg ._cacd .Ser =append (_dffg ._cacd .Ser ,_fdfa );_fdfa .Idx .ValAttr =uint32 (len (_dffg ._cacd .Ser )-1);_fdfa .Order .ValAttr =uint32 (len (_dffg ._cacd .Ser )-1);_egca :=PieChartSeries {_fdfa };_egca .InitializeDefaults ();return _egca ;};func (_ef AreaChart )AddAxis (axis Axis ){_bbb :=_gb .NewCT_UnsignedInt ();_bbb .ValAttr =axis .AxisID ();_ef ._eb .AxId =append (_ef ._eb .AxId ,_bbb );};

// AddAxis adds an axis to a Surface chart.
func (_adeb Surface3DChart )AddAxis (axis Axis ){_dgf :=_gb .NewCT_UnsignedInt ();_dgf .ValAttr =axis .AxisID ();_adeb ._dgd .AxId =append (_adeb ._dgd .AxId ,_dgf );};func (_cge Legend )SetOverlay (b bool ){_cge ._bgae .Overlay =_gb .NewCT_Boolean ();_cge ._bgae .Overlay .ValAttr =_c .Bool (b );};

// CategoryAxis returns the category data source.
func (_aee RadarChartSeries )CategoryAxis ()CategoryAxisDataSource {if _aee ._gaf .Cat ==nil {_aee ._gaf .Cat =_gb .NewCT_AxDataSource ();};return MakeAxisDataSource (_aee ._gaf .Cat );};

// BubbleChartSeries is a series to be used on a Bubble chart.
type BubbleChartSeries struct{_afe *_gb .CT_BubbleSer };

// X returns the inner wrapped XML type.
func (_fbg ScatterChartSeries )X ()*_gb .CT_ScatterSer {return _fbg ._abg };func (_eae DateAxis )SetMajorTickMark (m _gb .ST_TickMark ){if m ==_gb .ST_TickMarkUnset {_eae ._agd .MajorTickMark =nil ;}else {_eae ._agd .MajorTickMark =_gb .NewCT_TickMark ();_eae ._agd .MajorTickMark .ValAttr =m ;};};

// AddScatterChart adds a scatter (X/Y) chart.
func (_fbe Chart )AddScatterChart ()ScatterChart {_egd :=_gb .NewCT_PlotAreaChoice ();_fbe ._daf .Chart .PlotArea .Choice =append (_fbe ._daf .Chart .PlotArea .Choice ,_egd );_egd .ScatterChart =_gb .NewCT_ScatterChart ();_afc :=ScatterChart {_aea :_egd .ScatterChart };_afc .InitializeDefaults ();return _afc ;};

// AddAxis adds an axis to a line chart.
func (_bfb LineChart )AddAxis (axis Axis ){_gcg :=_gb .NewCT_UnsignedInt ();_gcg .ValAttr =axis .AxisID ();_bfb ._fea .AxId =append (_bfb ._fea .AxId ,_gcg );};

// InitializeDefaults the bar chart to its defaults
func (_gbbb PieChart )InitializeDefaults (){_gbbb ._cbf .VaryColors =_gb .NewCT_Boolean ();_gbbb ._cbf .VaryColors .ValAttr =_c .Bool (true );};

// AddCategoryAxis adds a category axis.
func (_age Chart )AddCategoryAxis ()CategoryAxis {_ecff :=_gb .NewCT_CatAx ();if _age ._daf .Chart .PlotArea .CChoice ==nil {_age ._daf .Chart .PlotArea .CChoice =_gb .NewCT_PlotAreaChoice1 ();};_ecff .AxId =_gb .NewCT_UnsignedInt ();_ecff .AxId .ValAttr =0x7FFFFFFF&_ce .Uint32 ();_age ._daf .Chart .PlotArea .CChoice .CatAx =append (_age ._daf .Chart .PlotArea .CChoice .CatAx ,_ecff );_ecff .Auto =_gb .NewCT_Boolean ();_ecff .Auto .ValAttr =_c .Bool (true );_ecff .Delete =_gb .NewCT_Boolean ();_ecff .Delete .ValAttr =_c .Bool (false );_eee :=MakeCategoryAxis (_ecff );_eee .InitializeDefaults ();return _eee ;};

// Values returns the value data source.
func (_gfce PieChartSeries )Values ()NumberDataSource {if _gfce ._gbg .Val ==nil {_gfce ._gbg .Val =_gb .NewCT_NumDataSource ();};return MakeNumberDataSource (_gfce ._gbg .Val );};

// X returns the inner wrapped XML type.
func (_ceec LineChart )X ()*_gb .CT_LineChart {return _ceec ._fea };func (_gdc BarChart )AddAxis (axis Axis ){_bg :=_gb .NewCT_UnsignedInt ();_bg .ValAttr =axis .AxisID ();_gdc ._ggc .AxId =append (_gdc ._ggc .AxId ,_bg );};

// PieChartSeries is a series to be used on an Pie chart.
type PieChartSeries struct{_gbg *_gb .CT_PieSer };

// SetIndex sets the index of the series
func (_ffg ScatterChartSeries )SetIndex (idx uint32 ){_ffg ._abg .Idx .ValAttr =idx };func (_gff DateAxis )Properties ()_d .ShapeProperties {if _gff ._agd .SpPr ==nil {_gff ._agd .SpPr =_cb .NewCT_ShapeProperties ();};return _d .MakeShapeProperties (_gff ._agd .SpPr );};

// PieOfPieChart is a Pie chart with an extra Pie chart.
type PieOfPieChart struct{chartBase ;_fca *_gb .CT_OfPieChart ;};func (_fac Chart )AddSeriesAxis ()SeriesAxis {_bcg :=_gb .NewCT_SerAx ();if _fac ._daf .Chart .PlotArea .CChoice ==nil {_fac ._daf .Chart .PlotArea .CChoice =_gb .NewCT_PlotAreaChoice1 ();};_bcg .AxId =_gb .NewCT_UnsignedInt ();_bcg .AxId .ValAttr =0x7FFFFFFF&_ce .Uint32 ();_fac ._daf .Chart .PlotArea .CChoice .SerAx =append (_fac ._daf .Chart .PlotArea .CChoice .SerAx ,_bcg );_bcg .Delete =_gb .NewCT_Boolean ();_bcg .Delete .ValAttr =_c .Bool (false );_geg :=MakeSeriesAxis (_bcg );_geg .InitializeDefaults ();return _geg ;};func (_deb NumberDataSource )ensureChoice (){if _deb ._ffe .Choice ==nil {_deb ._ffe .Choice =_gb .NewCT_NumDataSourceChoice ();};};

// SetText sets the series text
func (_aeed ScatterChartSeries )SetText (s string ){_aeed ._abg .Tx =_gb .NewCT_SerTx ();_aeed ._abg .Tx .Choice .V =&s ;};type CategoryAxis struct{_ba *_gb .CT_CatAx };func (_beb Title )InitializeDefaults (){_beb .SetText ("\u0054\u0069\u0074l\u0065");_beb .RunProperties ().SetSize (16*_b .Point );_beb .RunProperties ().SetSolidFill (_e .Black );_beb .RunProperties ().SetFont ("\u0043\u0061\u006c\u0069\u0062\u0020\u0072\u0069");_beb .RunProperties ().SetBold (false );};type nullAxis byte ;func (_bdcf DateAxis )AxisID ()uint32 {return _bdcf ._agd .AxId .ValAttr };type ValueAxis struct{_dffd *_gb .CT_ValAx };func (_ade NumberDataSource )SetReference (s string ){_ade .ensureChoice ();if _ade ._ffe .Choice .NumRef ==nil {_ade ._ffe .Choice .NumRef =_gb .NewCT_NumRef ();};_ade ._ffe .Choice .NumRef .F =s ;};func (_gadd ValueAxis )SetCrosses (axis Axis ){_gadd ._dffd .CrossAx .ValAttr =axis .AxisID ()};type SurfaceChartSeries struct{_ebad *_gb .CT_SurfaceSer };

// X returns the inner wrapped XML type.
func (_eeag PieOfPieChart )X ()*_gb .CT_OfPieChart {return _eeag ._fca };func (_bcc CategoryAxis )SetMinorTickMark (m _gb .ST_TickMark ){if m ==_gb .ST_TickMarkUnset {_bcc ._ba .MinorTickMark =nil ;}else {_bcc ._ba .MinorTickMark =_gb .NewCT_TickMark ();_bcc ._ba .MinorTickMark .ValAttr =m ;};};func (_ecc SurfaceChart )InitializeDefaults (){_ecc ._afce .Wireframe =_gb .NewCT_Boolean ();_ecc ._afce .Wireframe .ValAttr =_c .Bool (false );_ecc ._afce .BandFmts =_gb .NewCT_BandFmts ();for _afcaf :=0;_afcaf < 15;_afcaf ++{_abf :=_gb .NewCT_BandFmt ();_abf .Idx .ValAttr =uint32 (_afcaf );_abf .SpPr =_cb .NewCT_ShapeProperties ();_caf :=_d .MakeShapeProperties (_abf .SpPr );_caf .SetSolidFill (_ecc .nextColor (_afcaf ));_ecc ._afce .BandFmts .BandFmt =append (_ecc ._afce .BandFmts .BandFmt ,_abf );};};

// BarChartSeries is a series to be used on a bar chart.
type BarChartSeries struct{_bc *_gb .CT_BarSer };

// InitializeDefaults initializes a Bubble chart series to the default values.
func (_bda BubbleChartSeries )InitializeDefaults (){};

// SetValues sets values directly on a source.
func (_gfc NumberDataSource )SetValues (v []float64 ){_gfc .ensureChoice ();_gfc ._ffe .Choice .NumRef =nil ;_gfc ._ffe .Choice .NumLit =_gb .NewCT_NumData ();_gfc ._ffe .Choice .NumLit .PtCount =_gb .NewCT_UnsignedInt ();_gfc ._ffe .Choice .NumLit .PtCount .ValAttr =uint32 (len (v ));for _bcb ,_ggfd :=range v {_gfc ._ffe .Choice .NumLit .Pt =append (_gfc ._ffe .Choice .NumLit .Pt ,&_gb .CT_NumVal {IdxAttr :uint32 (_bcb ),V :_gg .Sprintf ("\u0025\u0067",_ggfd )});};};

// InitializeDefaults the bar chart to its defaults
func (_fdfd Pie3DChart )InitializeDefaults (){_fdfd ._cacd .VaryColors =_gb .NewCT_Boolean ();_fdfd ._cacd .VaryColors .ValAttr =_c .Bool (true );};

// SetOrder sets the order of the series
func (_dcb SurfaceChartSeries )SetOrder (idx uint32 ){_dcb ._ebad .Order .ValAttr =idx };

// Values returns the value data source.
func (_dc BarChartSeries )Values ()NumberDataSource {if _dc ._bc .Val ==nil {_dc ._bc .Val =_gb .NewCT_NumDataSource ();};return MakeNumberDataSource (_dc ._bc .Val );};

// SetIndex sets the index of the series
func (_dadb SurfaceChartSeries )SetIndex (idx uint32 ){_dadb ._ebad .Idx .ValAttr =idx };

// Surface3DChart is a 3D view of a surface chart.
type Surface3DChart struct{chartBase ;_dgd *_gb .CT_Surface3DChart ;};

// X returns the inner wrapped XML type.
func (_ggf DoughnutChart )X ()*_gb .CT_DoughnutChart {return _ggf ._dec };

// DoughnutChart is a Doughnut chart.
type DoughnutChart struct{chartBase ;_dec *_gb .CT_DoughnutChart ;};

// Properties returns the line chart series shape properties.
func (_feb LineChartSeries )Properties ()_d .ShapeProperties {if _feb ._feaa .SpPr ==nil {_feb ._feaa .SpPr =_cb .NewCT_ShapeProperties ();};return _d .MakeShapeProperties (_feb ._feaa .SpPr );};func (_ga CategoryAxis )SetMajorTickMark (m _gb .ST_TickMark ){if m ==_gb .ST_TickMarkUnset {_ga ._ba .MajorTickMark =nil ;}else {_ga ._ba .MajorTickMark =_gb .NewCT_TickMark ();_ga ._ba .MajorTickMark .ValAttr =m ;};};

// Properties returns the chart's shape properties.
func (_gad Chart )Properties ()_d .ShapeProperties {if _gad ._daf .SpPr ==nil {_gad ._daf .SpPr =_cb .NewCT_ShapeProperties ();};return _d .MakeShapeProperties (_gad ._daf .SpPr );};func (_gbdb DataLabels )SetShowCategoryName (b bool ){_gbdb .ensureChoice ();_gbdb ._bfd .Choice .ShowCatName =_gb .NewCT_Boolean ();_gbdb ._bfd .Choice .ShowCatName .ValAttr =_c .Bool (b );};

// AddSeries adds a default series to a line chart.
func (_eead Line3DChart )AddSeries ()LineChartSeries {_acb :=_eead .nextColor (len (_eead ._afa .Ser ));_aeda :=_gb .NewCT_LineSer ();_eead ._afa .Ser =append (_eead ._afa .Ser ,_aeda );_aeda .Idx .ValAttr =uint32 (len (_eead ._afa .Ser )-1);_aeda .Order .ValAttr =uint32 (len (_eead ._afa .Ser )-1);_dbga :=LineChartSeries {_aeda };_dbga .InitializeDefaults ();_dbga .Properties ().LineProperties ().SetSolidFill (_acb );_dbga .Properties ().SetSolidFill (_acb );return _dbga ;};func (_cgcd LineChartSeries )InitializeDefaults (){_cgcd .Properties ().LineProperties ().SetWidth (1*_b .Point );_cgcd .Properties ().LineProperties ().SetSolidFill (_e .Black );_cgcd .Properties ().LineProperties ().SetJoin (_d .LineJoinRound );_cgcd .Marker ().SetSymbol (_gb .ST_MarkerStyleNone );_cgcd .Labels ().SetShowLegendKey (false );_cgcd .Labels ().SetShowValue (false );_cgcd .Labels ().SetShowPercent (false );_cgcd .Labels ().SetShowCategoryName (false );_cgcd .Labels ().SetShowSeriesName (false );_cgcd .Labels ().SetShowLeaderLines (false );};func (_fbcf SurfaceChartSeries )InitializeDefaults (){_fbcf .Properties ().LineProperties ().SetWidth (1*_b .Point );_fbcf .Properties ().LineProperties ().SetSolidFill (_e .Black );_fbcf .Properties ().LineProperties ().SetJoin (_d .LineJoinRound );};

// AddSeries adds a default series to a Surface chart.
func (_ged Surface3DChart )AddSeries ()SurfaceChartSeries {_daa :=_ged .nextColor (len (_ged ._dgd .Ser ));_dae :=_gb .NewCT_SurfaceSer ();_ged ._dgd .Ser =append (_ged ._dgd .Ser ,_dae );_dae .Idx .ValAttr =uint32 (len (_ged ._dgd .Ser )-1);_dae .Order .ValAttr =uint32 (len (_ged ._dgd .Ser )-1);_dda :=SurfaceChartSeries {_dae };_dda .InitializeDefaults ();_dda .Properties ().LineProperties ().SetSolidFill (_daa );return _dda ;};

// InitializeDefaults the Bubble chart to its defaults
func (_cag BubbleChart )InitializeDefaults (){};

// AddBar3DChart adds a new 3D bar chart to a chart.
func (_faa Chart )AddBar3DChart ()Bar3DChart {_ad (_faa ._daf .Chart );_aff :=_gb .NewCT_PlotAreaChoice ();_faa ._daf .Chart .PlotArea .Choice =append (_faa ._daf .Chart .PlotArea .Choice ,_aff );_aff .Bar3DChart =_gb .NewCT_Bar3DChart ();_aff .Bar3DChart .Grouping =_gb .NewCT_BarGrouping ();_aff .Bar3DChart .Grouping .ValAttr =_gb .ST_BarGroupingStandard ;_cfb :=Bar3DChart {_ff :_aff .Bar3DChart };_cfb .InitializeDefaults ();return _cfb ;};

// Area3DChart is an area chart that has a shaded area underneath a curve.
type Area3DChart struct{chartBase ;_gba *_gb .CT_Area3DChart ;};type DateAxis struct{_agd *_gb .CT_DateAx };

// X returns the inner wrapped XML type.
func (_gd AreaChartSeries )X ()*_gb .CT_AreaSer {return _gd ._cf };

// Order returns the order of the series
func (_eecd ScatterChartSeries )Order ()uint32 {return _eecd ._abg .Order .ValAttr };func (_gfbc Title )SetText (s string ){if _gfbc ._gded .Tx ==nil {_gfbc ._gded .Tx =_gb .NewCT_Tx ();};if _gfbc ._gded .Tx .Choice .Rich ==nil {_gfbc ._gded .Tx .Choice .Rich =_cb .NewCT_TextBody ();};var _afb *_cb .CT_TextParagraph ;if len (_gfbc ._gded .Tx .Choice .Rich .P )==0{_afb =_cb .NewCT_TextParagraph ();_gfbc ._gded .Tx .Choice .Rich .P =[]*_cb .CT_TextParagraph {_afb };}else {_afb =_gfbc ._gded .Tx .Choice .Rich .P [0];};var _gfa *_cb .EG_TextRun ;if len (_afb .EG_TextRun )==0{_gfa =_cb .NewEG_TextRun ();_afb .EG_TextRun =[]*_cb .EG_TextRun {_gfa };}else {_gfa =_afb .EG_TextRun [0];};if _gfa .R ==nil {_gfa .R =_cb .NewCT_RegularTextRun ();};_gfa .R .T =s ;};

// SetOrder sets the order of the series
func (_cgaa ScatterChartSeries )SetOrder (idx uint32 ){_cgaa ._abg .Order .ValAttr =idx };

// X returns the inner wrapped XML type.
func (_gdec BarChart )X ()*_gb .CT_BarChart {return _gdec ._ggc };

// RadarChartSeries is a series to be used on an Radar chart.
type RadarChartSeries struct{_gaf *_gb .CT_RadarSer };

// SurfaceChart is a 3D surface chart, viewed from the top-down.
type SurfaceChart struct{chartBase ;_afce *_gb .CT_SurfaceChart ;};func (_cafd SurfaceChartSeries )CategoryAxis ()CategoryAxisDataSource {if _cafd ._ebad .Cat ==nil {_cafd ._ebad .Cat =_gb .NewCT_AxDataSource ();};return MakeAxisDataSource (_cafd ._ebad .Cat );};

// AddPieChart adds a new pie chart to a chart.
func (_acca Chart )AddPieChart ()PieChart {_ecfe :=_gb .NewCT_PlotAreaChoice ();_acca ._daf .Chart .PlotArea .Choice =append (_acca ._daf .Chart .PlotArea .Choice ,_ecfe );_ecfe .PieChart =_gb .NewCT_PieChart ();_becd :=PieChart {_cbf :_ecfe .PieChart };_becd .InitializeDefaults ();return _becd ;};

// AddValueAxis adds a value axis to the chart.
func (_fc Chart )AddValueAxis ()ValueAxis {_gac :=_gb .NewCT_ValAx ();if _fc ._daf .Chart .PlotArea .CChoice ==nil {_fc ._daf .Chart .PlotArea .CChoice =_gb .NewCT_PlotAreaChoice1 ();};_gac .AxId =_gb .NewCT_UnsignedInt ();_gac .AxId .ValAttr =0x7FFFFFFF&_ce .Uint32 ();_fc ._daf .Chart .PlotArea .CChoice .ValAx =append (_fc ._daf .Chart .PlotArea .CChoice .ValAx ,_gac );_gac .Delete =_gb .NewCT_Boolean ();_gac .Delete .ValAttr =_c .Bool (false );_gac .Scaling =_gb .NewCT_Scaling ();_gac .Scaling .Orientation =_gb .NewCT_Orientation ();_gac .Scaling .Orientation .ValAttr =_gb .ST_OrientationMinMax ;_gac .Choice =&_gb .EG_AxSharedChoice {};_gac .Choice .Crosses =_gb .NewCT_Crosses ();_gac .Choice .Crosses .ValAttr =_gb .ST_CrossesAutoZero ;_gac .CrossBetween =_gb .NewCT_CrossBetween ();_gac .CrossBetween .ValAttr =_gb .ST_CrossBetweenBetween ;_eeg :=MakeValueAxis (_gac );_eeg .MajorGridLines ().Properties ().LineProperties ().SetSolidFill (_e .LightGray );_eeg .SetMajorTickMark (_gb .ST_TickMarkOut );_eeg .SetMinorTickMark (_gb .ST_TickMarkIn );_eeg .SetTickLabelPosition (_gb .ST_TickLblPosNextTo );_eeg .Properties ().LineProperties ().SetSolidFill (_e .Black );_eeg .SetPosition (_gb .ST_AxPosL );return _eeg ;};

// X returns the inner wrapped XML type.
func (_cbb Marker )X ()*_gb .CT_Marker {return _cbb ._dff };

// AddAxis adds an axis to a line chart.
func (_gbb Line3DChart )AddAxis (axis Axis ){_edb :=_gb .NewCT_UnsignedInt ();_edb .ValAttr =axis .AxisID ();_gbb ._afa .AxId =append (_gbb ._afa .AxId ,_edb );};

// X returns the inner wrapped XML type.
func (_ccd DateAxis )X ()*_gb .CT_DateAx {return _ccd ._agd };

// InitializeDefaults initializes an area series to the default values.
func (_be AreaChartSeries )InitializeDefaults (){};

// InitializeDefaults the bar chart to its defaults
func (_dbe PieOfPieChart )InitializeDefaults (){_dbe ._fca .VaryColors =_gb .NewCT_Boolean ();_dbe ._fca .VaryColors .ValAttr =_c .Bool (true );_dbe .SetType (_gb .ST_OfPieTypePie );_dbe ._fca .SecondPieSize =_gb .NewCT_SecondPieSize ();_dbe ._fca .SecondPieSize .ValAttr =&_gb .ST_SecondPieSize {};_dbe ._fca .SecondPieSize .ValAttr .ST_SecondPieSizeUShort =_c .Uint16 (75);_baa :=_gb .NewCT_ChartLines ();_baa .SpPr =_cb .NewCT_ShapeProperties ();_dfdd :=_d .MakeShapeProperties (_baa .SpPr );_dfdd .LineProperties ().SetSolidFill (_e .Auto );_dbe ._fca .SerLines =append (_dbe ._fca .SerLines ,_baa );};func (_gee DateAxis )SetMinorTickMark (m _gb .ST_TickMark ){if m ==_gb .ST_TickMarkUnset {_gee ._agd .MinorTickMark =nil ;}else {_gee ._agd .MinorTickMark =_gb .NewCT_TickMark ();_gee ._agd .MinorTickMark .ValAttr =m ;};};

// Labels returns the data label properties.
func (_bce ScatterChartSeries )Labels ()DataLabels {if _bce ._abg .DLbls ==nil {_bce ._abg .DLbls =_gb .NewCT_DLbls ();};return MakeDataLabels (_bce ._abg .DLbls );};func (_ggcd CategoryAxis )AxisID ()uint32 {return _ggcd ._ba .AxId .ValAttr };

// X returns the inner wrapped XML type.
func (_egdg Line3DChart )X ()*_gb .CT_Line3DChart {return _egdg ._afa };func (_deca ValueAxis )SetPosition (p _gb .ST_AxPos ){_deca ._dffd .AxPos =_gb .NewCT_AxPos ();_deca ._dffd .AxPos .ValAttr =p ;};

// Order returns the order of the series
func (_fce SurfaceChartSeries )Order ()uint32 {return _fce ._ebad .Order .ValAttr };

// ScatterChartSeries is the data series for a scatter chart.
type ScatterChartSeries struct{_abg *_gb .CT_ScatterSer };

// SetText sets the series text.
func (_cgf PieChartSeries )SetText (s string ){_cgf ._gbg .Tx =_gb .NewCT_SerTx ();_cgf ._gbg .Tx .Choice .V =&s ;};func (_eg Bar3DChart )AddAxis (axis Axis ){_ag :=_gb .NewCT_UnsignedInt ();_ag .ValAttr =axis .AxisID ();_eg ._ff .AxId =append (_eg ._ff .AxId ,_ag );};type chartBase struct{};func (_bbf Marker )SetSize (sz uint8 ){_bbf ._dff .Size =_gb .NewCT_MarkerSize ();_bbf ._dff .Size .ValAttr =&sz ;};

// CategoryAxis returns the category data source.
func (_dge PieChartSeries )CategoryAxis ()CategoryAxisDataSource {if _dge ._gbg .Cat ==nil {_dge ._gbg .Cat =_gb .NewCT_AxDataSource ();};return MakeAxisDataSource (_dge ._gbg .Cat );};

// AddDateAxis adds a value axis to the chart.
func (_dad Chart )AddDateAxis ()DateAxis {_cdb :=_gb .NewCT_DateAx ();if _dad ._daf .Chart .PlotArea .CChoice ==nil {_dad ._daf .Chart .PlotArea .CChoice =_gb .NewCT_PlotAreaChoice1 ();};_cdb .AxId =_gb .NewCT_UnsignedInt ();_cdb .AxId .ValAttr =0x7FFFFFFF&_ce .Uint32 ();_dad ._daf .Chart .PlotArea .CChoice .DateAx =append (_dad ._daf .Chart .PlotArea .CChoice .DateAx ,_cdb );_cdb .Delete =_gb .NewCT_Boolean ();_cdb .Delete .ValAttr =_c .Bool (false );_cdb .Scaling =_gb .NewCT_Scaling ();_cdb .Scaling .Orientation =_gb .NewCT_Orientation ();_cdb .Scaling .Orientation .ValAttr =_gb .ST_OrientationMinMax ;_cdb .Choice =&_gb .EG_AxSharedChoice {};_cdb .Choice .Crosses =_gb .NewCT_Crosses ();_cdb .Choice .Crosses .ValAttr =_gb .ST_CrossesAutoZero ;_gge :=DateAxis {_cdb };_gge .MajorGridLines ().Properties ().LineProperties ().SetSolidFill (_e .LightGray );_gge .SetMajorTickMark (_gb .ST_TickMarkOut );_gge .SetMinorTickMark (_gb .ST_TickMarkIn );_gge .SetTickLabelPosition (_gb .ST_TickLblPosNextTo );_gge .Properties ().LineProperties ().SetSolidFill (_e .Black );_gge .SetPosition (_gb .ST_AxPosL );return _gge ;};

// AddBubbleChart adds a new bubble chart.
func (_ddb Chart )AddBubbleChart ()BubbleChart {_dbg :=_gb .NewCT_PlotAreaChoice ();_ddb ._daf .Chart .PlotArea .Choice =append (_ddb ._daf .Chart .PlotArea .Choice ,_dbg );_dbg .BubbleChart =_gb .NewCT_BubbleChart ();_aga :=BubbleChart {_bbg :_dbg .BubbleChart };_aga .InitializeDefaults ();return _aga ;};

// SetText sets the series text.
func (_agc BarChartSeries )SetText (s string ){_agc ._bc .Tx =_gb .NewCT_SerTx ();_agc ._bc .Tx .Choice .V =&s ;};

// AddSeries adds a default series to an Radar chart.
func (_adgg RadarChart )AddSeries ()RadarChartSeries {_fbab :=_adgg .nextColor (len (_adgg ._fgc .Ser ));_fdc :=_gb .NewCT_RadarSer ();_adgg ._fgc .Ser =append (_adgg ._fgc .Ser ,_fdc );_fdc .Idx .ValAttr =uint32 (len (_adgg ._fgc .Ser )-1);_fdc .Order .ValAttr =uint32 (len (_adgg ._fgc .Ser )-1);_bfeg :=RadarChartSeries {_fdc };_bfeg .InitializeDefaults ();_bfeg .Properties ().SetSolidFill (_fbab );return _bfeg ;};func (_aad ScatterChartSeries )Values ()NumberDataSource {if _aad ._abg .YVal ==nil {_aad ._abg .YVal =_gb .NewCT_NumDataSource ();};return MakeNumberDataSource (_aad ._abg .YVal );};func (_ceeb SurfaceChartSeries )Values ()NumberDataSource {if _ceeb ._ebad .Val ==nil {_ceeb ._ebad .Val =_gb .NewCT_NumDataSource ();};_gacd :=MakeNumberDataSource (_ceeb ._ebad .Val );_gacd .CreateEmptyNumberCache ();return _gacd ;};func (_adee ScatterChartSeries )InitializeDefaults (){_adee .Properties ().LineProperties ().SetNoFill ();_adee .Marker ().SetSymbol (_gb .ST_MarkerStyleAuto );_adee .Labels ().SetShowLegendKey (false );_adee .Labels ().SetShowValue (true );_adee .Labels ().SetShowPercent (false );_adee .Labels ().SetShowCategoryName (false );_adee .Labels ().SetShowSeriesName (false );_adee .Labels ().SetShowLeaderLines (false );};func (_cbc RadarChart )AddAxis (axis Axis ){_fbbd :=_gb .NewCT_UnsignedInt ();_fbbd .ValAttr =axis .AxisID ();_cbc ._fgc .AxId =append (_cbc ._fgc .AxId ,_fbbd );};type Legend struct{_bgae *_gb .CT_Legend };

// RadarChart is an Radar chart that has a shaded Radar underneath a curve.
type RadarChart struct{chartBase ;_fgc *_gb .CT_RadarChart ;};type NumberDataSource struct{_ffe *_gb .CT_NumDataSource };

// InitializeDefaults initializes an Pie series to the default values.
func (_cadb PieChartSeries )InitializeDefaults (){};

// AddSeries adds a default series to a Stock chart.
func (_acgg StockChart )AddSeries ()LineChartSeries {_fgda :=_gb .NewCT_LineSer ();_acgg ._edf .Ser =append (_acgg ._edf .Ser ,_fgda );_fgda .Idx .ValAttr =uint32 (len (_acgg ._edf .Ser )-1);_fgda .Order .ValAttr =uint32 (len (_acgg ._edf .Ser )-1);_bacd :=LineChartSeries {_fgda };_bacd .Values ().CreateEmptyNumberCache ();_bacd .Properties ().LineProperties ().SetNoFill ();return _bacd ;};

// PieChart is a Pie chart.
type PieChart struct{chartBase ;_cbf *_gb .CT_PieChart ;};

// X returns the inner wrapped XML type.
func (_adg Pie3DChart )X ()*_gb .CT_Pie3DChart {return _adg ._cacd };func (_feaac ValueAxis )SetMajorTickMark (m _gb .ST_TickMark ){if m ==_gb .ST_TickMarkUnset {_feaac ._dffd .MajorTickMark =nil ;}else {_feaac ._dffd .MajorTickMark =_gb .NewCT_TickMark ();_feaac ._dffd .MajorTickMark .ValAttr =m ;};};type SeriesAxis struct{_cfgb *_gb .CT_SerAx };

// MakeAxisDataSource constructs an AxisDataSource wrapper.
func MakeAxisDataSource (x *_gb .CT_AxDataSource )CategoryAxisDataSource {return CategoryAxisDataSource {x };};

// Values returns the bubble size data source.
func (_ebe BubbleChartSeries )BubbleSizes ()NumberDataSource {if _ebe ._afe .BubbleSize ==nil {_ebe ._afe .BubbleSize =_gb .NewCT_NumDataSource ();};return MakeNumberDataSource (_ebe ._afe .BubbleSize );};func (_gfff ValueAxis )MajorGridLines ()GridLines {if _gfff ._dffd .MajorGridlines ==nil {_gfff ._dffd .MajorGridlines =_gb .NewCT_ChartLines ();};return GridLines {_gfff ._dffd .MajorGridlines };};func MakeTitle (x *_gb .CT_Title )Title {return Title {x }};func (_fec ValueAxis )Properties ()_d .ShapeProperties {if _fec ._dffd .SpPr ==nil {_fec ._dffd .SpPr =_cb .NewCT_ShapeProperties ();};return _d .MakeShapeProperties (_fec ._dffd .SpPr );};type GridLines struct{_afcd *_gb .CT_ChartLines };

// AddPieOfPieChart adds a new pie chart to a chart.
func (_bca Chart )AddPieOfPieChart ()PieOfPieChart {_faac :=_gb .NewCT_PlotAreaChoice ();_bca ._daf .Chart .PlotArea .Choice =append (_bca ._daf .Chart .PlotArea .Choice ,_faac );_faac .OfPieChart =_gb .NewCT_OfPieChart ();_bgf :=PieOfPieChart {_fca :_faac .OfPieChart };_bgf .InitializeDefaults ();return _bgf ;};

// X returns the inner wrapped XML type.
func (_ffa ValueAxis )X ()*_gb .CT_ValAx {return _ffa ._dffd };

// Order returns the order of the series
func (_dga LineChartSeries )Order ()uint32 {return _dga ._feaa .Order .ValAttr };func MakeSeriesAxis (x *_gb .CT_SerAx )SeriesAxis {return SeriesAxis {x }};func (_bff SeriesAxis )AxisID ()uint32 {return _bff ._cfgb .AxId .ValAttr };func (_caa StockChart )AddAxis (axis Axis ){_bgd :=_gb .NewCT_UnsignedInt ();_bgd .ValAttr =axis .AxisID ();_caa ._edf .AxId =append (_caa ._edf .AxId ,_bgd );};

// Properties returns the bar chart series shape properties.
func (_ada RadarChartSeries )Properties ()_d .ShapeProperties {if _ada ._gaf .SpPr ==nil {_ada ._gaf .SpPr =_cb .NewCT_ShapeProperties ();};return _d .MakeShapeProperties (_ada ._gaf .SpPr );};

// InitializeDefaults initializes an Radar series to the default values.
func (_agf RadarChartSeries )InitializeDefaults (){};func (_bcbb Surface3DChart )InitializeDefaults (){_bcbb ._dgd .Wireframe =_gb .NewCT_Boolean ();_bcbb ._dgd .Wireframe .ValAttr =_c .Bool (false );_bcbb ._dgd .BandFmts =_gb .NewCT_BandFmts ();for _dcf :=0;_dcf < 15;_dcf ++{_caaf :=_gb .NewCT_BandFmt ();_caaf .Idx .ValAttr =uint32 (_dcf );_caaf .SpPr =_cb .NewCT_ShapeProperties ();_adb :=_d .MakeShapeProperties (_caaf .SpPr );_adb .SetSolidFill (_bcbb .nextColor (_dcf ));_bcbb ._dgd .BandFmts .BandFmt =append (_bcbb ._dgd .BandFmts .BandFmt ,_caaf );};};func (_aadc ValueAxis )AxisID ()uint32 {return _aadc ._dffd .AxId .ValAttr };

// InitializeDefaults the bar chart to its defaults
func (_fdd BarChart )InitializeDefaults (){_fdd .SetDirection (_gb .ST_BarDirCol )};

// CategoryAxis returns the category data source.
func (_da BubbleChartSeries )CategoryAxis ()CategoryAxisDataSource {if _da ._afe .XVal ==nil {_da ._afe .XVal =_gb .NewCT_AxDataSource ();};return MakeAxisDataSource (_da ._afe .XVal );};

// SetType sets the type the secone pie to either pie or bar
func (_dca PieOfPieChart )SetType (t _gb .ST_OfPieType ){_dca ._fca .OfPieType .ValAttr =t };

// AddTitle sets a new title on the chart.
func (_cad Chart )AddTitle ()Title {_cad ._daf .Chart .Title =_gb .NewCT_Title ();_cad ._daf .Chart .Title .Overlay =_gb .NewCT_Boolean ();_cad ._daf .Chart .Title .Overlay .ValAttr =_c .Bool (false );_cad ._daf .Chart .AutoTitleDeleted =_gb .NewCT_Boolean ();_cad ._daf .Chart .AutoTitleDeleted .ValAttr =_c .Bool (false );_dg :=MakeTitle (_cad ._daf .Chart .Title );_dg .InitializeDefaults ();return _dg ;};var NullAxis Axis =nullAxis (0);

// AddSeries adds a default series to an Pie chart.
func (_fad PieChart )AddSeries ()PieChartSeries {_eegd :=_gb .NewCT_PieSer ();_fad ._cbf .Ser =append (_fad ._cbf .Ser ,_eegd );_eegd .Idx .ValAttr =uint32 (len (_fad ._cbf .Ser )-1);_eegd .Order .ValAttr =uint32 (len (_fad ._cbf .Ser )-1);_ccb :=PieChartSeries {_eegd };_ccb .InitializeDefaults ();return _ccb ;};

// SetText sets the series text
func (_cdfb SurfaceChartSeries )SetText (s string ){_cdfb ._ebad .Tx =_gb .NewCT_SerTx ();_cdfb ._ebad .Tx .Choice .V =&s ;};func (_bced ScatterChartSeries )CategoryAxis ()CategoryAxisDataSource {if _bced ._abg .XVal ==nil {_bced ._abg .XVal =_gb .NewCT_AxDataSource ();};return MakeAxisDataSource (_bced ._abg .XVal );};type ScatterChart struct{chartBase ;_aea *_gb .CT_ScatterChart ;};func MakeValueAxis (x *_gb .CT_ValAx )ValueAxis {return ValueAxis {x }};func (_fba LineChartSeries )CategoryAxis ()CategoryAxisDataSource {if _fba ._feaa .Cat ==nil {_fba ._feaa .Cat =_gb .NewCT_AxDataSource ();};return MakeAxisDataSource (_fba ._feaa .Cat );};

// X returns the inner wrapped XML type.
func (_ebf Chart )X ()*_gb .ChartSpace {return _ebf ._daf };

// AddSeries adds a default series to a Bubble chart.
func (_cgc BubbleChart )AddSeries ()BubbleChartSeries {_ab :=_cgc .nextColor (len (_cgc ._bbg .Ser ));_gdd :=_gb .NewCT_BubbleSer ();_cgc ._bbg .Ser =append (_cgc ._bbg .Ser ,_gdd );_gdd .Idx .ValAttr =uint32 (len (_cgc ._bbg .Ser )-1);_gdd .Order .ValAttr =uint32 (len (_cgc ._bbg .Ser )-1);_bgg :=BubbleChartSeries {_gdd };_bgg .InitializeDefaults ();_bgg .Properties ().SetSolidFill (_ab );return _bgg ;};

// X returns the inner wrapped XML type.
func (_edbb RadarChartSeries )X ()*_gb .CT_RadarSer {return _edbb ._gaf };func (_acg DataLabels )SetShowValue (b bool ){_acg .ensureChoice ();_acg ._bfd .Choice .ShowVal =_gb .NewCT_Boolean ();_acg ._bfd .Choice .ShowVal .ValAttr =_c .Bool (b );};

// X returns the inner wrapped XML type.
func (_bad LineChartSeries )X ()*_gb .CT_LineSer {return _bad ._feaa };

// AddPie3DChart adds a new pie chart to a chart.
func (_fdff Chart )AddPie3DChart ()Pie3DChart {_ad (_fdff ._daf .Chart );_ecfd :=_gb .NewCT_PlotAreaChoice ();_fdff ._daf .Chart .PlotArea .Choice =append (_fdff ._daf .Chart .PlotArea .Choice ,_ecfd );_ecfd .Pie3DChart =_gb .NewCT_Pie3DChart ();_ge :=Pie3DChart {_cacd :_ecfd .Pie3DChart };_ge .InitializeDefaults ();return _ge ;};

// Pie3DChart is a Pie3D chart.
type Pie3DChart struct{chartBase ;_cacd *_gb .CT_Pie3DChart ;};

// Marker returns the marker properties.
func (_ceeg ScatterChartSeries )Marker ()Marker {if _ceeg ._abg .Marker ==nil {_ceeg ._abg .Marker =_gb .NewCT_Marker ();};return MakeMarker (_ceeg ._abg .Marker );};func MakeChart (x *_gb .ChartSpace )Chart {return Chart {x }};

// Marker returns the marker properties.
func (_bac LineChartSeries )Marker ()Marker {if _bac ._feaa .Marker ==nil {_bac ._feaa .Marker =_gb .NewCT_Marker ();};return MakeMarker (_bac ._feaa .Marker );};

// AddSeries adds a default series to an Pie chart.
func (_dbc PieOfPieChart )AddSeries ()PieChartSeries {_acga :=_gb .NewCT_PieSer ();_dbc ._fca .Ser =append (_dbc ._fca .Ser ,_acga );_acga .Idx .ValAttr =uint32 (len (_dbc ._fca .Ser )-1);_acga .Order .ValAttr =uint32 (len (_dbc ._fca .Ser )-1);_eag :=PieChartSeries {_acga };_eag .InitializeDefaults ();return _eag ;};

// AddLineChart adds a new line chart to a chart.
func (_bbbd Chart )AddLineChart ()LineChart {_ac :=_gb .NewCT_PlotAreaChoice ();_bbbd ._daf .Chart .PlotArea .Choice =append (_bbbd ._daf .Chart .PlotArea .Choice ,_ac );_ac .LineChart =_gb .NewCT_LineChart ();_ac .LineChart .Grouping =_gb .NewCT_Grouping ();_ac .LineChart .Grouping .ValAttr =_gb .ST_GroupingStandard ;return LineChart {_fea :_ac .LineChart };};

// Properties returns the bar chart series shape properties.
func (_ca AreaChartSeries )Properties ()_d .ShapeProperties {if _ca ._cf .SpPr ==nil {_ca ._cf .SpPr =_cb .NewCT_ShapeProperties ();};return _d .MakeShapeProperties (_ca ._cf .SpPr );};

// SetOrder sets the order of the series
func (_fbc LineChartSeries )SetOrder (idx uint32 ){_fbc ._feaa .Order .ValAttr =idx };

// AddArea3DChart adds a new area chart to a chart.
func (_aa Chart )AddArea3DChart ()Area3DChart {_ad (_aa ._daf .Chart );_edca :=_gb .NewCT_PlotAreaChoice ();_aa ._daf .Chart .PlotArea .Choice =append (_aa ._daf .Chart .PlotArea .Choice ,_edca );_edca .Area3DChart =_gb .NewCT_Area3DChart ();_fde :=Area3DChart {_gba :_edca .Area3DChart };_fde .InitializeDefaults ();return _fde ;};

// AddSeries adds a default series to a Surface chart.
func (_cbed SurfaceChart )AddSeries ()SurfaceChartSeries {_gdb :=_cbed .nextColor (len (_cbed ._afce .Ser ));_ddc :=_gb .NewCT_SurfaceSer ();_cbed ._afce .Ser =append (_cbed ._afce .Ser ,_ddc );_ddc .Idx .ValAttr =uint32 (len (_cbed ._afce .Ser )-1);_ddc .Order .ValAttr =uint32 (len (_cbed ._afce .Ser )-1);_aaf :=SurfaceChartSeries {_ddc };_aaf .InitializeDefaults ();_aaf .Properties ().LineProperties ().SetSolidFill (_gdb );return _aaf ;};

// X returns the inner wrapped XML type.
func (_deba SurfaceChart )X ()*_gb .CT_SurfaceChart {return _deba ._afce };

// InitializeDefaults the bar chart to its defaults
func (_ceb RadarChart )InitializeDefaults (){_ceb ._fgc .RadarStyle .ValAttr =_gb .ST_RadarStyleMarker };func (_cga CategoryAxis )MajorGridLines ()GridLines {if _cga ._ba .MajorGridlines ==nil {_cga ._ba .MajorGridlines =_gb .NewCT_ChartLines ();};return GridLines {_cga ._ba .MajorGridlines };};

// Values returns the value data source.
func (_edc BubbleChartSeries )Values ()NumberDataSource {if _edc ._afe .YVal ==nil {_edc ._afe .YVal =_gb .NewCT_NumDataSource ();};return MakeNumberDataSource (_edc ._afe .YVal );};func (_afbe Title )ParagraphProperties ()_d .ParagraphProperties {if _afbe ._gded .Tx ==nil {_afbe .SetText ("");};if _afbe ._gded .Tx .Choice .Rich .P [0].PPr ==nil {_afbe ._gded .Tx .Choice .Rich .P [0].PPr =_cb .NewCT_TextParagraphProperties ();};return _d .MakeParagraphProperties (_afbe ._gded .Tx .Choice .Rich .P [0].PPr );};