//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

package powerpoint ;import (_f "encoding/xml";_g "fmt";_fe "github.com/unidoc/unioffice";);

// Validate validates the Iscomment and its children
func (_eee *Iscomment )Validate ()error {return _eee .ValidateWithPath ("\u0049s\u0063\u006f\u006d\u006d\u0065\u006et");};type Iscomment struct{CT_Empty };func (_eea *CT_Rel )UnmarshalXML (d *_f .Decoder ,start _f .StartElement )error {for _ ,_cg :=range start .Attr {if _cg .Name .Local =="\u0069\u0064"{_bf ,_af :=_cg .Value ,error (nil );
if _af !=nil {return _af ;};_eea .IdAttr =&_bf ;continue ;};};for {_gc ,_eg :=d .Token ();if _eg !=nil {return _g .Errorf ("\u0070a\u0072s\u0069\u006e\u0067\u0020\u0043T\u005f\u0052e\u006c\u003a\u0020\u0025\u0073",_eg );};if _ac ,_dd :=_gc .(_f .EndElement );
_dd &&_ac .Name ==start .Name {break ;};};return nil ;};func (_aff *Iscomment )MarshalXML (e *_f .Encoder ,start _f .StartElement )error {start .Attr =append (start .Attr ,_f .Attr {Name :_f .Name {Local :"\u0078\u006d\u006cn\u0073"},Value :"\u0075\u0072\u006e\u003a\u0073\u0063\u0068e\u006d\u0061\u0073-\u006d\u0069\u0063\u0072o\u0073\u006f\u0066\u0074\u002d\u0063\u006f\u006d\u003a\u006f\u0066\u0066\u0069\u0063\u0065\u003a\u0070\u006f\u0077\u0065\u0072\u0070\u006f\u0069\u006e\u0074"});
start .Attr =append (start .Attr ,_f .Attr {Name :_f .Name {Local :"\u0078m\u006c\u006e\u0073\u003a\u0078\u006dl"},Value :"\u0068\u0074tp\u003a\u002f\u002fw\u0077\u0077\u002e\u00773.o\u0072g/\u0058\u004d\u004c\u002f\u0031\u0039\u00398/\u006e\u0061\u006d\u0065\u0073\u0070\u0061c\u0065"});
start .Name .Local ="\u0069s\u0063\u006f\u006d\u006d\u0065\u006et";return _aff .CT_Empty .MarshalXML (e ,start );};

// ValidateWithPath validates the CT_Rel and its children, prefixing error messages with path
func (_ec *CT_Rel )ValidateWithPath (path string )error {return nil };func (_bc *CT_Rel )MarshalXML (e *_f .Encoder ,start _f .StartElement )error {if _bc .IdAttr !=nil {start .Attr =append (start .Attr ,_f .Attr {Name :_f .Name {Local :"\u0069\u0064"},Value :_g .Sprintf ("\u0025\u0076",*_bc .IdAttr )});
};e .EncodeToken (start );e .EncodeToken (_f .EndElement {Name :start .Name });return nil ;};type CT_Empty struct{};func NewCT_Rel ()*CT_Rel {_d :=&CT_Rel {};return _d };func NewIscomment ()*Iscomment {_cd :=&Iscomment {};_cd .CT_Empty =*NewCT_Empty ();
return _cd };

// ValidateWithPath validates the CT_Empty and its children, prefixing error messages with path
func (_feb *CT_Empty )ValidateWithPath (path string )error {return nil };func (_cdd *Textdata )UnmarshalXML (d *_f .Decoder ,start _f .StartElement )error {_cdd .CT_Rel =*NewCT_Rel ();for _ ,_gb :=range start .Attr {if _gb .Name .Local =="\u0069\u0064"{_dc ,_cgd :=_gb .Value ,error (nil );
if _cgd !=nil {return _cgd ;};_cdd .IdAttr =&_dc ;continue ;};};for {_cgf ,_bga :=d .Token ();if _bga !=nil {return _g .Errorf ("p\u0061r\u0073\u0069\u006e\u0067\u0020\u0054\u0065\u0078t\u0064\u0061\u0074\u0061: \u0025\u0073",_bga );};if _de ,_acd :=_cgf .(_f .EndElement );
_acd &&_de .Name ==start .Name {break ;};};return nil ;};type Textdata struct{CT_Rel };

// ValidateWithPath validates the Textdata and its children, prefixing error messages with path
func (_ge *Textdata )ValidateWithPath (path string )error {if _bb :=_ge .CT_Rel .ValidateWithPath (path );_bb !=nil {return _bb ;};return nil ;};

// Validate validates the Textdata and its children
func (_bd *Textdata )Validate ()error {return _bd .ValidateWithPath ("\u0054\u0065\u0078\u0074\u0064\u0061\u0074\u0061");};func NewCT_Empty ()*CT_Empty {_ad :=&CT_Empty {};return _ad };func NewTextdata ()*Textdata {_adc :=&Textdata {};_adc .CT_Rel =*NewCT_Rel ();
return _adc };type CT_Rel struct{IdAttr *string ;};

// Validate validates the CT_Empty and its children
func (_ea *CT_Empty )Validate ()error {return _ea .ValidateWithPath ("\u0043\u0054\u005f\u0045\u006d\u0070\u0074\u0079");};func (_e *CT_Empty )MarshalXML (e *_f .Encoder ,start _f .StartElement )error {e .EncodeToken (start );e .EncodeToken (_f .EndElement {Name :start .Name });
return nil ;};func (_eec *Textdata )MarshalXML (e *_f .Encoder ,start _f .StartElement )error {start .Attr =append (start .Attr ,_f .Attr {Name :_f .Name {Local :"\u0078\u006d\u006cn\u0073"},Value :"\u0075\u0072\u006e\u003a\u0073\u0063\u0068e\u006d\u0061\u0073-\u006d\u0069\u0063\u0072o\u0073\u006f\u0066\u0074\u002d\u0063\u006f\u006d\u003a\u006f\u0066\u0066\u0069\u0063\u0065\u003a\u0070\u006f\u0077\u0065\u0072\u0070\u006f\u0069\u006e\u0074"});
start .Attr =append (start .Attr ,_f .Attr {Name :_f .Name {Local :"\u0078m\u006c\u006e\u0073\u003a\u0078\u006dl"},Value :"\u0068\u0074tp\u003a\u002f\u002fw\u0077\u0077\u002e\u00773.o\u0072g/\u0058\u004d\u004c\u002f\u0031\u0039\u00398/\u006e\u0061\u006d\u0065\u0073\u0070\u0061c\u0065"});
start .Name .Local ="\u0074\u0065\u0078\u0074\u0064\u0061\u0074\u0061";return _eec .CT_Rel .MarshalXML (e ,start );};func (_adg *Iscomment )UnmarshalXML (d *_f .Decoder ,start _f .StartElement )error {_adg .CT_Empty =*NewCT_Empty ();for {_eb ,_ba :=d .Token ();
if _ba !=nil {return _g .Errorf ("p\u0061\u0072\u0073\u0069ng\u0020I\u0073\u0063\u006f\u006d\u006de\u006e\u0074\u003a\u0020\u0025\u0073",_ba );};if _bgb ,_ag :=_eb .(_f .EndElement );_ag &&_bgb .Name ==start .Name {break ;};};return nil ;};

// ValidateWithPath validates the Iscomment and its children, prefixing error messages with path
func (_gg *Iscomment )ValidateWithPath (path string )error {if _ddc :=_gg .CT_Empty .ValidateWithPath (path );_ddc !=nil {return _ddc ;};return nil ;};

// Validate validates the CT_Rel and its children
func (_add *CT_Rel )Validate ()error {return _add .ValidateWithPath ("\u0043\u0054\u005f\u0052\u0065\u006c");};func (_ee *CT_Empty )UnmarshalXML (d *_f .Decoder ,start _f .StartElement )error {for {_b ,_c :=d .Token ();if _c !=nil {return _g .Errorf ("p\u0061r\u0073\u0069\u006e\u0067\u0020\u0043\u0054\u005fE\u006d\u0070\u0074\u0079: \u0025\u0073",_c );
};if _ae ,_bg :=_b .(_f .EndElement );_bg &&_ae .Name ==start .Name {break ;};};return nil ;};func init (){_fe .RegisterConstructor ("\u0075\u0072\u006e\u003a\u0073\u0063\u0068e\u006d\u0061\u0073-\u006d\u0069\u0063\u0072o\u0073\u006f\u0066\u0074\u002d\u0063\u006f\u006d\u003a\u006f\u0066\u0066\u0069\u0063\u0065\u003a\u0070\u006f\u0077\u0065\u0072\u0070\u006f\u0069\u006e\u0074","\u0043\u0054\u005f\u0045\u006d\u0070\u0074\u0079",NewCT_Empty );
_fe .RegisterConstructor ("\u0075\u0072\u006e\u003a\u0073\u0063\u0068e\u006d\u0061\u0073-\u006d\u0069\u0063\u0072o\u0073\u006f\u0066\u0074\u002d\u0063\u006f\u006d\u003a\u006f\u0066\u0066\u0069\u0063\u0065\u003a\u0070\u006f\u0077\u0065\u0072\u0070\u006f\u0069\u006e\u0074","\u0043\u0054\u005f\u0052\u0065\u006c",NewCT_Rel );
_fe .RegisterConstructor ("\u0075\u0072\u006e\u003a\u0073\u0063\u0068e\u006d\u0061\u0073-\u006d\u0069\u0063\u0072o\u0073\u006f\u0066\u0074\u002d\u0063\u006f\u006d\u003a\u006f\u0066\u0066\u0069\u0063\u0065\u003a\u0070\u006f\u0077\u0065\u0072\u0070\u006f\u0069\u006e\u0074","\u0069s\u0063\u006f\u006d\u006d\u0065\u006et",NewIscomment );
_fe .RegisterConstructor ("\u0075\u0072\u006e\u003a\u0073\u0063\u0068e\u006d\u0061\u0073-\u006d\u0069\u0063\u0072o\u0073\u006f\u0066\u0074\u002d\u0063\u006f\u006d\u003a\u006f\u0066\u0066\u0069\u0063\u0065\u003a\u0070\u006f\u0077\u0065\u0072\u0070\u006f\u0069\u006e\u0074","\u0074\u0065\u0078\u0074\u0064\u0061\u0074\u0061",NewTextdata );
};