//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

package mergesort ;func MergeSort (array []float64 )[]float64 {if len (array )<=1{_d :=make ([]float64 ,len (array ));copy (_d ,array );return _d ;};_c :=len (array )/2;_a :=MergeSort (array [:_c ]);_be :=MergeSort (array [_c :]);_e :=make ([]float64 ,len (array ));
_ag :=0;_bd :=0;_agb :=0;for _bd < len (_a )&&_agb < len (_be ){if _a [_bd ]<=_be [_agb ]{_e [_ag ]=_a [_bd ];_bd ++;}else {_e [_ag ]=_be [_agb ];_agb ++;};_ag ++;};for _bd < len (_a ){_e [_ag ]=_a [_bd ];_bd ++;_ag ++;};for _agb < len (_be ){_e [_ag ]=_be [_agb ];
_agb ++;_ag ++;};return _e ;};