//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

package mergesort ;func MergeSort (array []float64 )[]float64 {if len (array )<=1{_c :=make ([]float64 ,len (array ));copy (_c ,array );return _c ;};_cd :=len (array )/2;_e :=MergeSort (array [:_cd ]);_ed :=MergeSort (array [_cd :]);_gg :=make ([]float64 ,len (array ));_b :=0;_a :=0;_cc :=0;for _a < len (_e )&&_cc < len (_ed ){if _e [_a ]<=_ed [_cc ]{_gg [_b ]=_e [_a ];_a ++;}else {_gg [_b ]=_ed [_cc ];_cc ++;};_b ++;};for _a < len (_e ){_gg [_b ]=_e [_a ];_a ++;_b ++;};for _cc < len (_ed ){_gg [_b ]=_ed [_cc ];_cc ++;_b ++;};return _gg ;};