//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

// Package diskstore implements tempStorage interface
// by using disk as a storage
package diskstore ;import (_gf "github.com/unidoc/unioffice/common/tempstorage";_g "io/ioutil";_ec "os";_e "strings";);

// SetAsStorage sets temp storage as a disk storage
func SetAsStorage (){_eb :=diskStorage {};_gf .SetAsStorage (&_eb )};

// Add is not applicable in the diskstore implementation
func (_f diskStorage )Add (path string )error {return nil };

// RemoveAll removes all files in the directory
func (_eg diskStorage )RemoveAll (dir string )error {if _e .HasPrefix (dir ,_ec .TempDir ()){return _ec .RemoveAll (dir );};return nil ;};

// TempFile creates a new temp file by calling ioutil TempFile
func (_cd diskStorage )TempFile (dir ,pattern string )(_gf .File ,error ){return _g .TempFile (dir ,pattern );};

// TempFile creates a new temp directory by calling ioutil TempDir
func (_b diskStorage )TempDir (pattern string )(string ,error ){return _g .TempDir ("",pattern )};

// Open opens file from disk according to a path
func (_ed diskStorage )Open (path string )(_gf .File ,error ){return _ec .OpenFile (path ,_ec .O_RDWR ,0644);};type diskStorage struct{};