//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

// Package diskstore implements tempStorage interface
// by using disk as a storage
package diskstore ;import (_d "github.com/unidoc/unioffice/common/tempstorage";_g "io/ioutil";_ea "os";_ee "strings";);

// TempFile creates a new temp directory by calling ioutil TempDir
func (_ga diskStorage )TempDir (pattern string )(string ,error ){return _g .TempDir ("",pattern )};

// SetAsStorage sets temp storage as a disk storage
func SetAsStorage (){_de :=diskStorage {};_d .SetAsStorage (&_de )};

// Open opens file from disk according to a path
func (_ec diskStorage )Open (path string )(_d .File ,error ){return _ea .Open (path )};

// Add is not applicable in the diskstore implementation
func (_ge diskStorage )Add (path string )error {return nil };

// RemoveAll removes all files in the directory
func (_dc diskStorage )RemoveAll (dir string )error {if _ee .HasPrefix (dir ,_ea .TempDir ()){return _ea .RemoveAll (dir );};return nil ;};

// TempFile creates a new temp file by calling ioutil TempFile
func (_c diskStorage )TempFile (dir ,pattern string )(_d .File ,error ){return _g .TempFile (dir ,pattern );};type diskStorage struct{};