//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

package wildcard ;func _fc (_ab ,_af []rune ,_fg bool )bool {for len (_af )> 0{switch _af [0]{default:if len (_ab )==0||_ab [0]!=_af [0]{return false ;};case '?':if len (_ab )==0&&!_fg {return false ;};case '*':return _fc (_ab ,_af [1:],_fg )||(len (_ab )> 0&&_fc (_ab [1:],_af ,_fg ));};_ab =_ab [1:];_af =_af [1:];};return len (_ab )==0&&len (_af )==0;};func Match (pattern ,name string )(_db bool ){if pattern ==""{return name ==pattern ;};if pattern =="\u002a"{return true ;};_gf :=make ([]rune ,0,len (name ));_ag :=make ([]rune ,0,len (pattern ));for _ ,_fd :=range name {_gf =append (_gf ,_fd );};for _ ,_ae :=range pattern {_ag =append (_ag ,_ae );};_cf :=false ;return _fc (_gf ,_ag ,_cf );};func Index (pattern ,name string )(_e int ){if pattern ==""||pattern =="\u002a"{return 0;};_ce :=make ([]rune ,0,len (name ));_ad :=make ([]rune ,0,len (pattern ));for _ ,_aed :=range name {_ce =append (_ce ,_aed );};for _ ,_eb :=range pattern {_ad =append (_ad ,_eb );};return _gd (_ce ,_ad ,0);};func MatchSimple (pattern ,name string )bool {if pattern ==""{return name ==pattern ;};if pattern =="\u002a"{return true ;};_f :=make ([]rune ,0,len (name ));_a :=make ([]rune ,0,len (pattern ));for _ ,_g :=range name {_f =append (_f ,_g );};for _ ,_cg :=range pattern {_a =append (_a ,_cg );};_d :=true ;return _fc (_f ,_a ,_d );};func _gd (_ea ,_ada []rune ,_fe int )int {for len (_ada )> 0{switch _ada [0]{default:if len (_ea )==0{return -1;};if _ea [0]!=_ada [0]{return _gd (_ea [1:],_ada ,_fe +1);};case '?':if len (_ea )==0{return -1;};case '*':if len (_ea )==0{return -1;};_ge :=_gd (_ea ,_ada [1:],_fe );if _ge !=-1{return _fe ;}else {_ge =_gd (_ea [1:],_ada ,_fe );if _ge !=-1{return _fe ;}else {return -1;};};};_ea =_ea [1:];_ada =_ada [1:];};return _fe ;};