//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

package drawing ;import (_d "github.com/unidoc/unioffice";_g "github.com/unidoc/unioffice/color";_e "github.com/unidoc/unioffice/measurement";_dc "github.com/unidoc/unioffice/schema/soo/dml";);

// SetAlign controls the paragraph alignment
func (_fa ParagraphProperties )SetAlign (a _dc .ST_TextAlignType ){_fa ._af .AlgnAttr =a };func (_fec ShapeProperties )ensureXfrm (){if _fec ._gbe .Xfrm ==nil {_fec ._gbe .Xfrm =_dc .NewCT_Transform2D ();};};

// ParagraphProperties allows controlling paragraph properties.
type ParagraphProperties struct{_af *_dc .CT_TextParagraphProperties ;};func MakeShapeProperties (x *_dc .CT_ShapeProperties )ShapeProperties {return ShapeProperties {x }};

// AddRun adds a new run to a paragraph.
func (_df Paragraph )AddRun ()Run {_ff :=MakeRun (_dc .NewEG_TextRun ());_df ._gd .EG_TextRun =append (_df ._gd .EG_TextRun ,_ff .X ());return _ff ;};

// SetBulletFont controls the font for the bullet character.
func (_ebe ParagraphProperties )SetBulletFont (f string ){if f ==""{_ebe ._af .BuFont =nil ;}else {_ebe ._af .BuFont =_dc .NewCT_TextFont ();_ebe ._af .BuFont .TypefaceAttr =f ;};};

// SetWidth sets the width of the shape.
func (_gf ShapeProperties )SetWidth (w _e .Distance ){_gf .ensureXfrm ();if _gf ._gbe .Xfrm .Ext ==nil {_gf ._gbe .Xfrm .Ext =_dc .NewCT_PositiveSize2D ();};_gf ._gbe .Xfrm .Ext .CxAttr =int64 (w /_e .EMU );};

// SetBulletChar sets the bullet character for the paragraph.
func (_ac ParagraphProperties )SetBulletChar (c string ){if c ==""{_ac ._af .BuChar =nil ;}else {_ac ._af .BuChar =_dc .NewCT_TextCharBullet ();_ac ._af .BuChar .CharAttr =c ;};};

// SetFont controls the font of a run.
func (_bg RunProperties )SetFont (s string ){_bg ._fc .Latin =_dc .NewCT_TextFont ();_bg ._fc .Latin .TypefaceAttr =s ;};

// SetText sets the run's text contents.
func (_egd Run )SetText (s string ){_egd ._ae .Br =nil ;_egd ._ae .Fld =nil ;if _egd ._ae .R ==nil {_egd ._ae .R =_dc .NewCT_RegularTextRun ();};_egd ._ae .R .T =s ;};

// SetPosition sets the position of the shape.
func (_gdg ShapeProperties )SetPosition (x ,y _e .Distance ){_gdg .ensureXfrm ();if _gdg ._gbe .Xfrm .Off ==nil {_gdg ._gbe .Xfrm .Off =_dc .NewCT_Point2D ();};_gdg ._gbe .Xfrm .Off .XAttr .ST_CoordinateUnqualified =_d .Int64 (int64 (x /_e .EMU ));_gdg ._gbe .Xfrm .Off .YAttr .ST_CoordinateUnqualified =_d .Int64 (int64 (y /_e .EMU ));};const (LineJoinRound LineJoin =iota ;LineJoinBevel ;LineJoinMiter ;);

// SetFlipVertical controls if the shape is flipped vertically.
func (_gdd ShapeProperties )SetFlipVertical (b bool ){_gdd .ensureXfrm ();if !b {_gdd ._gbe .Xfrm .FlipVAttr =nil ;}else {_gdd ._gbe .Xfrm .FlipVAttr =_d .Bool (true );};};

// AddBreak adds a new line break to a paragraph.
func (_ecc Paragraph )AddBreak (){_fg :=_dc .NewEG_TextRun ();_fg .Br =_dc .NewCT_TextLineBreak ();_ecc ._gd .EG_TextRun =append (_ecc ._gd .EG_TextRun ,_fg );};

// SetFlipHorizontal controls if the shape is flipped horizontally.
func (_bga ShapeProperties )SetFlipHorizontal (b bool ){_bga .ensureXfrm ();if !b {_bga ._gbe .Xfrm .FlipHAttr =nil ;}else {_bga ._gbe .Xfrm .FlipHAttr =_d .Bool (true );};};

// SetSize sets the font size of the run text
func (_ecb RunProperties )SetSize (sz _e .Distance ){_ecb ._fc .SzAttr =_d .Int32 (int32 (sz /_e .HundredthPoint ));};

// Properties returns the paragraph properties.
func (_gb Paragraph )Properties ()ParagraphProperties {if _gb ._gd .PPr ==nil {_gb ._gd .PPr =_dc .NewCT_TextParagraphProperties ();};return MakeParagraphProperties (_gb ._gd .PPr );};

// SetWidth sets the line width, MS products treat zero as the minimum width
// that can be displayed.
func (_a LineProperties )SetWidth (w _e .Distance ){_a ._de .WAttr =_d .Int32 (int32 (w /_e .EMU ))};

// Properties returns the run's properties.
func (_fge Run )Properties ()RunProperties {if _fge ._ae .R ==nil {_fge ._ae .R =_dc .NewCT_RegularTextRun ();};if _fge ._ae .R .RPr ==nil {_fge ._ae .R .RPr =_dc .NewCT_TextCharacterProperties ();};return RunProperties {_fge ._ae .R .RPr };};

// Run is a run within a paragraph.
type Run struct{_ae *_dc .EG_TextRun };

// RunProperties controls the run properties.
type RunProperties struct{_fc *_dc .CT_TextCharacterProperties ;};type ShapeProperties struct{_gbe *_dc .CT_ShapeProperties };

// MakeParagraphProperties constructs a new ParagraphProperties wrapper.
func MakeParagraphProperties (x *_dc .CT_TextParagraphProperties )ParagraphProperties {return ParagraphProperties {x };};

// MakeRunProperties constructs a new RunProperties wrapper.
func MakeRunProperties (x *_dc .CT_TextCharacterProperties )RunProperties {return RunProperties {x }};

// X returns the inner wrapped XML type.
func (_ag ParagraphProperties )X ()*_dc .CT_TextParagraphProperties {return _ag ._af };

// GetPosition gets the position of the shape in EMU.
func (_agc ShapeProperties )GetPosition ()(int64 ,int64 ){_agc .ensureXfrm ();if _agc ._gbe .Xfrm .Off ==nil {_agc ._gbe .Xfrm .Off =_dc .NewCT_Point2D ();};return *_agc ._gbe .Xfrm .Off .XAttr .ST_CoordinateUnqualified ,*_agc ._gbe .Xfrm .Off .YAttr .ST_CoordinateUnqualified ;};func (_ebf ShapeProperties )SetSolidFill (c _g .Color ){_ebf .clearFill ();_ebf ._gbe .SolidFill =_dc .NewCT_SolidColorFillProperties ();_ebf ._gbe .SolidFill .SrgbClr =_dc .NewCT_SRgbColor ();_ebf ._gbe .SolidFill .SrgbClr .ValAttr =*c .AsRGBString ();};

// MakeParagraph constructs a new paragraph wrapper.
func MakeParagraph (x *_dc .CT_TextParagraph )Paragraph {return Paragraph {x }};

// X returns the inner wrapped XML type.
func (_fde ShapeProperties )X ()*_dc .CT_ShapeProperties {return _fde ._gbe };

// X returns the inner wrapped XML type.
func (_fe Paragraph )X ()*_dc .CT_TextParagraph {return _fe ._gd };

// SetGeometry sets the shape type of the shape
func (_ea ShapeProperties )SetGeometry (g _dc .ST_ShapeType ){if _ea ._gbe .PrstGeom ==nil {_ea ._gbe .PrstGeom =_dc .NewCT_PresetGeometry2D ();};_ea ._gbe .PrstGeom .PrstAttr =g ;};func (_b LineProperties )SetNoFill (){_b .clearFill ();_b ._de .NoFill =_dc .NewCT_NoFillProperties ()};

// SetHeight sets the height of the shape.
func (_ede ShapeProperties )SetHeight (h _e .Distance ){_ede .ensureXfrm ();if _ede ._gbe .Xfrm .Ext ==nil {_ede ._gbe .Xfrm .Ext =_dc .NewCT_PositiveSize2D ();};_ede ._gbe .Xfrm .Ext .CyAttr =int64 (h /_e .EMU );};

// SetSolidFill controls the text color of a run.
func (_fd RunProperties )SetSolidFill (c _g .Color ){_fd ._fc .NoFill =nil ;_fd ._fc .BlipFill =nil ;_fd ._fc .GradFill =nil ;_fd ._fc .GrpFill =nil ;_fd ._fc .PattFill =nil ;_fd ._fc .SolidFill =_dc .NewCT_SolidColorFillProperties ();_fd ._fc .SolidFill .SrgbClr =_dc .NewCT_SRgbColor ();_fd ._fc .SolidFill .SrgbClr .ValAttr =*c .AsRGBString ();};

// MakeRun constructs a new Run wrapper.
func MakeRun (x *_dc .EG_TextRun )Run {return Run {x }};func (_aa ShapeProperties )SetNoFill (){_aa .clearFill ();_aa ._gbe .NoFill =_dc .NewCT_NoFillProperties ();};

// X returns the inner wrapped XML type.
func (_bb Run )X ()*_dc .EG_TextRun {return _bb ._ae };

// SetLevel sets the level of indentation of a paragraph.
func (_ed ParagraphProperties )SetLevel (idx int32 ){_ed ._af .LvlAttr =_d .Int32 (idx )};

// LineJoin is the type of line join
type LineJoin byte ;

// X returns the inner wrapped XML type.
func (_ec LineProperties )X ()*_dc .CT_LineProperties {return _ec ._de };func (_ab ShapeProperties )LineProperties ()LineProperties {if _ab ._gbe .Ln ==nil {_ab ._gbe .Ln =_dc .NewCT_LineProperties ();};return LineProperties {_ab ._gbe .Ln };};

// SetSize sets the width and height of the shape.
func (_cd ShapeProperties )SetSize (w ,h _e .Distance ){_cd .SetWidth (w );_cd .SetHeight (h )};

// SetJoin sets the line join style.
func (_gc LineProperties )SetJoin (e LineJoin ){_gc ._de .Round =nil ;_gc ._de .Miter =nil ;_gc ._de .Bevel =nil ;switch e {case LineJoinRound :_gc ._de .Round =_dc .NewCT_LineJoinRound ();case LineJoinBevel :_gc ._de .Bevel =_dc .NewCT_LineJoinBevel ();case LineJoinMiter :_gc ._de .Miter =_dc .NewCT_LineJoinMiterProperties ();};};type LineProperties struct{_de *_dc .CT_LineProperties };func (_eb LineProperties )SetSolidFill (c _g .Color ){_eb .clearFill ();_eb ._de .SolidFill =_dc .NewCT_SolidColorFillProperties ();_eb ._de .SolidFill .SrgbClr =_dc .NewCT_SRgbColor ();_eb ._de .SolidFill .SrgbClr .ValAttr =*c .AsRGBString ();};func (_gg ShapeProperties )clearFill (){_gg ._gbe .NoFill =nil ;_gg ._gbe .BlipFill =nil ;_gg ._gbe .GradFill =nil ;_gg ._gbe .GrpFill =nil ;_gg ._gbe .SolidFill =nil ;_gg ._gbe .PattFill =nil ;};func (_f LineProperties )clearFill (){_f ._de .NoFill =nil ;_f ._de .GradFill =nil ;_f ._de .SolidFill =nil ;_f ._de .PattFill =nil ;};

// SetNumbered controls if bullets are numbered or not.
func (_eg ParagraphProperties )SetNumbered (scheme _dc .ST_TextAutonumberScheme ){if scheme ==_dc .ST_TextAutonumberSchemeUnset {_eg ._af .BuAutoNum =nil ;}else {_eg ._af .BuAutoNum =_dc .NewCT_TextAutonumberBullet ();_eg ._af .BuAutoNum .TypeAttr =scheme ;};};

// SetBold controls the bolding of a run.
func (_db RunProperties )SetBold (b bool ){_db ._fc .BAttr =_d .Bool (b )};

// Paragraph is a paragraph within a document.
type Paragraph struct{_gd *_dc .CT_TextParagraph };