//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

package cid ;import (_d "encoding/xml";_g "fmt";_ag "github.com/unidoc/unioffice";_f "github.com/unidoc/unioffice/common/logger";_b "strconv";);type CT_CommentsIds struct{CommentId []*CT_CommentId ;};func NewCT_CommentsIds ()*CT_CommentsIds {_cfb :=&CT_CommentsIds {};
return _cfb };

// Validate validates the CT_CommentsIds and its children
func (_ec *CT_CommentsIds )Validate ()error {return _ec .ValidateWithPath ("\u0043\u0054\u005f\u0043\u006f\u006d\u006d\u0065\u006et\u0073\u0049\u0064\u0073");};func NewCommentsIds ()*CommentsIds {_dde :=&CommentsIds {};_dde .CT_CommentsIds =*NewCT_CommentsIds ();
return _dde ;};

// ValidateWithPath validates the CT_CommentsIds and its children, prefixing error messages with path
func (_ba *CT_CommentsIds )ValidateWithPath (path string )error {for _def ,_bb :=range _ba .CommentId {if _ca :=_bb .ValidateWithPath (_g .Sprintf ("\u0025\u0073/\u0043\u006f\u006dm\u0065\u006e\u0074\u0049\u0064\u005b\u0025\u0064\u005d",path ,_def ));_ca !=nil {return _ca ;
};};return nil ;};type CT_CommentId struct{ParaIdAttr string ;DurableIdAttr string ;};

// ValidateWithPath validates the CT_CommentId and its children, prefixing error messages with path
func (_cd *CT_CommentId )ValidateWithPath (path string )error {return nil };func (_e *CT_CommentId )UnmarshalXML (d *_d .Decoder ,start _d .StartElement )error {for _ ,_ac :=range start .Attr {if _ac .Name .Local =="\u0070\u0061\u0072\u0061\u0049\u0064"{_c ,_cf :=_ac .Value ,error (nil );
if _cf !=nil {return _cf ;};_e .ParaIdAttr =_c ;continue ;};if _ac .Name .Local =="\u0064u\u0072\u0061\u0062\u006c\u0065\u0049d"{_df ,_ge :=_ac .Value ,error (nil );if _ge !=nil {return _ge ;};_e .DurableIdAttr =_df ;continue ;};};for {_acf ,_fb :=d .Token ();
if _fb !=nil {return _g .Errorf ("\u0070a\u0072\u0073\u0069\u006e\u0067\u0020\u0043\u0054\u005f\u0043\u006fm\u006d\u0065\u006e\u0074\u0049\u0064\u003a\u0020\u0025\u0073",_fb );};if _ae ,_dd :=_acf .(_d .EndElement );_dd &&_ae .Name ==start .Name {break ;
};};return nil ;};func (_de *CT_CommentsIds )MarshalXML (e *_d .Encoder ,start _d .StartElement )error {e .EncodeToken (start );if _de .CommentId !=nil {_fg :=_d .StartElement {Name :_d .Name {Local :"\u0063\u0069\u003ac\u006f\u006d\u006d\u0065\u006e\u0074\u0049\u0064"}};
for _ ,_cc :=range _de .CommentId {e .EncodeElement (_cc ,_fg );};};e .EncodeToken (_d .EndElement {Name :start .Name });return nil ;};type CommentsIds struct{CT_CommentsIds };func NewDecimaldurableId ()*DecimaldurableId {_ga :=&DecimaldurableId {};return _ga };


// ValidateWithPath validates the CommentsIds and its children, prefixing error messages with path
func (_ecd *CommentsIds )ValidateWithPath (path string )error {if _cca :=_ecd .CT_CommentsIds .ValidateWithPath (path );_cca !=nil {return _cca ;};return nil ;};func (_baf *CommentsIds )UnmarshalXML (d *_d .Decoder ,start _d .StartElement )error {_baf .CT_CommentsIds =*NewCT_CommentsIds ();
_dda :for {_bac ,_dg :=d .Token ();if _dg !=nil {return _dg ;};switch _dfg :=_bac .(type ){case _d .StartElement :switch _dfg .Name {case _d .Name {Space :"\u0068\u0074\u0074\u0070\u003a\u002f/\u0073\u0063\u0068e\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002ec\u006f\u006d\u002f\u006f\u0066fi\u0063\u0065\u002f\u0077\u006f\u0072\u0064\u002f\u0032\u0030\u0031\u0036\u002f\u0077\u006f\u0072\u0064\u006d\u006c\u002f\u0063\u0069\u0064",Local :"\u0063o\u006d\u006d\u0065\u006e\u0074\u0049d"}:_da :=NewCT_CommentId ();
if _daf :=d .DecodeElement (_da ,&_dfg );_daf !=nil {return _daf ;};_baf .CommentId =append (_baf .CommentId ,_da );default:_f .Log .Debug ("\u0073\u006bi\u0070\u0070\u0069\u006e\u0067\u0020\u0075\u006e\u0073\u0075\u0070\u0070\u006f\u0072\u0074\u0065\u0064\u0020\u0065\u006c\u0065\u006d\u0065\u006e\u0074\u0020\u006f\u006e\u0020\u0043\u006f\u006d\u006d\u0065\u006e\u0074\u0073\u0049\u0064\u0073\u0020\u0025\u0076",_dfg .Name );
if _ecc :=d .Skip ();_ecc !=nil {return _ecc ;};};case _d .EndElement :break _dda ;case _d .CharData :};};return nil ;};func (_dca *CT_CommentId )MarshalXML (e *_d .Encoder ,start _d .StartElement )error {start .Attr =append (start .Attr ,_d .Attr {Name :_d .Name {Local :"\u0063i\u003a\u0070\u0061\u0072\u0061\u0049d"},Value :_g .Sprintf ("\u0025\u0076",_dca .ParaIdAttr )});
start .Attr =append (start .Attr ,_d .Attr {Name :_d .Name {Local :"\u0063\u0069\u003ad\u0075\u0072\u0061\u0062\u006c\u0065\u0049\u0064"},Value :_g .Sprintf ("\u0025\u0076",_dca .DurableIdAttr )});e .EncodeToken (start );e .EncodeToken (_d .EndElement {Name :start .Name });
return nil ;};

// Validate validates the CommentsIds and its children
func (_af *CommentsIds )Validate ()error {return _af .ValidateWithPath ("C\u006f\u006d\u006d\u0065\u006e\u0074\u0073\u0049\u0064\u0073");};type DecimaldurableId struct{DurableIdAttr *int64 ;};func (_ff *DecimaldurableId )UnmarshalXML (d *_d .Decoder ,start _d .StartElement )error {for _ ,_be :=range start .Attr {if _be .Name .Local =="\u0064u\u0072\u0061\u0062\u006c\u0065\u0049d"{_fa ,_dgf :=_b .ParseInt (_be .Value ,10,64);
if _dgf !=nil {return _dgf ;};_ff .DurableIdAttr =&_fa ;continue ;};};for {_cfbd ,_cdg :=d .Token ();if _cdg !=nil {return _g .Errorf ("\u0070\u0061\u0072\u0073i\u006e\u0067\u0020\u0044\u0065\u0063\u0069\u006d\u0061\u006cd\u0075r\u0061\u0062\u006c\u0065\u0049\u0064\u003a \u0025\u0073",_cdg );
};if _bbe ,_fba :=_cfbd .(_d .EndElement );_fba &&_bbe .Name ==start .Name {break ;};};return nil ;};func (_gd *CommentsIds )MarshalXML (e *_d .Encoder ,start _d .StartElement )error {start .Attr =append (start .Attr ,_d .Attr {Name :_d .Name {Local :"\u0078\u006d\u006cn\u0073"},Value :"\u0068\u0074\u0074\u0070\u003a\u002f/\u0073\u0063\u0068e\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002ec\u006f\u006d\u002f\u006f\u0066fi\u0063\u0065\u002f\u0077\u006f\u0072\u0064\u002f\u0032\u0030\u0031\u0036\u002f\u0077\u006f\u0072\u0064\u006d\u006c\u002f\u0063\u0069\u0064"});
start .Attr =append (start .Attr ,_d .Attr {Name :_d .Name {Local :"\u0078\u006d\u006c\u006e\u0073\u003a\u0063\u0069"},Value :"\u0068\u0074\u0074\u0070\u003a\u002f/\u0073\u0063\u0068e\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002ec\u006f\u006d\u002f\u006f\u0066fi\u0063\u0065\u002f\u0077\u006f\u0072\u0064\u002f\u0032\u0030\u0031\u0036\u002f\u0077\u006f\u0072\u0064\u006d\u006c\u002f\u0063\u0069\u0064"});
start .Attr =append (start .Attr ,_d .Attr {Name :_d .Name {Local :"\u0078m\u006c\u006e\u0073\u003a\u0077"},Value :"ht\u0074\u0070:\u002f\u002f\u0073\u0063\u0068\u0065\u006d\u0061\u0073.\u006f\u0070\u0065\u006e\u0078\u006d\u006c\u0066\u006f\u0072\u006d\u0061\u0074\u0073\u002e\u006f\u0072\u0067\u002f\u0077\u006f\u0072\u0064\u0070\u0072\u006f\u0063\u0065s\u0073i\u006e\u0067\u006d\u006c\u002f\u0032\u0030\u00306\u002fm\u0061\u0069n"});
start .Attr =append (start .Attr ,_d .Attr {Name :_d .Name {Local :"\u0078m\u006c\u006e\u0073\u003a\u0078\u006dl"},Value :"\u0068\u0074tp\u003a\u002f\u002fw\u0077\u0077\u002e\u00773.o\u0072g/\u0058\u004d\u004c\u002f\u0031\u0039\u00398/\u006e\u0061\u006d\u0065\u0073\u0070\u0061c\u0065"});
start .Name .Local ="\u0063\u0069\u003a\u0063\u006f\u006d\u006d\u0065\u006et\u0073\u0049\u0064\u0073";return _gd .CT_CommentsIds .MarshalXML (e ,start );};

// Validate validates the DecimaldurableId and its children
func (_gcc *DecimaldurableId )Validate ()error {return _gcc .ValidateWithPath ("\u0044\u0065c\u0069\u006d\u0061l\u0064\u0075\u0072\u0061\u0062\u006c\u0065\u0049\u0064");};

// Validate validates the CT_CommentId and its children
func (_cg *CT_CommentId )Validate ()error {return _cg .ValidateWithPath ("\u0043\u0054\u005fC\u006f\u006d\u006d\u0065\u006e\u0074\u0049\u0064");};

// ValidateWithPath validates the DecimaldurableId and its children, prefixing error messages with path
func (_bcb *DecimaldurableId )ValidateWithPath (path string )error {return nil };func (_ab *CT_CommentsIds )UnmarshalXML (d *_d .Decoder ,start _d .StartElement )error {_gc :for {_gb ,_fbd :=d .Token ();if _fbd !=nil {return _fbd ;};switch _gbb :=_gb .(type ){case _d .StartElement :switch _gbb .Name {case _d .Name {Space :"\u0068\u0074\u0074\u0070\u003a\u002f/\u0073\u0063\u0068e\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002ec\u006f\u006d\u002f\u006f\u0066fi\u0063\u0065\u002f\u0077\u006f\u0072\u0064\u002f\u0032\u0030\u0031\u0036\u002f\u0077\u006f\u0072\u0064\u006d\u006c\u002f\u0063\u0069\u0064",Local :"\u0063o\u006d\u006d\u0065\u006e\u0074\u0049d"}:_ea :=NewCT_CommentId ();
if _dcb :=d .DecodeElement (_ea ,&_gbb );_dcb !=nil {return _dcb ;};_ab .CommentId =append (_ab .CommentId ,_ea );default:_f .Log .Debug ("\u0073\u006b\u0069\u0070\u0070\u0069n\u0067\u0020\u0075\u006e\u0073\u0075\u0070\u0070\u006f\u0072\u0074\u0065\u0064\u0020\u0065\u006c\u0065\u006d\u0065\u006et\u0020\u006f\u006e\u0020\u0043\u0054\u005f\u0043\u006f\u006d\u006d\u0065\u006e\u0074s\u0049d\u0073\u0020\u0025\u0076",_gbb .Name );
if _gf :=d .Skip ();_gf !=nil {return _gf ;};};case _d .EndElement :break _gc ;case _d .CharData :};};return nil ;};func (_gfg *DecimaldurableId )MarshalXML (e *_d .Encoder ,start _d .StartElement )error {if _gfg .DurableIdAttr !=nil {start .Attr =append (start .Attr ,_d .Attr {Name :_d .Name {Local :"\u0063\u0069\u003ad\u0075\u0072\u0061\u0062\u006c\u0065\u0049\u0064"},Value :_g .Sprintf ("\u0025\u0076",*_gfg .DurableIdAttr )});
};start .Name .Local ="\u0063\u0069\u003a\u0064ec\u0069\u006d\u0061\u006c\u0064\u0075\u0072\u0061\u0062\u006c\u0065\u0049\u0064";return nil ;};func NewCT_CommentId ()*CT_CommentId {_dc :=&CT_CommentId {};return _dc };func init (){_ag .RegisterConstructor ("\u0068\u0074\u0074\u0070\u003a\u002f/\u0073\u0063\u0068e\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002ec\u006f\u006d\u002f\u006f\u0066fi\u0063\u0065\u002f\u0077\u006f\u0072\u0064\u002f\u0032\u0030\u0031\u0036\u002f\u0077\u006f\u0072\u0064\u006d\u006c\u002f\u0063\u0069\u0064","\u0043\u0054\u005f\u0043\u006f\u006d\u006d\u0065\u006et\u0073\u0049\u0064\u0073",NewCT_CommentsIds );
_ag .RegisterConstructor ("\u0068\u0074\u0074\u0070\u003a\u002f/\u0073\u0063\u0068e\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002ec\u006f\u006d\u002f\u006f\u0066fi\u0063\u0065\u002f\u0077\u006f\u0072\u0064\u002f\u0032\u0030\u0031\u0036\u002f\u0077\u006f\u0072\u0064\u006d\u006c\u002f\u0063\u0069\u0064","\u0043\u0054\u005fC\u006f\u006d\u006d\u0065\u006e\u0074\u0049\u0064",NewCT_CommentId );
_ag .RegisterConstructor ("\u0068\u0074\u0074\u0070\u003a\u002f/\u0073\u0063\u0068e\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002ec\u006f\u006d\u002f\u006f\u0066fi\u0063\u0065\u002f\u0077\u006f\u0072\u0064\u002f\u0032\u0030\u0031\u0036\u002f\u0077\u006f\u0072\u0064\u006d\u006c\u002f\u0063\u0069\u0064","c\u006f\u006d\u006d\u0065\u006e\u0074\u0073\u0049\u0064\u0073",NewCommentsIds );
_ag .RegisterConstructor ("\u0068\u0074\u0074\u0070\u003a\u002f/\u0073\u0063\u0068e\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002ec\u006f\u006d\u002f\u006f\u0066fi\u0063\u0065\u002f\u0077\u006f\u0072\u0064\u002f\u0032\u0030\u0031\u0036\u002f\u0077\u006f\u0072\u0064\u006d\u006c\u002f\u0063\u0069\u0064","\u0064\u0065c\u0069\u006d\u0061l\u0064\u0075\u0072\u0061\u0062\u006c\u0065\u0049\u0064",NewDecimaldurableId );
};