//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

package reference ;import (_e "errors";_ag "fmt";_bd "github.com/unidoc/unioffice/spreadsheet/update";_a "regexp";_dc "strconv";_b "strings";);

// ColumnToIndex maps a column to a zero based index (e.g. A = 0, B = 1, AA = 26)
func ColumnToIndex (col string )uint32 {col =_b .ToUpper (col );_cb :=uint32 (0);for _ ,_dg :=range col {_cb *=26;_cb +=uint32 (_dg -'A'+1);};return _cb -1;};

// Update updates reference to point one of the neighboring columns with respect to the update type after removing a row/column.
func (_ad *ColumnReference )Update (updateType _bd .UpdateAction )*ColumnReference {switch updateType {case _bd .UpdateActionRemoveColumn :_ffe :=_ad ;_ffe .ColumnIdx =_ad .ColumnIdx -1;_ffe .Column =IndexToColumn (_ffe .ColumnIdx );return _ffe ;default:return _ad ;
};};

// ParseColumnReference parses a column reference of the form 'Sheet1!A' and splits it
// into sheet name and column segments.
func ParseColumnReference (s string )(ColumnReference ,error ){s =_b .TrimSpace (s );if len (s )< 1{return ColumnReference {},_e .New ("\u0063\u006f\u006c\u0075\u006d\u006e \u0072\u0065\u0066\u0065\u0072\u0065\u006e\u0063\u0065\u0020\u006d\u0075\u0073\u0074\u0020\u0068\u0061\u0076\u0065\u0020a\u0074\u0020\u006c\u0065\u0061\u0073\u0074\u0020\u006f\u006e\u0065\u0020\u0063\u0068a\u0072a\u0063\u0074\u0065\u0072");
};_ba :=ColumnReference {};_eg ,_ed ,_bad :=_cg (s );if _bad !=nil {return ColumnReference {},_bad ;};if _eg !=""{_ba .SheetName =_eg ;};if _ed [0]=='$'{_ba .AbsoluteColumn =true ;_ed =_ed [1:];};if !_c .MatchString (_ed ){return ColumnReference {},_e .New ("\u0063\u006f\u006c\u0075\u006dn\u0020\u0072\u0065\u0066\u0065\u0072\u0065\u006e\u0063\u0065\u0020\u006d\u0075s\u0074\u0020\u0062\u0065\u0020\u0062\u0065\u0074\u0077\u0065\u0065\u006e\u0020\u0041\u0020\u0061\u006e\u0064\u0020\u005a\u005a");
};_ba .Column =_ed ;_ba .ColumnIdx =ColumnToIndex (_ba .Column );return _ba ,nil ;};

// ParseCellReference parses a cell reference of the form 'A10' and splits it
// into column/row segments.
func ParseCellReference (s string )(CellReference ,error ){s =_b .TrimSpace (s );if len (s )< 2{return CellReference {},_e .New ("\u0063\u0065\u006c\u006c\u0020\u0072\u0065\u0066e\u0072\u0065\u006ece\u0020\u006d\u0075\u0073\u0074\u0020h\u0061\u0076\u0065\u0020\u0061\u0074\u0020\u006c\u0065\u0061\u0073\u0074\u0020\u0074\u0077o\u0020\u0063\u0068\u0061\u0072\u0061\u0063\u0074e\u0072\u0073");
};_f :=CellReference {};_dcf ,_bcd ,_bdb :=_cg (s );if _bdb !=nil {return CellReference {},_bdb ;};if _dcf !=""{_f .SheetName =_dcf ;};if s [0]=='$'{_f .AbsoluteColumn =true ;_bcd =_bcd [1:];};_dd :=-1;_gf :for _bdf :=0;_bdf < len (_bcd );_bdf ++{switch {case _bcd [_bdf ]>='0'&&_bcd [_bdf ]<='9'||_bcd [_bdf ]=='$':_dd =_bdf ;
break _gf ;};};switch _dd {case 0:return CellReference {},_ag .Errorf ("\u006e\u006f\u0020\u006cet\u0074\u0065\u0072\u0020\u0070\u0072\u0065\u0066\u0069\u0078\u0020\u0069\u006e\u0020%\u0073",_bcd );case -1:return CellReference {},_ag .Errorf ("\u006eo\u0020d\u0069\u0067\u0069\u0074\u0073\u0020\u0069\u006e\u0020\u0025\u0073",_bcd );
};_f .Column =_bcd [0:_dd ];if _bcd [_dd ]=='$'{_f .AbsoluteRow =true ;_dd ++;};_f .ColumnIdx =ColumnToIndex (_f .Column );_ae ,_bdb :=_dc .ParseUint (_bcd [_dd :],10,32);if _bdb !=nil {return CellReference {},_ag .Errorf ("e\u0072\u0072\u006f\u0072 p\u0061r\u0073\u0069\u006e\u0067\u0020r\u006f\u0077\u003a\u0020\u0025\u0073",_bdb );
};if _ae ==0{return CellReference {},_ag .Errorf ("\u0065\u0072\u0072\u006f\u0072\u0020\u0070\u0061\u0072\u0073i\u006e\u0067\u0020\u0072\u006f\u0077\u003a \u0063\u0061\u006e\u006e\u006f\u0074\u0020\u0062\u0065\u0020\u0030");};_f .RowIdx =uint32 (_ae );
return _f ,nil ;};

// CellReference is a parsed reference to a cell.  Input is of the form 'A1',
// '$C$2', etc.
type CellReference struct{RowIdx uint32 ;ColumnIdx uint32 ;Column string ;AbsoluteColumn bool ;AbsoluteRow bool ;SheetName string ;};

// String returns a string representation of CellReference.
func (_g CellReference )String ()string {_bc :=make ([]byte ,0,4);if _g .AbsoluteColumn {_bc =append (_bc ,'$');};_bc =append (_bc ,_g .Column ...);if _g .AbsoluteRow {_bc =append (_bc ,'$');};_bc =_dc .AppendInt (_bc ,int64 (_g .RowIdx ),10);return string (_bc );
};

// ParseColumnRangeReference splits a range reference of the form "A:B" into its
// components.
func ParseColumnRangeReference (s string )(_age ,_db ColumnReference ,_badf error ){_ead :="";_cd :=_b .Split (s ,"\u0021");if len (_cd )==2{_ead =_cd [0];s =_cd [1];};_fed :=_b .Split (s ,"\u003a");if len (_fed )!=2{return ColumnReference {},ColumnReference {},_e .New ("i\u006ev\u0061\u006c\u0069\u0064\u0020\u0072\u0061\u006eg\u0065\u0020\u0066\u006frm\u0061\u0074");
};if _ead !=""{_fed [0]=_ead +"\u0021"+_fed [0];_fed [1]=_ead +"\u0021"+_fed [1];};_gbd ,_badf :=ParseColumnReference (_fed [0]);if _badf !=nil {return ColumnReference {},ColumnReference {},_badf ;};_fd ,_badf :=ParseColumnReference (_fed [1]);if _badf !=nil {return ColumnReference {},ColumnReference {},_badf ;
};return _gbd ,_fd ,nil ;};

// ParseRangeReference splits a range reference of the form "A1:B5" into its
// components.
func ParseRangeReference (s string )(_gg ,_ddg CellReference ,_ea error ){_cf ,_bcg ,_ea :=_cg (s );if _ea !=nil {return CellReference {},CellReference {},_ea ;};_fee :=_b .Split (_bcg ,"\u003a");if len (_fee )!=2{return CellReference {},CellReference {},_e .New ("i\u006ev\u0061\u006c\u0069\u0064\u0020\u0072\u0061\u006eg\u0065\u0020\u0066\u006frm\u0061\u0074");
};if _cf !=""{_fee [0]=_cf +"\u0021"+_fee [0];_fee [1]=_cf +"\u0021"+_fee [1];};_gb ,_ea :=ParseCellReference (_fee [0]);if _ea !=nil {return CellReference {},CellReference {},_ea ;};_bec ,_ea :=ParseCellReference (_fee [1]);if _ea !=nil {return CellReference {},CellReference {},_ea ;
};return _gb ,_bec ,nil ;};

// IndexToColumn maps a column number to a column name (e.g. 0 = A, 1 = B, 26 = AA)
func IndexToColumn (col uint32 )string {var _edg [64+1]byte ;_bdd :=len (_edg );_cba :=col ;const _abf =26;for _cba >=_abf {_bdd --;_dcfe :=_cba /_abf ;_edg [_bdd ]=byte ('A'+uint (_cba -_dcfe *_abf ));_cba =_dcfe -1;};_bdd --;_edg [_bdd ]=byte ('A'+uint (_cba ));
return string (_edg [_bdd :]);};

// String returns a string representation of ColumnReference.
func (_gff ColumnReference )String ()string {_ab :=make ([]byte ,0,4);if _gff .AbsoluteColumn {_ab =append (_ab ,'$');};_ab =append (_ab ,_gff .Column ...);return string (_ab );};

// ColumnReference is a parsed reference to a column.  Input is of the form 'A',
// '$C', etc.
type ColumnReference struct{ColumnIdx uint32 ;Column string ;AbsoluteColumn bool ;SheetName string ;};var _c =_a .MustCompile ("^\u005b\u0061\u002d\u007aA-\u005a]\u0028\u005b\u0061\u002d\u007aA\u002d\u005a\u005d\u003f\u0029\u0024");func _cg (_fe string )(string ,string ,error ){_egb :="";
_cga :=_b .LastIndex (_fe ,"\u0021");if _cga > -1{_egb =_fe [:_cga ];_fe =_fe [_cga +1:];if _egb ==""{return "","",_e .New ("\u0049n\u0076a\u006c\u0069\u0064\u0020\u0073h\u0065\u0065t\u0020\u006e\u0061\u006d\u0065");};};return _egb ,_fe ,nil ;};

// Update updates reference to point one of the neighboring cells with respect to the update type after removing a row/column.
func (_ff *CellReference )Update (updateType _bd .UpdateAction )*CellReference {switch updateType {case _bd .UpdateActionRemoveColumn :_de :=_ff ;_de .ColumnIdx =_ff .ColumnIdx -1;_de .Column =IndexToColumn (_de .ColumnIdx );return _de ;default:return _ff ;
};};