//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

package algo ;import _ec "strconv";

// NaturalLess compares two strings in a human manner so rId2 sorts less than rId10
func NaturalLess (lhs ,rhs string )bool {_ca ,_e :=0,0;for _ca < len (lhs )&&_e < len (rhs ){_eg :=lhs [_ca ];_ae :=rhs [_e ];_a :=_eb (_eg );_fg :=_eb (_ae );switch {case _a &&!_fg :return true ;case !_a &&_fg :return false ;case !_a &&!_fg :if _eg !=_ae {return _eg < _ae ;};_ca ++;_e ++;default:_ee :=_ca +1;_ege :=_e +1;for _ee < len (lhs )&&_eb (lhs [_ee ]){_ee ++;};for _ege < len (rhs )&&_eb (rhs [_ege ]){_ege ++;};_de ,_ :=_ec .ParseUint (lhs [_ca :_ee ],10,64);_cf ,_ :=_ec .ParseUint (rhs [_ca :_ege ],10,64);if _de !=_cf {return _de < _cf ;};_ca =_ee ;_e =_ege ;};};return len (lhs )< len (rhs );};func _eb (_f byte )bool {return _f >='0'&&_f <='9'};func RepeatString (s string ,cnt int )string {if cnt <=0{return "";};_c :=make ([]byte ,len (s )*cnt );_ad :=[]byte (s );for _gc :=0;_gc < cnt ;_gc ++{copy (_c [_gc :],_ad );};return string (_c );};