//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

package algo ;import _g "strconv";func _gg (_b byte )bool {return _b >='0'&&_b <='9'};

// NaturalLess compares two strings in a human manner so rId2 sorts less than rId10
func NaturalLess (lhs ,rhs string )bool {_dd ,_e :=0,0;for _dd < len (lhs )&&_e < len (rhs ){_f :=lhs [_dd ];_eg :=rhs [_e ];_bd :=_gg (_f );_ef :=_gg (_eg );switch {case _bd &&!_ef :return true ;case !_bd &&_ef :return false ;case !_bd &&!_ef :if _f !=_eg {return _f < _eg ;
};_dd ++;_e ++;default:_a :=_dd +1;_ad :=_e +1;for _a < len (lhs )&&_gg (lhs [_a ]){_a ++;};for _ad < len (rhs )&&_gg (rhs [_ad ]){_ad ++;};_fe ,_ :=_g .ParseUint (lhs [_dd :_a ],10,64);_de ,_ :=_g .ParseUint (rhs [_dd :_ad ],10,64);if _fe !=_de {return _fe < _de ;
};_dd =_a ;_e =_ad ;};};return len (lhs )< len (rhs );};func RepeatString (s string ,cnt int )string {if cnt <=0{return "";};_dc :=make ([]byte ,len (s )*cnt );_ag :=[]byte (s );for _ce :=0;_ce < cnt ;_ce ++{copy (_dc [_ce :],_ag );};return string (_dc );
};